### ISSUE TITLE
We are getting conflicting scan result for password protected .rar file with windows and linux clamav install.

### ISSUE THREAD

**Issue by clamavissue** [Cisco-Talos/clamav#1006]
Describe the bug
----------------
We are testing scan for password protected .rar file using clamav install on windows and linux machine. we are getting file as infected on windows install and clean on linux install.

How to reproduce the problem
----------------------------
1. Created one .rar file and given password to it to make it encrypted.
2. I am not able to attach it with this bug as this file type is not supported to attach here.
3. Installed  clamAV on windows and EC2 instance with MAC os. Tried with scanning password protected .rar file using 'clamdscan' command. We get conflicting result on windows and linux both installations.
4. Below are installation details for both windows and linux installations. 
5. We have tested other encrypted files like pdf,zip and doc also noted down results. These files dont have conflicting result like rar file. We are expecting here same results on windows and linux platform.

Windows result is as below -
-----------------------------------------------------------------------

  D:\clamav-0.105.1.win.x64>clamdscan Readme.rar
D:\clamav-0.105.1.win.x64\Readme.rar: Heuristics.Encrypted.RAR FOUND

----------- SCAN SUMMARY -----------
Infected files: 1
Time: 0.200 sec (0 m 0 s)
Start Date: 2023:08:21 12:21:05
End Date:   2023:08:21 12:21:05

Linux result  is as follows-
-----------------------------------------------------------------
[root@ip-10-0-2-241 /]# clamdscan ../testfiles/Readme.rar
/testfiles/Readme.rar: OK

----------- SCAN SUMMARY -----------
Infected files: 0
Time: 0.003 sec (0 m 0 s)
Start Date: 2023:08:21 05:46:20
End Date:   2023:08:21 05:46:20

Output of clamconf -n for windows and linux machine 
Windows -
--------------------------------
D:\clamav-0.105.1.win.x64>clamconf -n
Checking configuration files in D:\clamav-0.105.1.win.x64

Config file: clamd.conf
-----------------------
LogFile = "D:\clamav-0.105.1.win.x64\clamd.log"
ExtendedDetectionInfo = "yes"
TCPSocket = "3310"
TCPAddr = "localhost"
AlertEncrypted = "yes"

Config file: freshclam.conf
---------------------------
LogTime = "yes"
LogSyslog = "yes"
LogFacility = "LOG_MAIL"
LogVerbose = "yes"
LogRotate = "yes"
PidFile = "D:\clamav-0.105.1.win.x64\freshclam.pid"
UpdateLogFile = "D:\clamav-0.105.1.win.x64\freshclam.log"
DatabaseMirror = "database.clamav.net"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.105.1
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 JSON RAR

Database information
--------------------
Database directory: D:\clamav-0.105.1.win.x64\database
bytecode.cvd: version 334, sigs: 91, built on Thu Feb 23 03:03:21 2023
daily.cld: version 26933, sigs: 2036707, built on Thu Jun  8 12:56:06 2023
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 18:02:42 2021
Total number of signatures: 8684225

Platform information
--------------------
uname: Microsoft Windows 6.2 SP0.0 Build 9200
OS: Windows, ARCH: AMD64, CPU: AMD64
zlib version: 1.2.12 (1.2.12), compile flags: 65
platform id: 0x10259797080000000000077c

Build information
-----------------
Microsoft Visual C++: (0.7.124)
sizeof(void*) = 8
Engine flevel: 151, dconf: 151

Linux machine 
-----------------------------------------

sh-4.2$ clamconf -n
Checking configuration files in /etc

Config file: clamd.d/scan.conf
------------------------------
LogSyslog = "yes"
ExtendedDetectionInfo = "yes"
PidFile = "/run/clamd.scan/clamd.pid"
TemporaryDirectory = "/var/tmp"
LocalSocket = "/run/clamd.scan/clamd.sock"
User = "clamscan"
AlertEncrypted = "yes"
AlertEncryptedArchive = "yes"
AlertEncryptedDoc = "yes"

freshclam.conf not found

mail/clamav-milter.conf not found

Software settings
-----------------
Version: 0.103.8
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE ICONV JSON

Database information
--------------------
Database directory: /var/lib/clamav
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 12:32:42 2021
bytecode.cvd: version 334, sigs: 91, built on Wed Feb 22 21:33:21 2023
daily.cld: version 27006, sigs: 2039951, built on Sun Aug 20 07:37:21 2023
Total number of signatures: 8687469

Platform information
--------------------
uname: Linux 4.14.314-238.539.amzn2.x86_64 #1 SMP Tue May 23 16:44:05 UTC 2023 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.7 (1.2.7), compile flags: a9
platform id: 0x0a2181810800000000070301

Build information
-----------------
GNU C: 7.3.1 20180712 (Red Hat 7.3.1-15) (7.3.1)
CPPFLAGS:
CFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic
LDFLAGS: -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--as-needed
Configure: '--build=x86_64-koji-linux-gnu' '--host=x86_64-koji-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-milter' '--disable-clamav' '--disable-static' '--disable-zlib-vcheck' '--disable-unrar' '--enable-id-check' '--enable-dns' '--with-dbdir=/var/lib/clamav' '--with-group=clamupdate' '--with-user=clamupdate' '--disable-rpath' '--disable-silent-rules' '--enable-clamdtop' '--disable-prelude' 'build_alias=x86_64-koji-linux-gnu' 'host_alias=x86_64-koji-linux-gnu' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--as-needed' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
sizeof(void*) = 8
Engine flevel: 129, dconf: 129

 
Attachments
-----------
I am not able to attach my test file Readme.rar here as this file type is not supported to attach here.
To create rar file first install winrar on your machine. 
On your side you can quickly create from any test rar file with click on text file and right click and select Add to Archieve option and select format as RAR. Also click on set password button to set password to file.

Please let me know if any more info is required.

**Comment by micahsnyder** [comment]
It looks like you're comparing clamav on:
- Windows with v0.105.1
- Linux with 0.103.8

I doubt very much that the difference has to do with OS.  More likely, 0.105 is better at detecting encrypted archives than 0.103.

You might try grabbing the Windows 0.103.9 version to compare 0.103 vs 0.103: https://www.clamav.net/downloads

Side note: 0.105 is no longer supported, so unless you downgrade to 0.103 to match your Linux environment, you may wish to upgrade to version 1.1.1.

**Comment by dmitrydonskih** [comment]
I also confirm ClamD 0.103.11 from `ol8_developer_EPEL` repo on `Oracle Linux 8` does not detect encrypted RAR archives.
```
clamd --version
ClamAV 0.103.11/27088/Thu Nov  9 11:39:37 2023
```
```
clamconf -n

Software settings
-----------------
Version: 0.103.11
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON

Database information
--------------------
Database directory: /var/lib/clamav
bytecode.cvd: version 334, sigs: 91, built on Thu Feb 23 00:33:21 2023
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 15:32:42 2021
[3rd Party] Custom.ndb: 3 sigs
daily.cld: version 27096, sigs: 2046777, built on Fri Nov 17 11:39:57 2023
Total number of signatures: 8694298

Platform information
--------------------
uname: Linux 5.4.17-2136.323.8.2.el8uek.x86_64 #2 SMP Tue Sep 19 23:45:56 PDT 2023 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x0a2184840800000000080500

Build information
(omitted)
```

**Comment by micahsnyder** [comment]
@dmitrydonskih if you need this feature then I think you need to upgrade to a newer clamav release.  We provide pre-compiled RPM packages if you need, or else you can compile it yourself: https://docs.clamav.net/manual/Installing.html

Closing this stale ticket because original issue was not valid and no response regarding feature fixed in newer version.
