### ISSUE TITLE
Clamav 1.2.0 - clamconf result question

### ISSUE THREAD

**Issue by teoberi** [Cisco-Talos/clamav#1013]
Describe the bug
----------------
When I run the command
`./clamconf`
the result contains:

> Checking configuration files in /opt/clamav/etc
> Config file: clamd.conf
> ...
> MaxScanTime disabled
> !!! MaxScanSize: UNKNOWN INTERNAL TYPE !!!
> MaxFileSize = "104857600"
> ...

I specify that I have not modified the respective option in clamd.conf, it is default.

**Comment by teoberi** [comment]
The message appears in the **clamconf.c** file twice, lines 116 and 187, as a default option for switch instructions.
Isn't the case missing:
`case CLOPT_TYPE_SIZE64:`

**Comment by teoberi** [comment]
Maybe adding the missing case to the clamconf.c file would be the solution to solving the problem.
After line 103
`                case CLOPT_TYPE_SIZE:`
will be added
`                case CLOPT_TYPE_SIZE64:`
After line 171
`                case CLOPT_TYPE_SIZE:`
will be added
`                case CLOPT_TYPE_SIZE64:`
The printf message in line 172 will also be modified.

**Comment by rsundriyal** [comment]
Hi @teoberi, Thanks for sharing the issue. We have created a ticket to track the issue. Will update you on its fix.

**Comment by dohoangkhiem** [comment]
Hello, 

Any update on this? We have the config "MaxScanSize 500M" in our clamd.conf and running "clamconf -n" also gave us the error 

```
!!! MaxScanSize: UNKNOWN INTERNAL TYPE !!!
MaxFileSize = "209715200"
```

That makes us unsure that our config is really appied and effective, or due to that error clamd will revert to the default MaxScanSize (100M)?

**Comment by teoberi** [comment]
Have you tried the changes [here](https://github.com/Cisco-Talos/clamav/issues/1013#issuecomment-1700623971)?
It works for me.
