### ISSUE TITLE
ClamD fails silently if temporary folder does not exist

### ISSUE THREAD

**Issue by electrosonics** [Cisco-Talos/clamav#1028]
Describe the bug
----------------
ClamD fails silently if temporary folder does not exist
----------------

While testing the lastest version of ClamD with ClamDScan.exe, I was not getting any positive results for test files. ClamDscan reported that it took 0.005 second to scan a 20 megabyte file. I traced the issue to the ClamD.conf file TemporaryDirectory entry. It contained a typo. After I corrected the typo and restarted the ClamD service, the test file took a lot longer to scan and detections were now positive.

It would be nice if ClamDScan could verify that the TemporaryDirectory path is valid and report the error if it is not. This would have saved a lot of time debugging this issue.

How to reproduce the problem
----------------------------

To reproduce this error, edit the ClamD.conf file and change the TemporaryDirectory to an non-existent folder, restart the ClamD service and use ClamDScan to test a file with a known issue (or test a large file and note that the scan time in non-zero).

Config file: clamd.conf
-----------------------
LogFile = "C:\Program Files (x86)\[snip]\Antivirus\ClamAV\clamd.log"
LogFileUnlock = "yes"
LogTime = "yes"
LogVerbose = "yes"
ExtendedDetectionInfo = "yes"
TemporaryDirectory = "C:\Program Files (x86)\[snip]\Scratch"
DatabaseDirectory = "C:\Program Files (x86)\[snip]\Antivirus\ClamAV\db"
TCPSocket = "3310"
TCPAddr = "127.0.0.1"
MaxConnectionQueueLength = "30"
StreamMaxLength = "52428800"
MaxThreads = "100"
ReadTimeout = "60"
MaxQueue = "200"
IdleTimeout = "60"
SelfCheck = "1800"
ExitOnOOM = "yes"
Debug = "yes"

Config file: freshclam.conf
---------------------------
LogTime = "yes"
DatabaseDirectory = "C:\Program Files (x86)\[snip]\Antivirus\ClamAV\db"
UpdateLogFile = "C:\Program Files (x86)\[snip]\Antivirus\ClamAV\freshclam.log"
DatabaseMirror = "database.clamav.net"

clamav-milter.conf not found

Software settings
-----------------
Version: 1.2.0
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 JSON RAR

Database information
--------------------
Database directory: C:\Program Files (x86)\[snip]\Antivirus\ClamAV\db
bytecode.cvd: version 334, sigs: 91, built on Wed Feb 22 16:33:21 2023
daily.cld: version 27036, sigs: 2040930, built on Tue Sep 19 03:42:31 2023
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 08:32:42 2021
Total number of signatures: 8688448

Platform information
--------------------
uname: Microsoft Windows Server 6.2 SP0.0 Build 9200
OS: Windows, ARCH: AMD64, CPU: AMD64
zlib version: 1.2.13 (1.2.13), compile flags: 65
platform id: 0x1025bebe080000000000077c

Build information
-----------------
Microsoft Visual C++: (0.7.124)
sizeof(void*) = 8
Engine flevel: 190, dconf: 190

Here is the command line test results:

#
# scanning of large file using clamd with bad TemporaryDirectory
#
clamdscan.exe "BA04CB9FCCF9491CA54ADA2D216CBC52.MAI"
C:\[snip]\BA04CB9FCCF9491CA54ADA2D216CBC52.MAI: OK

----------- SCAN SUMMARY -----------
Infected files: 0
Time: 0.005 sec (0 m 0 s)
Start Date: 2023:09:19 16:06:30
End Date:   2023:09:19 16:06:30

#
# scanning of large file using clamd with fixed TemporaryDirectory
#
clamdscan.exe "BA04CB9FCCF9491CA54ADA2D216CBC52.MAI"
C:\[snip]\BA04CB9FCCF9491CA54ADA2D216CBC52.MAI: OK

----------- SCAN SUMMARY -----------
Infected files: 0
Time: 31.949 sec (0 m 31 s)
Start Date: 2023:09:19 16:07:13
End Date:   2023:09:19 16:07:45

#
# scanning email file using clamdscan that contains phising URL
#
clamdscan.exe DD3195FE049B474084043852DE96DC74.MAI
C:\[snip]\DD3195FE049B474084043852DE96DC74.MAI: OK

----------- SCAN SUMMARY -----------
Infected files: 0
Time: 0.006 sec (0 m 0 s)
Start Date: 2023:09:19 10:25:11
End Date:   2023:09:19 10:25:11

#
# scanning email file using clamscan that contains phising URL
#
clamscan.exe DD3195FE049B474084043852DE96DC74.MAI
Loading:    24s, ETA:   0s [========================>]    8.67M/8.67M sigs
Compiling:   5s, ETA:   0s [========================>]       41/41 tasks

LibClamAV info: Suspicious link found!
LibClamAV info:   Real URL:    http://url3637.quantumtechnology.net
LibClamAV info:   Display URL: ebay.com
C:\[snip]\DD3195FE049B474084043852DE96DC74.MAI: Heuristics.Phishing.Email.SpoofedDomain FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8672677
Engine version: 1.2.0
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 0.14 MB
Data read: 0.06 MB (ratio 2.19:1)
Time: 30.586 sec (0 m 30 s)
Start Date: 2023:09:19 10:25:47
End Date:   2023:09:19 10:26:18

#
# scanning email file using clamdscan that contains phising URL after fixing the TemporaryDirectory
#
clamdscan.exe DD3195FE049B474084043852DE96DC74.MAI
C:\[snip]\DD3195FE049B474084043852DE96DC74.MAI: Heuristics.Phishing.Email.SpoofedDomain FOUND

----------- SCAN SUMMARY -----------
Infected files: 1
Time: 0.069 sec (0 m 0 s)
Start Date: 2023:09:19 16:08:11
End Date:   2023:09:19 16:08:11
Attachments
-----------

None

**Comment by micahsnyder** [comment]
Thanks for the report.

> It would be nice if ClamDScan could verify that the TemporaryDirectory path is valid and report the error if it is not. This would have saved a lot of time debugging this issue.

It's possible that ClamDScan won't have access to ClamD's temporary directory if ClamD is running as a different user and using a private temp directory.  Instead, it may be best for ClamD to fail to start if the TemporaryDirectory is invalid. 

I should be a relatively simple change.  If anyone wants to contribute that would be nice.

**Comment by Kiggins26** [comment]
I am new to contributing to open source, could I take this on?

**Comment by micahsnyder** [comment]
@Kiggins26 certainly! We'd love the help.

**Comment by Kiggins26** [comment]
Awesome, Thank you

**Comment by micahsnyder** [comment]
Thanks @Kiggins26 I'll check it out

**Comment by Kiggins26** [comment]
@micahsnyder Thank you for taking a look, updated PR with your suggestions.

**Comment by Kiggins26** [comment]
@micahsnyder forgot to mention it was updated again

**Comment by micahsnyder** [comment]
Oh okay thanks.  Sorry about the delay.  I'll check it out.
