### ISSUE TITLE
Heuristics.Limits.Exceeded.MaxFileSize not emitted for 2GB+ files

### ISSUE THREAD

**Issue by fawind** [Cisco-Talos/clamav#1030]
Describe the bug
----------------

ClamAV is currently unable to scan files larger then 2GB (https://github.com/Cisco-Talos/clamav/issues/344#issuecomment-954236634).

Given that, I would expect ClamAV to emit the `Heuristics.Limits.Exceeded.MaxFileSize` warning when encountering a file larger then 2GB and configured with `--alert-exceeds-max=true`.

However, the MaxFileSize warning seems to be emitted based on the value configured through the `--max-filesize` option. I.e. when running with `--max-filesize=4000M`, ClamAV will not emit a MaxFileSize warning, even when encountering and skipping files larger then 2GB.

You can workaround this by setting `--max-filesize` to 2GB, which makes ClamAV emit warnings for 2GB+ files. However this is not obvious and very easy to misconfigure, resulting in files silently getting skipped without emitting the respective warning.

Ideally, ClamAV would always emit the MaxFileSize warning when it skips scanning bytes of files due to their size. Alternatively, it might also make sense to restrict the `--max-filesize` option to not allow setting values larger then 2GB or at least emit a warning if users misconfigure this.

How to reproduce the problem
----------------------------

Given `my-big-file` with size 2.5GB, the following command does not emit the MaxFileSize warning:

```bash
$ clamscan -d ./db --max-filesize=4000M --alert-exceeds-max=true my-big-file
Loading:     0s, ETA:   0s [========================>]        1/1 sigs
Compiling:   0s, ETA:   0s [========================>]       10/10 tasks

/tmp/clamav-limits/my-big-file: OK

----------- SCAN SUMMARY -----------
Known viruses: 1
Engine version: 1.2.0
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 0.00 MB
Data read: 2500.00 MB (ratio 0.00:1)
Time: 4.383 sec (0 m 4 s)
```

Note that a workaround is to set `--max-filesize` to 2GB, where the warning is emitted:

```bash
$ clamscan -d ./db --max-filesize=2048M --alert-exceeds-max=true my-big-file
Loading:     0s, ETA:   0s [========================>]        1/1 sigs
Compiling:   0s, ETA:   0s [========================>]       10/10 tasks

/tmp/clamav-limits/my-big-file: Heuristics.Limits.Exceeded.MaxFileSize FOUND

----------- SCAN SUMMARY -----------
Known viruses: 1
Engine version: 1.2.0
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 0.00 MB
Data read: 2500.00 MB (ratio 0.00:1)
Time: 0.002 sec (0 m 0 s)
```

**Comment by micahsnyder** [comment]
I reproduced this bug and see the issue in the code.  The heuristic signature is recorded, but not reported because of a loophole in the logic.  I drafted a fix yesterday and will put in a PR shortly

**Comment by fawind** [comment]
Thanks a lot for pushing this through 🎉
