### ISSUE TITLE
Docker "latest" image references 1.1.2 (at the moment)

### ISSUE THREAD

**Issue by bnutzer** [Cisco-Talos/clamav#1031]
Describe the bug
----------------

Today, the publicly available docker image "clamav/clamav:latest" is a reference to the 1.1.2 image, although 1.2.0 has been released weeks ago.

To me, it looks as if a *later* 1.1 release overwrote an already existing 1.2 "latest" tag.

How to reproduce the problem
----------------------------

```
$ docker run -it --rm clamav/clamav:latest clamd --version
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ClamAV 1.1.2/27020/Sun Sep  3 07:38:16 2023
```

**Comment by micahsnyder** [comment]
Thanks for reporting this. I'll track down what's going on in our automation.

**Comment by micahsnyder** [comment]
I confirmed the issue:
```
❯ docker pull clamav/clamav:latest
...
❯ docker pull clamav/clamav:latest_base
...

❯ docker run -it --rm clamav/clamav:latest clamd --version
ClamAV 1.1.2/27020/Sun Sep  3 07:38:16 2023

❯ docker run -it --rm clamav/clamav:latest_base clamd --version
ClamAV 1.1.2
```

The "IS_LATEST" default settings in the jenkinsfiles seem correct... 
1.2.0: https://github.com/Cisco-Talos/clamav-docker/blob/main/clamav/1.2/alpine/Jenkinsfile#L12
1.1.2: https://github.com/Cisco-Talos/clamav-docker/blob/main/clamav/1.1/alpine/Jenkinsfile#L12

I did notice it's not automatically updating the 1.2.0 image weekly as it should be.  But that doesn't explain why 1.1.2 was pushed as latest.  Will keep looking.

**Comment by rsundriyal** [comment]
@bnutzer @micahsnyder The issue is not with the code but with the Jenkins setup using the wrong parameters. I have fixed the issue and reran the pipeline to fix the images. 

@bnutzer Thanks for pointing out the issue. 

Please point out in case of any issues.
