### ISSUE TITLE
no solution to remove all those warnings in logs

### ISSUE THREAD

**Issue by novazur972** [Cisco-Talos/clamav#1068]
What should I do to no longer have the logs polluted by all these warnings?
```
WARNING: /var/spool/postfix/public/pickup: Not supported file type
WARNING: /var/spool/postfix/public/qmgr: Not supported file type
WARNING: /var/spool/postfix/public/postlog: Not supported file type
WARNING: /var/spool/postfix/public/flush: Not supported file type
WARNING: /var/spool/postfix/public/cleanup: Not supported file type
```
Already reported on the mailing list in 2019 (not me) but had not received a response. [](https://lists.clamav.net/pipermail/clamav-users/2019-March/007774.html)

My command line:
```
clamdscan -m -i --fdpass --log=/var/log/clamav/clamdscan.log /var /home /tmp /var/tmp
```

**Comment by ragusaa** [comment]
Hi,

Could you run with '-v' enabled in your clamdscan command and debug enabled in your clamd.conf ('Debug yes') and post the log?

Also, does '--quiet' get rid of them? 

Thanks,
Andy

**Comment by novazur972** [comment]
Are you sure adding -v and debug will remove all `WARNING: *** Not supported file type` ?

**Comment by ragusaa** [comment]
I don't think it will remove all the warnings, but looking at the logs will help us narrow down what types of files are causing these warnings.

**Comment by novazur972** [comment]
But we already know what type of file they are. That's sockets, only sockets.
And my question is : "How to remove thoses warnings". Not "how to correct to not have thoses warnings anymore" because I won't remove sockets from my FS, and I won't try to add all of them in clamd.conf to excluded them one by one.
I Juste want to know HOW to not get thoses warnings in my logs.

**Comment by micahsnyder** [comment]
@novazur972: Don't be rude. You're not paying for anything and we don't owe you anything.

@ragusaa already asked you to try with '--quiet' to see if that solves the problem for you.  

He was also hoping you could provide `--debug` output so we may understand the issue better.  In particular we've seen a bunch of complaints about `cli_realpath` warnings (sometimes with clamonacc but not clamdscan, etc) and are unsure what is causing the problem.  More information is better. 

Furthermore you failed to put in the output of `clamconf -n` as was requested by the github issue template.  So we don't even know which version of ClamAV you're using. 

Personally I can't remember ever seeing the `"cli_realpath: Invalid arguments."` warning before and that's pretty concerning to me.  So debug logs may really help.

**Comment by novazur972** [comment]
There is what you want, and there is what I want. If your desire is to fulfill your wishes, you don't need me, my requests, and my logs.
I ask one question, and you decide to answer another.
A WARNING is a WARNING. It should never be imposed on anyone who does not wish to see it. If your system does not allow you to hide it, it is either not a WARNING but an ERROR, or it is poorly done. Either way, the problem is not me, but your system.

Let's not talk about it anymore, I will be able to remove these warnings on my own.
And for your information, my version of clamav is 1.2.0.
