### ISSUE TITLE
Freshclam-ClamAV - Database Download - blocked by CDN

### ISSUE THREAD

**Issue by dr-batisa** [Cisco-Talos/clamav#1073]
Got an error:
Freshclam-ClamAV - Database Download - blocked by CDN

freshclam
ClamAV update process started at Tue Oct 24 19:30:24 2023
daily database available for update (local version: 27017, remote version: 27071)
Current database is 54 versions behind.
Downloading database patch # 27018...
WARNING: downloadPatch: Can't download daily-27018.cdiff from https://database.clamav.net/daily-27018.cdiff
WARNING: Incremental update failed, trying to download daily.cvd
WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
WARNING: FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
This could mean several things:
 1. You are running an out-of-date version of ClamAV / FreshClam.
    Ensure you are the most updated version by visiting https://www.clamav.net/downloads
 2. Your network is explicitly denied by the FreshClam CDN.
    In order to rectify this please check that you are:
   a. Running an up-to-date version of FreshClam
   b. Running FreshClam no more than once an hour
   c. If you have checked (a) and (b), please open a ticket at
      https://github.com/Cisco-Talos/clamav/issues
      and we will investigate why your network is blocked.
WARNING: You are on cool-down until after: 2023-10-25 19:30:27
ERROR: Database update process failed: Forbidden; Blocked by CDN
ERROR: Update failed.

I have company in EU, Cyprus that rent server with IP address 94.241.172.73 in Europe thru Dubai hosting company. Why is that?

**Comment by micahsnyder** [comment]
@dr-batisa I don't believe your IP should be blocked for any geographical / sanction type of reason.

If you can gather the `cf-ray` ID from freshclam verbose log output it will help when I ask an admin to look up in the logs to see what is going wrong.

To get that `cf-ray` ID, first remove the `freshclam.dat` file from your database directory (probably in `/var/lib/clamav/freshclam.dat` or `/usr/local/share/clamav/freshclam.dat`).

Then try running freshclam with the `--verbose` option.

From the verbose log where you see the 403 HTTP response from the server, please grab the `cf-ray` ID.  It will look something like this
```
< server: cloudflare
< cf-ray: 81b3b1069af6f957-SJC
```

**Comment by micahsnyder** [comment]
@dr-batisa nevermind, we don't need the `cf-ray` ID after all.  We figured out what happened.  You should be unblocked now.

**Comment by karascho** [comment]
Hi, 
if someone read this:
Howto get in contact. I've been blocked. No access to Cloudflare too.

Cant start clamav + freshclam:
FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).
Database update process failed: Forbidden; Blocked by CDN
ERROR: Update failed
heidernein@gmail.com

**Comment by micahsnyder** [comment]
@karascho You can also reach out via:
1. our [ClamAV Discord chat server](https://discord.gg/6vNAqWnVgw).
2. the [clamav-users mailing list](https://lists.clamav.net/mailman/listinfo/clamav-users).

We have geolocation rules to [block IP addresses within sanctioned countries (notably Russia)](https://github.com/Cisco-Talos/clamav/issues/500). It's possible you're being blocked for that reason. Please follow [the instructions I provided above](https://github.com/Cisco-Talos/clamav/issues/1073#issuecomment-1777635343) to get the `cf-ray` id and we can look for it in our logs.

It's also possible that Cloudflare themselves are blocking you, in which case we won't have any record in our logs. 🤞
