### ISSUE TITLE
ClamAV 1.2.1 on macOS Sonoma 14.1, freshclam aborts.

### ISSUE THREAD

**Issue by suishouen** [Cisco-Talos/clamav#1075]
I've built ClamAV 1.2.0 from source as follows: 
https://www.gctv.ne.jp/~yokota/clamav/cmake/#mem9a
And I'm running ClamAV 1.2.0 without any problems on Sonoma 14.1.

But when I tried to build ClamAV 1.2.1 and run freshclam, I got an error as below:

freshclam
dyld[27450]: Library not loaded: @rpath/libjson-c.5.dylib
  Referenced by: <E138F212-3187-38CF-BBAE-058DC9E361D2> /usr/local/clamXav/bin/freshclam
  Reason: Attempted to use: '/usr/local/clamXav/lib/libjson-c.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/clamXav/lib/libjson-c.5.dylib' (no such file), '/usr/local/clamXav/lib/libjson-c.5. .dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/clamXav/lib/libjson-c.5.dylib' (no such file), (security policy does not allow @ path expansion)
Abort trap: 6

**Comment by micahsnyder** [comment]
@suishouen Did you do this step?
```
sudo ln -s /usr/local/json-c/lib/libjson-c.5.dylib /usr/local/lib/
```

If so, does `/usr/local/json-c/lib/libjson-c.5.dylib` actually exist?

I will note, this github issue tracker is for bugs in clamav.  The instructions you linked are unofficial.  Our instructions for building on mac use Homebrew though, which may not be an option for you.  If they are, our docs are here: https://docs.clamav.net/manual/Installing/Installing-from-source-Unix.html#macos

If you're interested in something pre-compiled, we also provide a `.pkg` installer for macOS that will work on Intel and Apple ARM Macs.  You can get it from clamav.net/downloads  and instructions for that is here https://docs.clamav.net/manual/Installing.html#macos

**Comment by suishouen** [comment]
@_micahsnyder
Thanks for your quick support.

Yes, I installed json-c as follows:
https://www.gctv.ne.jp/~yokota/clamav/cmake/#mem7

So `/usr/local/json-c/lib/libjson-c.5.dylib` and `/usr/local/lib/libjson-c.5.dylib` exist.

**Comment by suishouen** [comment]
Making symlinks to '/usr/local/clamXav/lib' seems to fix this problem.
`sudo ln -s /usr/local/json-c/lib/libjson-c.5.dylib /usr/local/clamXav/lib/`

I notes https://www.gctv.ne.jp/~yokota/clamav/cmake/#mem0.

Thanks for your support again.
Please close #1075.

**Comment by micahsnyder** [comment]
Oh good to hear! Take care.
