### ISSUE TITLE
EICAR text is ignored in crt files

### ISSUE THREAD

**Issue by marijusGood** [Cisco-Talos/clamav#1088]
Describe the bug
----------------

When I have a .ctr file that contains only the EICAR text then clamav detects it and is all fine, but if I put the EICAR text between -----BEGIN CERTIFICATE----- and -----END CERTIFICATE----- then it shows that the file has no problems.

How to reproduce the problem
----------------------------

1. Create .crt file that contains only the EICAR text
2. run clamscan on it
3. create .crt file that looks like so:
-----BEGIN CERTIFICATE-----
EICAR text
-----END CERTIFICATE-----
4. run clamscan on it

you will see that it will output OK

Attachments
-----------

Don't want to trigger GitHub antivirus, but how to create the file is specified

**Comment by micahsnyder** [comment]
This is not how the EICAR test file is supposed to be used.  It's not a special string that should be detected in any file.  It is a file that should be detected if it can be extracted from another file such as a Zip, a Doc attachment, an email attachment, etc.  A `.crt` file is not an archive.  No AV should detect the EICAR text just jammed in the middle of other file.  Plenty of them do detect this kind of thing, but ClamAV does not.  We're very strict about it. 

Here's the definition of EICAR from https://www.eicar.org/download-anti-malware-testfile/

> THE ANTI-MALWARE TESTFILE
> 
> It is also short and simple – in fact, it consists entirely of printable ASCII characters, so that it can easily be created with a regular text editor. Any anti-virus product that supports the EICAR test file should detect it in any file providing that the file starts with the following 68 characters, and is exactly 68 bytes long:
> 
> `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`
> The first 68 characters is the known string. It may be optionally appended by any combination of whitespace characters with the total file length not exceeding 128 characters. The only whitespace characters allowed are the space character, tab, LF, CR, CTRL-Z. To keep things simple the file uses only upper case letters, digits and punctuation marks, and does not include spaces. The only thing to watch out for when typing in the test file is that the third character is the capital letter “O”, not the digit zero.
> 
> This test file has been provided to EICAR for distribution as the “EICAR Standard Anti-Virus Test File”, and it satisfies all the criteria listed above. It is safe to pass around, because it is not a virus, and does not include any fragments of viral code. Most products react to it as if it were a virus (though they typically report it with an obvious name, such as “EICAR-AV-Test”).
> 
> The file is a legitimate DOS program, and produces sensible results when run (IT PRINTS THE MESSAGE “EICAR-STANDARD-ANTIVIRUS-TEST-FILE!”).
