### ISSUE TITLE
python 3.12 installer gets reported as a false positive

### ISSUE THREAD

**Issue by brokedarius** [Cisco-Talos/clamav#1089]
They say an image is worth a 1000 words..

![2023-11-17_11-10](https://github.com/Cisco-Talos/clamav/assets/95202445/98939210-476d-4f5d-87e7-5f376e5050b1)

**Comment by micahsnyder** [comment]
@brokedarius thanks for sharing. We have a malware and false positive-reporting portals for signature issues.  If you could please submit the report to https://www.clamav.net/reports/fp that will be helpful.  I've also shared it with our threat research team via chat message so they're aware. 

Regards,
Micah
