### ISSUE TITLE
ClamAV daily cvd for November 18th 2023 seems corrupted

### ISSUE THREAD

**Issue by dgonzalez** [Cisco-Talos/clamav#1094]
Describe the bug
----------------

We have automatically downloaded daily.cvd from ClamAV and our Clam instance detected it as corrupted. We have also downloaded it manually in order to rule out network issues and same result.

How to reproduce the problem
----------------------------

Download the daily.cvd file from ClamAV (http://database.clamav.net/daily.cvd) and use it in a ClamAV running clamd server. Should detect it as corrupted.

**Comment by dgonzalez** [comment]
This seems to have been resolved in today's file (November 19th).

**Comment by HydraDragonAntivirus** [comment]
Now 22.04.2024 is looks corrupted.
