### ISSUE TITLE
clamav都支持那些类型的病毒检测

### ISSUE THREAD

**Issue by LiujD0** [Cisco-Talos/clamav#1098]
Describe the bug
----------------

Replace this text with a clear and concise description of the bug or feature request.

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by teoberi** [comment]
?

**Comment by micahsnyder** [comment]
![image](https://github.com/Cisco-Talos/clamav/assets/30635813/0617c7fa-6b61-4f67-b435-29dc0e80b855)

@LiujD0 Your question is too general. I don't know how to answer it. Maybe this documentation will help: https://docs.clamav.net/#features

你的问题太笼统了。我不知道该怎么回答。也许这个文档会有所帮助：https://docs.clamav.net/#features

**Comment by LiujD0** [comment]
ClamAV 可检测数百万种病毒、蠕虫、木马和其他恶意软件，包括 Microsoft Office 宏病毒、移动恶意软件和其他威胁。
我想问的就上面这段描述里面所提到的各种病毒和攻击的详细信息
