### ISSUE TITLE
Python Interpreter Has Win.Virus.Expiro-10014083-0 False Positive?

### ISSUE THREAD

**Issue by clsvar** [Cisco-Talos/clamav#1106]
Describe the bug
----------------

The official Python interpreter is positive of Win.Virus.Expiro-10014083-0 malware using VirusTotal
![Screenshot 2023-12-04 094146 virustotal python](https://github.com/Cisco-Talos/clamav/assets/41988018/2d507f5b-4682-47fb-a5ce-8876d0c22b29)
. Is this a false positive?

How to reproduce the problem
----------------------------

Download the exe file from https://www.python.org/downloads/ Python version 3.11.6 amd64 is tested to be infected.

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by argosopentech** [comment]
I also see these files being flagged by Clamav
```
env/lib/python3.10/site-packages/pip/_vendor/distlib/w32.exe
env/lib/python3.10/site-packages/pip/_vendor/distlib/t64-arm.exe
env/lib/python3.10/site-packages/pip/_vendor/distlib/w64-arm.exe

Win.Virus.Expiro-10022939-0
```
