### ISSUE TITLE
pdf decoding issue

### ISSUE THREAD

**Issue by Sanesecurity** [Cisco-Talos/clamav#1109]
Describe the bug
----------------

received lots of pdf spam with a naked lady in it and inside the pdf is an embedded link to click on, which points to:

h t t p s: / /dating2 dot xloveme dot me/?cid=

engine doesn't seem to extract the above url or decode properly (even with --leave-temps),
so can't really create a useful sig to block the link.

Attachments
-----------

Added attachment example pdf.
[xxx spam.pdf](https://github.com/Cisco-Talos/clamav/files/13613883/xxx.spam.pdf)

**Comment by micahsnyder** [comment]
Going to close this as fixed, since it's working in main. The fix will be available in 1.3.0.  The release candidate should be out next week-ish, and stable release out in early January.
