### ISSUE TITLE
Got an error: Freshclam-ClamAV - Database Download - blocked by CDN

### ISSUE THREAD

**Issue by github-xalqretail** [Cisco-Talos/clamav#1119]
Freshclam My IP is 95.47.238.178, Company Xalqretail Uzbekistan.

Mon Dec 18 00:08:59 2023 -> ClamAV update process started at Mon Dec 18 00:08:59 2023
WARNING: Mon Dec 18 00:08:59 2023 -> Cool-down expired, ok to try again.
Mon Dec 18 00:08:59 2023 -> daily database available for download (remote version: 27126)
WARNING: Mon Dec 18 00:09:00 2023 -> Can't download daily.cvd from https://database.clamav.net/daily.cvd
WARNING: Mon Dec 18 00:09:00 2023 -> FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
Mon Dec 18 00:09:00 2023 -> This could mean several things:
Mon Dec 18 00:09:00 2023 ->  1. You are running an out-of-date version of ClamAV / FreshClam.
Mon Dec 18 00:09:00 2023 ->     Ensure you are the most updated version by visiting https://www.clamav.net/downloads
Mon Dec 18 00:09:00 2023 ->  2. Your network is explicitly denied by the FreshClam CDN.
Mon Dec 18 00:09:00 2023 ->     In order to rectify this please check that you are:
Mon Dec 18 00:09:00 2023 ->    a. Running an up-to-date version of FreshClam
Mon Dec 18 00:09:00 2023 ->    b. Running FreshClam no more than once an hour
Mon Dec 18 00:09:00 2023 ->    c. If you have checked (a) and (b), please open a ticket at
Mon Dec 18 00:09:00 2023 ->       https://github.com/Cisco-Talos/clamav/issues
Mon Dec 18 00:09:00 2023 ->       and we will investigate why your network is blocked.
WARNING: Mon Dec 18 00:09:00 2023 -> You are on cool-down until after: 2023-12-19 00:09:00
ERROR: Mon Dec 18 00:09:00 2023 -> Database update process failed: Forbidden; Blocked by CDN
ERROR: Mon Dec 18 00:09:00 2023 -> Update failed.

**Comment by brebell** [comment]
Thank you fore reaching out.
We took a look at your IP which we can see is for a company in Uzbekistan.
We use maxmind for the IP geolocation and it thinks the IP is from Russia, as such we are required to block.
For more details please look here: https://github.com/Cisco-Talos/clamav/issues/500

Another user reported a similar issue and suggested using https://packages.microsoft.com/clamav/ as a way to resolve a similar issue they had.

**Comment by github-xalqretail** [comment]
Ok thank u. Our ISP in datacenter had IP reputation's problem (Cisco talos had poor status). But they resolved it.
