### ISSUE TITLE
clamd is taking forever to complete SCAN

### ISSUE THREAD

**Issue by sunil-saini** [Cisco-Talos/clamav#1129]
We are using clamd in combination with [clamsmtp](http://thewalter.net/stef/software/clamsmtp/) to scan emails in postfix as [after queue filter](https://www.postfix.org/FILTER_README.html)

Our clamd configuration is [clamd.conf.txt](https://github.com/Cisco-Talos/clamav/files/13819709/clamd.conf.txt)

Clamsmtp writes mail to temporary path and then connects to clamd on local Unix Socket to get the SCAN verdict by running `SCAN <path>` command

There is [TimeOut](https://linux.die.net/man/5/clamsmtpd.conf) configuration in clamsmtp (default 180 secs), so it waits for 180 secs for SCAN to complete, but sometimes for some emails its timing out but still SCAN keeps on running in clamd for very long

<img width="1439" alt="Screenshot 2024-01-03 at 6 17 33 PM" src="https://github.com/Cisco-Talos/clamav/assets/34716971/af120034-9a85-4946-a162-8133eabe095f">

In Screenshot as can see, oldest SCAN been running from **4682** secs

Since timeout in clamsmtp is 180 secs, so after time out, mail gets deferred in postfix and retried after some time, again same thing happens and new SCAN keeps on running with older SCAN, as can see in screenshot, 3 SCANS were running from long time, we verified that are of same email only

To the surprise this mail size is approx 240 KB only ( 178 KB of attachment with **.dat** extension )

So thought there might be problem with our current **clamd version 0.103.8** so upgraded it to latest available version **0.103.9**  but still behaviour was same

We are using Amazon Linux 2 OS and here latest available version is **0.103.9** only, tried installing directly from [rpm](https://www.clamav.net/downloads/production/clamav-1.2.1.linux.x86_64.rpm) but it is also failing
```
[root@postfix-in tmp]# rpm -ivh clamav-1.2.1.linux.x86_64.rpm
error: Failed dependencies:
	clamav > 0.103.8-1.amzn2.0.2 conflicts with (installed) clamav-filesystem-0.103.8-1.amzn2.0.2.noarch
[root@postfix-in tmp]#
[root@postfix-in tmp]# rpm -qa | grep clam
clamav-update-0.103.8-1.amzn2.0.2.x86_64
clamav-filesystem-0.103.8-1.amzn2.0.2.noarch
clamsmtp-1.10-14.el7.x86_64
clamav-lib-0.103.8-1.amzn2.0.2.x86_64
clamav-0.103.8-1.amzn2.0.2.x86_64
clamd-0.103.8-1.amzn2.0.2.x86_64
[root@postfix-in tmp]#
[root@postfix-in tmp]# yum list clamd --show-duplicates
Installed Packages
clamd.x86_64                                                                                 0.103.8-1.amzn2.0.2                                                                                 @amzn2-core
Available Packages
clamd.x86_64                                                                                 0.103.6-1.amzn2.0.1                                                                                 amzn2-core
clamd.x86_64                                                                                 0.103.7-1.amzn2.0.1                                                                                 amzn2-core
clamd.x86_64                                                                                 0.103.8-1.amzn2.0.1                                                                                 amzn2-core
clamd.x86_64                                                                                 0.103.8-1.amzn2.0.2                                                                                 amzn2-core
clamd.x86_64                                                                                 0.103.9-1.amzn2.0.2                                                                                 amzn2-core
[root@postfix-in tmp]#
```

Expected behaviour :

1. SCAN should complete in some limited time, currently there doesn't seems to be any parameter in [configuration](https://linux.die.net/man/5/clamd.conf) to control timeout of SCAN and stop the SCAN
2. Once socket is closed from client, clamd SCAN should also stop OR there should be some way to stop this running SCAN other than restart of clamd process itself
3. Why for such small file, its taking so long (we are running 4 Core & 8 GB machine), is it due to **.dat** file ?

**Comment by micahsnyder** [comment]
It is unfortunate that 0.103.9 is the newest version available to you.  There have since been improvements in 1.0, 1.1, and 1.2 which may properly terminate a long scan.

1. The manpage you're using appears to be dated. We do have a newer feature `MaxScanTime`, which is set in milliseconds, to abort scans that take too long: https://github.com/Cisco-Talos/clamav/blob/main/etc/clamd.conf.sample#L528-L536
2. I agree it would be good if clamd canceled a scan when the socket closes.  Unfortunately this is not possible at this time.
3. I am also worried about why a small file scan would take this long.  If you could send me an encrypted zip containing the file and give me the password, my email address is micasnyd [ at ] cisco.com.  Or you could send it to me through Discord. https://docs.clamav.net/#chat

**Comment by sunil-saini** [comment]
@micahsnyder 

We have upgraded clamav to latest version v1.2.1 and since then its working well

about the option **MaxScanTime** in configuration mentioned that 

> In this version, this field only affects the scan time of ZIP archives

So what about about other file types,  SCAN will keep running till completion ?

**Comment by micahsnyder** [comment]
@sunil-saini 

> @micahsnyder
> 
> We have upgraded clamav to latest version v1.2.1 and since then its working well
> 
> about the option **MaxScanTime** in configuration mentioned that

Glad to hear your issue was resolve dwith the upgrade to 1.2.1

> > In this version, this field only affects the scan time of ZIP archives
> 
> So what about about other file types, SCAN will keep running till completion ?

We should remove this comment from `clamd.conf.sample`.  We've since added scan-time checks in many locations and the scan timeout should be enforced for the most part.

**Comment by micahsnyder** [comment]
@kw-create if you're running into issues with signature load, then you likely do not have enough RAM on your system (or container).  I think you will need at least 3GB of RAM, though I recommend 6GB or more.  Since your issue seems unrelated and the OP's issue is resolved, I am closing this ticket.
