### ISSUE TITLE
Debian based docker image is missing libncurses6

### ISSUE THREAD

**Issue by jbender81** [Cisco-Talos/clamav#1131]
Describe the bug
----------------

When using the Debian based docker image clamdtop won't start due to libncurses6 being missing:

How to reproduce the problem
----------------------------
1. Start a debian based clamav container.
2. Try to start clamdtop within that container. Either by using a container intern shell or directly via docker exec

Attachments
-----------

>>>>
sudo docker exec -it b7101bd84c93 clamdtop
clamdtop: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
>>>>

Workaround
----------
sudo docker exec -it b7101bd84c93 apt update
[...]
sudo docker exec -it b7101bd84c93 apt install -y libncurses6
[...]
sudo docker exec -it b7101bd84c93 clamdtop
        __                    ____
  _____/ /___ _____ ___  ____/ / /_____  ____
 / ___/ / __ `/ __ `__ \/ __  / __/ __ \/ __ \
/ /__/ / /_/ / / / / / / /_/ / /_/ /_/ / /_/ /
\___/_/\__,_/_/ /_/ /_/\__,_/\__/\____/ .___/
                                     /_/
Connecting to: /tmp/clamd.sock

**Comment by micahsnyder** [comment]
I was able to reproduce this issue:
```
root@bb7f6fee2f95:/# clamdtop
clamdtop: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory


root@bb7f6fee2f95:/# apt update && apt install libncurses6
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  libncurses6
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 102 kB of archives.
After this operation, 343 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 libncurses6 amd64 6.2+20201114-2+deb11u2 [102 kB]
Fetched 102 kB in 0s (1026 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libncurses6:amd64.
(Reading database ... 7198 files and directories currently installed.)
Preparing to unpack .../libncurses6_6.2+20201114-2+deb11u2_amd64.deb ...
Unpacking libncurses6:amd64 (6.2+20201114-2+deb11u2) ...
Setting up libncurses6:amd64 (6.2+20201114-2+deb11u2) ...
Processing triggers for libc-bin (2.31-13+deb11u7) ...
root@bb7f6fee2f95:/# clamdtop
        __                    ____
  _____/ /___ _____ ___  ____/ / /_____  ____
 / ___/ / __ `/ __ `__ \/ __  / __/ __ \/ __ \
/ /__/ / /_/ / / / / / / /_/ / /_/ /_/ / /_/ /
\___/_/\__,_/_/ /_/ /_/\__,_/\__/\____/ .___/
                                     /_/
Connecting to: /tmp/clamd.sock
...
```

Very odd, since we compile it with `libncurses5-dev` and install `libncurses5` in the final image.  I imagine one of the other build dependencies brought along ncurses6.  We don't explicitly tell clamav which library to link against so I suppose it found and built with version 6.  Should be simple enough to switch up 5 to 6.
