### ISSUE TITLE
If logging to syslog is enabled, all logs entries are generated with severity WARNING instead of the appropriate severity

### ISSUE THREAD

**Issue by nagmat84** [Cisco-Talos/clamav#1134]
If logging to Syslog is enabled, each program (`freshclam`, `clamscan`, `clamdscan`) logs every message with severity WARNING instead of an appropriate severity level.

For example, when freshclam successfully (!) updates the virus definition database the message "`******* RESULT 200, SIZE: <size of virus definitions> *******`" is logged as a WARNING even if at most NOTICE would be appropriate.

This is particularly annoying for messages which are actually "good" messages (such as a report about a successful DB update), as WARNING is the first level which indicates an _abnormal_ situation. Hence, it should not misused for success messages.

A little bit less annoying, but still not good, is reporting actual errors (like a corrupted DB definition database) only as a WARNING even if ERROR or CRITICAL would be more appropriate.

Unconditionally using the same log severity for everything complicates automated log monitoring. 

How to reproduce the problem
----------------------------

Enable logging to Syslog via `LogSyslog yes` in `/etc/clamav/{clamav-milter,clamd|freshclam}.conf` and observe logs.

**Comment by micahsnyder** [comment]
> For example, when freshclam successfully (!) updates the virus definition database the message "`******* RESULT 200, SIZE: <size of virus definitions> *******`" is logged as a WARNING even if at most NOTICE would be appropriate.

This specific error message was hardcoded to a warning level, as it was unintentionally included when testing a fix and should not be printed, ever. 

It was fixed in 1.2.0, 1.1.1, and 1.0.4. See https://github.com/Cisco-Talos/clamav/pull/935

**Comment by nagmat84** [comment]
Good to know. Unfortunately, version [1.1.0 is the latest stable version on Gentoo Linux](https://packages.gentoo.org/packages/app-antivirus/clamav) which I use. I will try to upgrade to unstable 1.2.1 and see what happens.
