### ISSUE TITLE
clamav on debian oldstable outdated

### ISSUE THREAD

**Issue by tillewolle** [Cisco-Talos/clamav#1170]
Describe the bug
----------------

package: clamav
Version: 0.103.10+dfsg-0+deb11u1

The daily logs tell that clamav installation is outdated. I suggest to bump the oldstable version to a current version like 0.103.11 which is suggested in the error message or even higher.

 
 Your ClamAV installation is OUTDATED!
 Local version: 0.103.10 Recommended version: 0.103.11

**Comment by Kangie** [comment]
This seems like an issue that you'll need to take up with your distribution packagers. Please raise a bug with Debian.

https://tracker.debian.org/pkg/clamav

**Comment by micahsnyder** [comment]
Closing this because it is a third party package.
