### ISSUE TITLE
Blocked by CDN when trying to download latest database #1123

### ISSUE THREAD

**Issue by Savitckiy** [Cisco-Talos/clamav#1181]
Hi!
When I try to run freshclam it fails and tells me im blocked by the CDN. 

Thu Feb 22 10:59:54 2024 -> ClamAV update process started at Thu Feb 22 10:59:54 2024
Thu Feb 22 10:59:54 2024 -> daily database available for download (remote version: 27192)
WARNING: Thu Feb 22 10:59:55 2024 -> Can't download daily.cvd from https://database.clamav.net/daily.cvd
WARNING: Thu Feb 22 10:59:55 2024 -> FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
Thu Feb 22 10:59:55 2024 -> This could mean several things:
Thu Feb 22 10:59:55 2024 ->  1. You are running an out-of-date version of ClamAV / FreshClam.
Thu Feb 22 10:59:55 2024 ->     Ensure you are the most updated version by visiting https://www.clamav.net/downloads
Thu Feb 22 10:59:55 2024 ->  2. Your network is explicitly denied by the FreshClam CDN.
Thu Feb 22 10:59:55 2024 ->     In order to rectify this please check that you are:
Thu Feb 22 10:59:55 2024 ->    a. Running an up-to-date version of FreshClam
Thu Feb 22 10:59:55 2024 ->    b. Running FreshClam no more than once an hour
Thu Feb 22 10:59:55 2024 ->    c. If you have checked (a) and (b), please open a ticket at
Thu Feb 22 10:59:55 2024 ->       https://github.com/Cisco-Talos/clamav/issues
Thu Feb 22 10:59:55 2024 ->       and we will investigate why your network is blocked.
WARNING: Thu Feb 22 10:59:55 2024 -> You are on cool-down until after: 2024-02-23 10:59:55
ERROR: Thu Feb 22 10:59:55 2024 -> Database update process failed: Forbidden; Blocked by CDN
ERROR: Thu Feb 22 10:59:55 2024 -> Update failed.

~]$ rpm -qa clamav
clamav-1.0.5-1.x86_64

IP: 151.236.118.3
Location: Frankfurt

**Comment by ragusaa** [comment]
Could you paste the output of  'freshclam --verbose'. That'll give us the CF-Ray ID, which makes it easier to find in the our logs.

**Comment by mohamedabz** [comment]
Hello,
I am on a windows machine
Best regards,

**Comment by ragusaa** [comment]
The verbose option also works on windows.

**Comment by ragusaa** [comment]
In order to get the cf-ray, you may need to create a different DatabaseDirectory that doesn't have a freshclam.dat file (or rename it)

**Comment by Savitckiy** [comment]
freshclam --verbose

Fri Feb 23 11:08:52 2024 -> Current working dir is /usr/local/share/clamav/
Fri Feb 23 11:08:52 2024 -> Loaded freshclam.dat:
Fri Feb 23 11:08:52 2024 ->   version:    1
Fri Feb 23 11:08:52 2024 ->   uuid:       42790417-43c1-4087-842a-b0ed1283b006
Fri Feb 23 11:08:52 2024 ->   retry-after: 2024-02-23 12:58:22
Fri Feb 23 11:08:52 2024 -> ClamAV update process started at Fri Feb 23 11:08:52 2024
Fri Feb 23 11:08:52 2024 -> Current working dir is /usr/local/share/clamav/
Fri Feb 23 11:08:52 2024 -> Querying current.cvd.clamav.net
Fri Feb 23 11:08:53 2024 -> TTL: 1800
Fri Feb 23 11:08:53 2024 -> fc_dns_query_update_info: Software version from DNS: 0.103.11
WARNING: Fri Feb 23 11:08:53 2024 -> FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).
Fri Feb 23 11:08:53 2024 -> This means that you have been rate limited or blocked by the CDN.
Fri Feb 23 11:08:53 2024 ->  1. Verify that you're running a supported ClamAV version.
Fri Feb 23 11:08:53 2024 ->     See https://docs.clamav.net/faq/faq-eol.html for details.
Fri Feb 23 11:08:53 2024 ->  2. Run FreshClam no more than once an hour to check for updates.
Fri Feb 23 11:08:53 2024 ->     FreshClam should check DNS first to see if an update is needed.
Fri Feb 23 11:08:53 2024 ->  3. If you have more than 10 hosts on your network attempting to download,
Fri Feb 23 11:08:53 2024 ->     it is recommended that you set up a private mirror on your network using
Fri Feb 23 11:08:53 2024 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Fri Feb 23 11:08:53 2024 ->     CDN and your own network.
Fri Feb 23 11:08:53 2024 ->  4. Please do not open a ticket asking for an exemption from the rate limit,
Fri Feb 23 11:08:53 2024 ->     it will not be granted.
WARNING: Fri Feb 23 11:08:53 2024 -> You are still on cool-down until after: 2024-02-23 12:58:22

**Comment by mohamedabz** [comment]
Hello,
I do not think this is a temporary rate limit blocking is the cause of the
issue! As even trying to access your website from my windows server is not
allowed, it was never allowed! Even after (You are still on cool-down until
after: 2024-02-23 12:58:22) I will not be able to access your website,
seems that IP address is blocked from your side for certain reasons even
before I started using ClamAV.
Best regards,

**Comment by ragusaa** [comment]
At this point, I think you are right.  We checked the logs, and your IP doesn't appear to have triggered any firewall events in the last 72 hours, but it can be harder to track down by IP in our system.  

If you could move your freshclam.dat file out of your signature database directory, and re-run freshclam --verbose, that would be helpful.  The line we need looks like 
"< cf-ray: 85a0b2585a8772b9-EWR"

Thanks, 
Andy

**Comment by Savitckiy** [comment]
* old SSL session ID is stale, removing
< HTTP/2 403 
< date: Fri, 23 Feb 2024 21:21:59 GMT
< content-type: text/html; charset=UTF-8
< x-frame-options: SAMEORIGIN
< referrer-policy: same-origin
< cache-control: max-age=15
< expires: Fri, 23 Feb 2024 21:22:14 GMT
< set-cookie: __cf_bm=1n58O8sTgjpVB6Zuf.zh_MkA9uFC0ohVDoph8smoH48-1708723319-1.0-AbLFT5j8yGAHHVleFe1ejm530teycZysqQTWGNrCe3XFakJRSqJl6o0XZJUc9/7KWKoVUP/aj5VzAGgjbKuxgOE=; path=/; expires=Fri, 23-Feb-24 21:51:59 GMT; domain=.clamav.net; HttpOnly; Secure; SameSite=None
< strict-transport-security: max-age=15552000
< x-content-type-options: nosniff
< server: cloudflare
**< cf-ray: 85a285896fea671c-AMS**
<

**Comment by ragusaa** [comment]
The logs are saying that you are blocked because of having a Russian IP.  If that's the case, there is really nothing more we can do.  

https://github.com/Cisco-Talos/clamav/issues/500

Thanks,
Andy

**Comment by Savitckiy** [comment]
OK!
Thanks you for the time spent!

**Comment by ragusaa** [comment]
Sorry I couldn't be more help.
