### ISSUE TITLE
freshclam fails since 2/28 to today with weird error

### ISSUE THREAD

**Issue by DGPickett** [Cisco-Talos/clamav#1191]
freshclam is failing last few nights:

Tue Feb 27 19:00:01 2024 -> ClamAV update process started at Tue Feb 27 19:00:01
 2024
Tue Feb 27 19:00:01 2024 -> daily database available for update (local version: 
27197, remote version: 27198)
Tue Feb 27 19:00:03 2024 -> Testing database: '/home/dgp/.clamtk/db/tmp.7f477dee
3d/clamav-a38d8a74262f9a0096008352a0fb1101.tmp-daily.cld' ...
Tue Feb 27 19:00:16 2024 -> Database test passed.
Tue Feb 27 19:00:17 2024 -> daily.cld updated (version: 27198, sigs: 2054038, f-
level: 90, builder: raynman)
Tue Feb 27 19:00:17 2024 -> main.cld database is up-to-date (version: 62, sigs: 
6647427, f-level: 90, builder: sigmgr)
Tue Feb 27 19:00:17 2024 -> bytecode database available for update (local versio
n: 334, remote version: 335)
Tue Feb 27 19:00:17 2024 -> WARNING: [LibClamAV] No DB open for action UNLINK on
 line 8
Tue Feb 27 19:00:17 2024 -> ERROR: downloadPatch: Can't apply patch
Tue Feb 27 19:00:17 2024 -> The database server doesn't have the latest patch fo
r the bytecode database (version 335). The server will likely have updated if yo
u check again in a few hours.
Tue Feb 27 19:00:17 2024 -> Clamd successfully notified about the update.

**Comment by micahsnyder** [comment]
Which version of ClamAV are you using?

**Comment by micahsnyder** [comment]
I believe this issue was fixed in versions:
- 1.1.0+, here: https://github.com/Cisco-Talos/clamav/commit/60f3413bf3a5b7cd4cd8ba3d07634f53306833ec
- 1.0.2, here: https://github.com/Cisco-Talos/clamav/commit/1418fd2ed73772c36f4d30ffdc68d40df7a71402

This issue still affects the 0.105 version, which is no longer supported.

**Comment by DGPickett** [comment]
I do all the usual updates using snap, flatpak, software, software updater.

----------- SCAN SUMMARY -----------
Known viruses: 8701354
Engine version: 0.105.1
Scanned directories: 24555
Scanned files: 220119
Infected files: 31
Data scanned: 67220.79 MB
Data read: 52396.55 MB (ratio 1.28:1)
Time: 43719.714 sec (728 m 39 s)
Start Date: 2024:02:29 19:05:01
End Date:   2024:03:01 07:13:41

So to update, I have to unistall and reinstall, or is there a clean update out there somewhere.  I am using Ubuntu 22.04 LTS.

**Comment by DGPickett** [comment]
I removed it and installed 1.3.0, and now freshclam has a new complaint:

dgp@dgp-p6803w:~
$ /usr/local/bin/freshclam --datadir=/home/dgp/.clamtk/db --log=/home/dgp/.clamtk/db/freshclam_$(date +\%Y-\%m-\%d).log
Fri Mar  1 17:19:53 2024 -> ClamAV update process started at Fri Mar  1 17:19:53 2024
Fri Mar  1 17:19:53 2024 -> daily.cld database is up-to-date (version: 27201, sigs: 2054082, f-level: 90, builder: raynman)
Fri Mar  1 17:19:53 2024 -> main.cld database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Fri Mar  1 17:19:53 2024 -> bytecode database available for update (local version: 334, remote version: 335)
Current database is 1 version behind.
Downloading database patch # 335...
Time:    0.2s, ETA:    0.0s [========================>]       836B/836B
Fri Mar  1 17:19:53 2024 -> Testing database: '/home/dgp/.clamtk/db/tmp.745c22faa7/clamav-67c817aebb6281b7a4e6d5716c1a2adf.tmp-bytecode.cld' ...
Fri Mar  1 17:19:53 2024 -> Database test passed.
Fri Mar  1 17:19:53 2024 -> bytecode.cld updated (version: 335, sigs: 86, f-level: 90, builder: raynman)
ERROR: Fri Mar  1 17:19:53 2024 -> NotifyClamd: Can't find or parse configuration file /etc/clamav/clamd.conf
dgp@dgp-p6803w:~
$

**Comment by DGPickett** [comment]
Funny, later under cron it was quieter, perhaps because no update:

Fri Mar  1 19:00:01 2024 -> --------------------------------------
Fri Mar  1 19:00:01 2024 -> ClamAV update process started at Fri Mar  1 19:00:01 2024
Fri Mar  1 19:00:01 2024 -> daily.cld database is up-to-date (version: 27201, sigs: 2054082, f-level: 90, builder: raynman)
Fri Mar  1 19:00:01 2024 -> main.cld database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Fri Mar  1 19:00:01 2024 -> bytecode.cld database is up-to-date (version: 335, sigs: 86, f-level: 90, builder: raynman)

**Comment by micahsnyder** [comment]
@DGPickett I'm glad to hear you were able to upgrade your ClamAV version and that it's working again.

The error at the end is because your `freshclam.conf` defines the "NotifyClamd" option which would be used to tell the `clamd` service to reload to get the new signatures immediately.  

It seems you're not using `clamd` and don't have `/etc/clamav/clamd.conf` set up. You don't need it for `clamscan` anyways. 

Even if you were using `clamd`, you don't actually need the "NotifyClamd" option.  `clamd` automatically checks for changes to the database directory and will reload if it finds them.  It's safe to remove the "NotifyClamd" option from your `freshclam.conf` config, if you wish to get rid of that error.

**Comment by DGPickett** [comment]
Any idea why it does not get updated like other apps?
    On Saturday, March 2, 2024 at 09:27:28 AM EST, Micah Snyder ***@***.***> wrote:  
 
 


Closed #1191 as completed.

**Comment by DGPickett** [comment]
PS: The downloaded 1.3.0 install deb does not seem to start the clamd, but my old install did.

**Comment by DGPickett** [comment]
PPS Does clamd do anything if I scan with clamscan?

**Comment by DGPickett** [comment]
I installed clamd and turned it on, just in case!  Had to make a clamd.conf, so install a bit flaky!

dgp@dgp-p6803w:~
$ which clamd
/usr/local/sbin/clamd
dgp@dgp-p6803w:~
$ clamd --version
ERROR: Can't open/parse the config file /usr/local/etc/clamd.conf
dgp@dgp-p6803w:~
$ touch /usr/local/etc/clamd.conf
touch: cannot touch '/usr/local/etc/clamd.conf': Permission denied
dgp@dgp-p6803w:~
$ sudo touch /usr/local/etc/clamd.conf
[sudo] password for dgp: 
dgp@dgp-p6803w:~
$ clamd --version
ClamAV 1.3.0
dgp@dgp-p6803w:~
$

**Comment by micahsnyder** [comment]
You'll need to set the "LocalSocket" optin or "TCPSocket" option at a minimum if you want to run `clamd`. More details here https://docs.clamav.net/manual/Usage/Configuration.html#clamdconf

**Comment by micahsnyder** [comment]
> Any idea why it does not get updated like other apps?

It depends on how you installed it, and who provides the clamav packages.



> PS: The downloaded 1.3.0 install deb does not seem to start the clamd, but my old install did.

Yeah our deb package is not as fancy or as preconfigured as the ones provided by ubuntu or debian. 



> PPS Does clamd do anything if I scan with clamscan?

No.
