### ISSUE TITLE
Permission on new install trying to run freshclam

### ISSUE THREAD

**Issue by cgakers** [Cisco-Talos/clamav#1193]
```sh
pi-star@pi-star(ro):~$ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://httpredir.debian.org/debian bullseye-backports InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
pi-star@pi-star(rw):~$ sudo apt-get install clamav
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  libclamunrar clamav-docs
The following NEW packages will be installed:
  clamav
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/157 kB of archives.
After this operation, 585 kB of additional disk space will be used.
Selecting previously unselected package clamav.
(Reading database ... 46842 files and directories currently installed.)
Preparing to unpack .../clamav_0.103.10+dfsg-0+deb11u1_armhf.deb ...
Unpacking clamav (0.103.10+dfsg-0+deb11u1) ...
Setting up clamav (0.103.10+dfsg-0+deb11u1) ...
Processing triggers for man-db (2.9.4-2) ...
pi-star@pi-star(rw):~$ sudo freshclam
ERROR: Can't open /var/log/clamav/freshclam.log in append mode (check permissions!).
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
ERROR: initialize: libfreshclam init failed.
ERROR: Initialization error!
```

**Comment by ragusaa** [comment]
Hi,

Have you verified that the directory /var/log/clamav exists and the user you are running freshclam as can write to it?

**Comment by ragusaa** [comment]
clamscan does take a few minutes to load the signatures, I would expect it to be longer on a raspberry pi.  Could you try this
1.  Save 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' to a string (no newline).
2. run the command "clamscan -d <your signature directory>/bytecode.cvd <file that you saved>

The bytecode.cvd signature file is very small and should load really fast.  

Also, could you run with '--debug' and upload the output?

Thanks,
Andy

**Comment by cgakers** [comment]
After a reinstall I get this when I now run freshclam ???

sudo freshclam
Mon Mar  4 17:34:33 2024 -> ClamAV update process started at Mon Mar  4 17:34:33 2024
Mon Mar  4 17:34:33 2024 -> ^Your ClamAV installation is OUTDATED!
Mon Mar  4 17:34:33 2024 -> ^Local version: 0.103.10 Recommended version: 0.103.11
Mon Mar  4 17:34:33 2024 -> DON'T PANIC! Read https://docs.clamav.net/manual/Installing.html
Mon Mar  4 17:34:33 2024 -> daily.cvd database is up-to-date (version: 27204, sigs: 2054232, f-level: 90, builder: raynman)
Mon Mar  4 17:34:33 2024 -> main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Mon Mar  4 17:34:33 2024 -> bytecode.cvd database is up-to-date (version: 335, sigs: 86, f-level: 90, builder: raynman)

-g

From: ragusaa ***@***.***>
Date: Monday, March 4, 2024 at 5:17 PM
To: Cisco-Talos/clamav ***@***.***>
Cc: Gregory Akers ***@***.***>, Author ***@***.***>
Subject: Re: [Cisco-Talos/clamav] Permission on new install trying to run freshclam (Issue #1193)

clamscan does take a few minutes to load the signatures, I would expect it to be longer on a raspberry pi. Could you try this

  1.  Save ***@***.***<https://github.com/ap>[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' to a string (no newline).
  2.  run the command "clamscan -d /bytecode.cvd

The bytecode.cvd signature file is very small and should load really fast.

Also, could you run with '--debug' and upload the output?

Thanks,
Andy

**Comment by ragusaa** [comment]
You don't want to try and run that, the eicar string is used to test antivirus products.  It should signature, but won't cause any damage.  For a better explanation, check out https://www.eicar.org/download-anti-malware-testfile/

In your case, freshclam is not able to download signatures because your version of freshclam is too old.  Our supported versions are on our downloads page here https://www.clamav.net/downloads.  If there isn't a version there for your platform, your best bet is to contact your package maintainer or build from source.

**Comment by ragusaa** [comment]
If you are going to download from our downloads page, I would suggest going with 1.3 (latest), because 0.103 will be EOL'd later this year.

**Comment by cgakers** [comment]
Thanks !

-g

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ragusaa** [comment]
No problem.  I am going to close this issue, but let us know if you have any other issues getting set up.

Thanks,
Andy

**Comment by ragusaa** [comment]
It just occurred to me that you could also try our docker image.
https://hub.docker.com/u/clamav
Documentation is here https://docs.clamav.net/manual/Installing/Docker.html

**Comment by cgakers** [comment]
Thanks !

-g

From: ragusaa ***@***.***>
Date: Tuesday, March 5, 2024 at 5:31 PM
To: Cisco-Talos/clamav ***@***.***>
Cc: Gregory Akers ***@***.***>, Author ***@***.***>
Subject: Re: [Cisco-Talos/clamav] Permission on new install trying to run freshclam (Issue #1193)

It just occurred to me that you could also try our docker image.
https://hub.docker.com/u/clamav
Documentation is here https://docs.clamav.net/manual/Installing/Docker.html

**Comment by micahsnyder** [comment]
@cgakers okay to close this ticket?

**Comment by cgakers** [comment]
yes

From: Micah Snyder ***@***.***>
Date: Tuesday, May 14, 2024 at 10:14 AM
To: Cisco-Talos/clamav ***@***.***>
Cc: Gregory Akers ***@***.***>, Mention ***@***.***>
Subject: Re: [Cisco-Talos/clamav] Permission on new install trying to run freshclam (Issue #1193)

@cgakers<https://github.com/cgakers> okay to close this ticket?
