### ISSUE TITLE
Please open access to a new subnet

### ISSUE THREAD

**Issue by Yurka029** [Cisco-Talos/clamav#1200]
Describe the bug
----------------

Please open access to the new subnet 5.133.120.0/22 v https://database.clamav.net

Attachments
-----------
![image](https://github.com/Cisco-Talos/clamav/assets/162543752/19299ef1-6e86-40a6-8d15-c2615d208eba)

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
@Yurka029 it's possible that our IP geolocation rules are misclassifying your IP as being Russian and blocking for that reason.  It's also possible that Cloudflare's own IP geolocation rules are doing the same. 

However, I see you're testing with a browser.  We only allow database downloads using the `freshclam` program, which comes with a clamav installation, or [the CVDUpdate software](https://github.com/Cisco-Talos/cvdupdate). 

Please try using `freshclam` and use the `--verbose` option.  If you're still blocked, we can use the `cf-ray` value in the HTTP 403 response from found in the `freshclam --verbose` output to search the logs on our side to confirm the reason for the block.

**Comment by Yurka029** [comment]
@micahsnyder Hello. Please tell me through the browser from other allowed ip addresses, we are able to download the database. We also used commands based on your recommendation of freshclam, but there is no point. Can you please check and give access
![photo_2024-03-07_10-11-32](https://github.com/Cisco-Talos/clamav/assets/162543752/2ecb1fe6-e4e1-4e33-9019-5549343bfc4c)

**Comment by ragusaa** [comment]
Hi,

We need the cf-ray id from your attempted download to be able to tell what the problem is, so that we can help.  If you have a database directory already, make sure to delete 'freshclam.dat', then run 

freshclam --verbose

Thanks,
Andy

**Comment by micahsnyder** [comment]
Closing stale ticket.
