### ISSUE TITLE
Documentation Broken Link: Troubleshooting FAQ

### ISSUE THREAD

**Issue by sc-draymond** [Cisco-Talos/clamav#1204]
The "more information here" link for the following sections are broken:
- ClamAV becomes unresponsive
- ClamAV stops responding after about 24 hours
- ClamAV crashes once each day

https://docs.clamav.net/faq/faq-troubleshoot.html#troubleshooting-faq

----------------

Replace this text with a clear and concise description of the bug or feature request.

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
It seems like the link should go here: https://docs.clamav.net/manual/Installing/Docker.html

The affected documentation code is here: https://github.com/Cisco-Talos/clamav-documentation/blob/main/src/faq/faq-troubleshoot.md?plain=1#L79-L87
