### ISSUE TITLE
 Hello, I cannot download signatures.. My ip 91.198.118.212. It looks like it's some kind of block for this IP address because it works fine on another IP

### ISSUE THREAD

**Issue by radulam** [Cisco-Talos/clamav#1243]
Mon Apr 15 09:22:43 2024 -> *Current working dir is /var/lib/clamav/
Mon Apr 15 09:22:43 2024 -> *Can't open freshclam.dat in /var/lib/clamav
Mon Apr 15 09:22:43 2024 -> *It probably doesn't exist yet. That's ok.
Mon Apr 15 09:22:43 2024 -> *Failed to load freshclam.dat; will create a new freshclam.dat
Mon Apr 15 09:22:43 2024 -> *Creating new freshclam.dat
Mon Apr 15 09:22:43 2024 -> *Saved freshclam.dat
Mon Apr 15 09:22:43 2024 -> ClamAV update process started at Mon Apr 15 09:22:43 2024
Mon Apr 15 09:22:43 2024 -> *Current working dir is /var/lib/clamav/
Mon Apr 15 09:22:43 2024 -> *Querying current.cvd.clamav.net
Mon Apr 15 09:22:43 2024 -> *TTL: 1364
Mon Apr 15 09:22:43 2024 -> *fc_dns_query_update_info: Software version from DNS: 0.103.11
Mon Apr 15 09:22:43 2024 -> ^Your ClamAV installation is OUTDATED!
Mon Apr 15 09:22:43 2024 -> ^Local version: 0.103.8 Recommended version: 0.103.11
Mon Apr 15 09:22:43 2024 -> DON'T PANIC! Read https://docs.clamav.net/manual/Installing.html
Mon Apr 15 09:22:43 2024 -> *Current working dir is /var/lib/clamav/
Mon Apr 15 09:22:43 2024 -> *check_for_new_database_version: Local copy of daily found: daily.cld.
Mon Apr 15 09:22:43 2024 -> *query_remote_database_version: daily.cvd version from DNS: 27245
Mon Apr 15 09:22:43 2024 -> daily.cld database is up-to-date (version: 27245, sigs: 2059145, f-level: 90, builder: raynman)
Mon Apr 15 09:22:43 2024 -> *fc_update_database: daily.cld already up-to-date.
Mon Apr 15 09:22:43 2024 -> *Current working dir is /var/lib/clamav/
Mon Apr 15 09:22:43 2024 -> *check_for_new_database_version: Local copy of main found: main.cvd.
Mon Apr 15 09:22:43 2024 -> *query_remote_database_version: main.cvd version from DNS: 62
Mon Apr 15 09:22:43 2024 -> main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Mon Apr 15 09:22:43 2024 -> *fc_update_database: main.cvd already up-to-date.
Mon Apr 15 09:22:43 2024 -> *Current working dir is /var/lib/clamav/
Mon Apr 15 09:22:43 2024 -> *check_for_new_database_version: Local copy of bytecode found: bytecode.cvd.
Mon Apr 15 09:22:43 2024 -> *query_remote_database_version: bytecode.cvd version from DNS: 335
Mon Apr 15 09:22:43 2024 -> bytecode.cvd database is up-to-date (version: 335, sigs: 86, f-level: 90, builder: raynman)
Mon Apr 15 09:22:43 2024 -> *fc_update_database: bytecode.cvd already up-to-date.
Mon Apr 15 09:22:43 2024 -> *Current working dir is /var/lib/clamav/
Mon Apr 15 09:22:43 2024 -> *Retrieving https://www.securiteinfo.com/get/signatures/b652ab7b2a01f23bc1b46c49a09fd64db520e1dbafe765caf68e2c18ad79c0a2834dd83236497993dd22adb7568d03655ad2694ef998acb8b98d70ed52b56154/securiteinfo.hdb
Mon Apr 15 09:22:43 2024 -> *downloadFile: Download source:      https://www.securiteinfo.com/get/signatures/b652ab7b2a01f23bc1b46c49a09fd64db520e1dbafe765caf68e2c18ad79c0a2834dd83236497993dd22adb7568d03655ad2694ef998acb8b98d70ed52b56154/securiteinfo.hdb
Mon Apr 15 09:22:43 2024 -> *downloadFile: Download destination: /var/lib/clamav/tmp.b679b7bdb8/clamav-b1b68b94deba35d62c4d26fe8b074198.tmp
*   Trying 104.26.10.102:443...
* Connected to www.securiteinfo.com (104.26.10.102) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=securiteinfo.com
*  start date: Apr 11 02:34:06 2024 GMT
*  expire date: Jul 10 02:34:05 2024 GMT
*  subjectAltName: host "www.securiteinfo.com" matched cert's "*.securiteinfo.com"
*  issuer: C=US; O=Let's Encrypt; CN=E1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /get/signatures/b652ab7b2a01f23bc1b46c49a09fd64db520e1dbafe765caf68e2c18ad79c0a2834dd83236497993dd22adb7568d03655ad2694ef998acb8b98d70ed52b56154/securiteinfo.hdb]
* h2h3 [:scheme: https]
* h2h3 [:authority: www.securiteinfo.com]
* h2h3 [user-agent: ClamAV/0.103.8 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64, UUID: edd6bed8-26de-4a21-9575-76541fe0c664)]
* h2h3 [accept: */*]
* h2h3 [if-modified-since: Tue, 02 Apr 2024 10:26:18 GMT]
* Using Stream ID: 1 (easy handle 0x55835b62f040)
> GET /get/signatures/b652ab7b2a01f23bc1b46c49a09fd64db520e1dbafe765caf68e2c18ad79c0a2834dd83236497993dd22adb7568d03655ad2694ef998acb8b98d70ed52b56154/securiteinfo.hdb HTTP/2
Host: www.securiteinfo.com
user-agent: ClamAV/0.103.8 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64, UUID: edd6bed8-26de-4a21-9575-76541fe0c664)
accept: */*
if-modified-since: Tue, 02 Apr 2024 10:26:18 GMT
connection: close

* old SSL session ID is stale, removing
< HTTP/2 403
< date: Mon, 15 Apr 2024 07:22:44 GMT
< content-type: text/html; charset=iso-8859-1
< content-security-policy: base-uri 'self' www.securiteinfo.com securiteinfo.com ; default-src 'self' www.securiteinfo.com securiteinfo.com *.paypal.com *.paypalobjects.com embeds.beehiiv.com www.chatbase.co ajax.cloudflare.com www.printfriendly.com www.worldcommunitygrid.org static.cloudflareinsights.com www.youtube-nocookie.com hcaptcha.com *.hcaptcha.com chrome-extension: 'unsafe-inline'; script-src 'self' www.securiteinfo.com securiteinfo.com *.paypal.com *.paypalobjects.com www.chatbase.co ajax.cloudflare.com static.cloudflareinsights.com https://static.cloudflareinsights.com/beacon.min.js maxcdn.bootstrapcdn.com translate.googleapis.com cdnjs.cloudflare.com hcaptcha.com *.hcaptcha.com embeds.beehiiv.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' www.securiteinfo.com securiteinfo.com fonts.googleapis.com maxcdn.bootstrapcdn.com 'unsafe-inline' data: translate.googleapis.com hcaptcha.com *.hcaptcha.com ; font-src 'self' www.securiteinfo.com securiteinfo.com maxcdn.bootstrapcdn.com fonts.gstatic.com github.com data: ; frame-ancestors www.worldcommunitygrid.org www.youtube-nocookie.com hcaptcha.com *.hcaptcha.com *.paypal.com *.paypalobjects.com embeds.beehiiv.com; img-src 'self' www.securiteinfo.com securiteinfo.com https://* data: blob: ; object-src 'self' www.securiteinfo.com securiteinfo.com ; connect-src 'self' www.securiteinfo.com securiteinfo.com *.paypal.com *.paypalobjects.com www.chatbase.co api.cognitive.microsofttranslator.com hcaptcha.com *.hcaptcha.com ;
< cf-cache-status: BYPASS
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=sJFus74ZSaUid4cWTfwH9uxAGq%2FkrC2%2BzJtLU1jOcfMc1Pz4zhDs86WCGqR91OH9un02xRyPOZ%2Bp%2BY%2BHSnSbeuS7AhldB0ezDWysHbLqYqYOZsqsPT0HGgFdSx5wquetJRkDnD20"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 874a2fa8af2c9295-FRA
< alt-svc: h3=":443"; ma=86400
<
* Connection #0 to host www.securiteinfo.com left intact
Mon Apr 15 09:22:44 2024 -> *Saved freshclam.dat
Mon Apr 15 09:22:44 2024 -> ^Can't download securiteinfo.hdb from https://www.securiteinfo.com/get/signatures/b652ab7b2a01f23bc1b46c49a09fd64db520e1dbafe765caf68e2c18ad79c0a2834dd83236497993dd22adb7568d03655ad2694ef998acb8b98d70ed52b56154/securiteinfo.hdb
Mon Apr 15 09:22:44 2024 -> ^FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
Mon Apr 15 09:22:44 2024 -> This could mean several things:
Mon Apr 15 09:22:44 2024 ->  1. You are running an out-of-date version of ClamAV / FreshClam.
Mon Apr 15 09:22:44 2024 ->     Ensure you are the most updated version by visiting https://www.clamav.net/downloads
Mon Apr 15 09:22:44 2024 ->  2. Your network is explicitly denied by the FreshClam CDN.
Mon Apr 15 09:22:44 2024 ->     In order to rectify this please check that you are:
Mon Apr 15 09:22:44 2024 ->    a. Running an up-to-date version of FreshClam
Mon Apr 15 09:22:44 2024 ->    b. Running FreshClam no more than once an hour
Mon Apr 15 09:22:44 2024 ->    c. If you have checked (a) and (b), please open a ticket at
Mon Apr 15 09:22:44 2024 ->       https://github.com/Cisco-Talos/clamav/issues
Mon Apr 15 09:22:44 2024 ->       and we will investigate why your network is blocked.
Mon Apr 15 09:22:44 2024 -> ^You are on cool-down until after: 2024-04-16 09:22:44
Mon Apr 15 09:22:44 2024 -> ^fc_download_url_databases: fc_download_url_database failed: Forbidden; Blocked by CDN (17)
Mon Apr 15 09:22:44 2024 -> !Database update process failed: Forbidden; Blocked by CDN
Mon Apr 15 09:22:44 2024 -> !Update failed.

**Comment by micahsnyder** [comment]
@radulam Looks like you're being blocked by securiteinfo.com, not clamav.net. Securiteinfo is a third-party malware signature provider.  You will have to contact them for help.
