### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by gladiatr72** [Cisco-Talos/clamav#1246]
This is not a bug report, and I do not need help.

I wanted to thank you all for your efforts at maintaining and continuing to develop such a fine piece of OSS.  It has all the glamour of a handful of coal but continues to provide valuable functionality and reliability.  With all that is new and shiny in our line of work (and all the benefits to the professional profile of swimming in that stream), you probably deserve more credit than taking care of such a venerable tool as this.  I do not imagine we'll run into each other but if we ever do, the celebratory beverages are on me.

**Comment by micahsnyder** [comment]
@gladiatr72 Thank you for the kind words. I passed along the link to an internal chat room with a larger group of developers, researchers, and managers involved in producing ClamAV and ClamAV malware detection signatures. Your words were much appreciated.
