### ISSUE TITLE
https://www.clamav.net/ not available from GitHub CI

### ISSUE THREAD

**Issue by chkpnt** [Cisco-Talos/clamav#1250]
Describe the bug
----------------

I've a link to https://www.clamav.net in my [README.md](https://github.com/chkpnt/chkpnt-mailserver/blob/15.5/README.md). I'm using [github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check) to check for dead links and unfortunately, it seems that https://www.clamav.net can't be accessed [from the GitHub CI environment](https://github.com/chkpnt/chkpnt-mailserver/actions/runs/8774204207/job/24075165222) (status code 403).

How to reproduce the problem
----------------------------

Try to access https://www.clamav.net with a GitHub Action.

Attachments
-----------

<img width="800" alt="grafik" src="https://github.com/Cisco-Talos/clamav/assets/1956979/64871a71-9646-4989-b46e-2f19b7b03b52">

**Comment by brebell** [comment]
The link works if you go there manually in a browser, .  So it's safe to ignore the dead link.  Perhaps you can add an exception to their markdown link checker?

**Comment by chkpnt** [comment]
Yes, I've already done this. If the behavior (blocking traffic from GitHub CI) is intended, you can close this issue.

**Comment by micahsnyder** [comment]
@chkpnt I believe this is intentional - the result of Cloudflare's bot detection feature.
