### ISSUE TITLE
Unable to download database updates

### ISSUE THREAD

**Issue by mrlerch** [Cisco-Talos/clamav#1275]
Hello, 
For some time I have not been able to download database updates.

Software settings
-----------------
Version: 0.100.3
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE ICONV JSON 

Database information
--------------------
Database directory: /var/lib/clamav
daily.cld: version 25442, sigs: 1564671, built on Tue May  7 01:01:24 2019
daily.cvd: version 25401, sigs: 1532768, built on Wed Mar 27 00:50:11 2019
bytecode.cld: version 328, sigs: 94, built on Wed Jan  2 06:42:37 2019
bytecode.cvd: version 328, sigs: 94, built on Wed Jan  2 06:42:37 2019
main.cld: version 59, sigs: 4564902, built on Mon Nov 25 05:56:15 2019
Total number of signatures: 7662529

clamav]# freshclam
ClamAV update process started at Tue May 28 18:35:44 2024
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.11
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:db54)
Trying host database.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:da54)
WARNING: Can't download main.cvd from database.clamav.net
Trying again in 5 secs...
ClamAV update process started at Tue May 28 18:35:50 2024
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.11
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
Trying host database.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:da54)
Trying host database.clamav.net (2606:4700::6810:db54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:db54)
WARNING: Can't download main.cvd from database.clamav.net
Trying again in 5 secs...
ClamAV update process started at Tue May 28 18:35:56 2024
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.11
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from database.clamav.net
ERROR: getpatch: Can't download main-60.cdiff from database.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
Trying host database.clamav.net (2606:4700::6810:db54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:db54)
Trying host database.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:da54)
ERROR: Can't download main.cvd from database.clamav.net
Giving up on database.clamav.net...
ClamAV update process started at Tue May 28 18:35:56 2024
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.11
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from db.local.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from db.local.clamav.net
ERROR: getpatch: Can't download main-60.cdiff from db.local.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
Trying host db.local.clamav.net (2606:4700::6810:db54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.local.clamav.net (IP: 2606:4700::6810:db54)
Trying host db.local.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.local.clamav.net (IP: 2606:4700::6810:da54)
ERROR: Can't download main.cvd from db.local.clamav.net
Giving up on db.local.clamav.net...
Update failed. Your network may be down or none of the mirrors listed in /etc/freshclam.conf is working. Check https://www.clamav.net/documents/official-mirror-faq for possible reasons.

Please advise on how to fix this. Thanks.

**Comment by HydraDragonAntivirus** [comment]
Update your ClamAV version?

**Comment by micahsnyder** [comment]
@mrlerch, @HydraDragonAntivirus is correct.  You must update. ClamAV 0.100.3 is past end of life and is intentionally blocked.

Please see: https://docs.clamav.net/faq/faq-eol.html
