### ISSUE TITLE
ClamAV not detective infected file if we keep malicious string in middle or end of file.

### ISSUE THREAD

**Issue by clamavissue** [Cisco-Talos/clamav#1277]
Describe the bug
----------------

We tried with creating text file with putting malicious string which is in eicar file at start,in middle and in end of file.

We are using clamav latest version which is 1.3.1.

When we put string in start it detects it as infected but when string is in middle or end it dont detect it as infected.

Is there any reson for this?

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
The EICAR test file is not intended to be used that way.  ClamAV is very strict in how it detects EICAR.

The rules are as follows:

> THE ANTI-MALWARE TESTFILE
> It is also short and simple – in fact, it consists entirely of printable ASCII characters, so that it can easily be created with a regular text editor. Any anti-virus product that supports the EICAR test file should detect it in any file providing that the file starts with the following 68 characters, and is exactly 68 bytes long:
> 
> X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
> The first 68 characters is the known string. It may be optionally appended by any combination of whitespace characters with the total file length not exceeding 128 characters. The only whitespace characters allowed are the space character, tab, LF, CR, CTRL-Z. To keep things simple the file uses only upper case letters, digits and punctuation marks, and does not include spaces. The only thing to watch out for when typing in the test file is that the third character is the capital letter “O”, not the digit zero.
> 
> This test file has been provided to EICAR for distribution as the “EICAR Standard Anti-Virus Test File”, and it satisfies all the criteria listed above. It is safe to pass around, because it is not a virus, and does not include any fragments of viral code. Most products react to it as if it were a virus (though they typically report it with an obvious name, such as “EICAR-AV-Test”).
> 
> The file is a legitimate DOS program, and produces sensible results when run
> 
> (IT PRINTS THE MESSAGE “EICAR-STANDARD-ANTIVIRUS-TEST-FILE!”).

Reference: https://www.eicar.org/download-anti-malware-testfile/

EICAR is to be treated as a file and will be detected by ClamAV when found in archives or attached (as a file) to emails, or documents. 

EICAR should NOT be detected when it is pasted into the middle of a text file, or otherwise embedded or appended in other files without structure.  This includes things like pasting it (as text) in the cell of a spreadsheet.  (Conversely, if you attach EICAR as a file to a spreadsheet then ClamAV should detect it.)

**Comment by clamavissue** [comment]
Hello,

Thanks for reply.
Can you please let us know how to create infected file of size 1GB? Do you have any such test file.

Thanks
Dipti

**Comment by micahsnyder** [comment]
I do not. Perhaps you could modify an existing large archive to add in the EICAR test file. For example, mount large ISO disk image and then add a file.

**Comment by mavjop** [comment]
@val-ms -
> I do not. Perhaps you could modify an existing large archive to add in the EICAR test file. For example, mount large ISO disk image and then add a file.

That is indeed a reasonable suggestion, but as I understand the ClamAV configuration options:
* `MaxFileSize` is a limit for the maximum file size to scan (hard limit: `2G`), but I'm not sure whether it applies to archives
* `MaxScanSize` is applied to archive files, and may be greater than `MaxFileSize`

So if one wants to make sure that a file of up to 2GB is scanned by ClamAV, in a system (verification) test situation, one would probably want to test the regular file handling code path, and not necessarily the (recursive) archive expansion path (one might **also** want to test that).

In addition to not being 100% sure if my understanding, above, is correct, I also don't know:
* whether `MaxFileSIze` is applied to an archive file before expanding?
* whether `MaxFileSIze` is applied to each file expanded from an archive?
* what ClamAV does if it reaches `MaxScanSize` -- does it scan everything up to before that, then stop, or does it detect that what has been (or will be) expanded exceeds the limit, and not scan any of the files from within the archive?

I appreciate the rigor with which ClamAV adheres to the EICAR standard. That said, though, it would be awfully useful to have a mechanism for testing installations/deployments of ClamAV for scanning and detecting files with threats up to the configured and/or hard limit. Trend Micro's CloudOne **does** detect an EICAR file padded with zeros (e.g. make an EICAR file, then `truncate -s 2G my_eicar_file.txt`), making it a very useful test option.

I assume the reason for the EICAR spec being so restrictive is that they don't want documents or e-mails or what have you *talking about how to use EICAR* to be flagged as threats. The spec seems unnecessarily restrictive to meet that goal, though. Presumably no such file/e-mail/document would ever be the EICAR string followed only by whitespace or zeros. I wish they'd relax the spec, to allow for this.

Questions:
1. Would the ClamAV maintainers consider relaxing the restrictions to allow the EICAR file mechanism to be used for testing with larger file sizes, by adhering **slightly** less strictly to the spec.
   * File must **begin** with the EICAR string.
   * File may be padded with whitespace or zeros ('\0').
1. Alternatively, would you consider adding a mechanism other than EICAR for performing positive threat detection testing supporting files of arbitrarily large size (up to the configured or hard limit for `MaxFileSize`)?
   * I'm not sure what the best option would be for this.
   * Perhaps you could define a ClamAV specific test string that any file must begin with, and which will cause it to be scanned up the configured limit.
   * Perhaps you could define a file name pattern that such a file must match to have the test string get matched as a threat?
   * I'm imagining something like if the file contains `X5O!P%@AP[4\PZX54(P^)7CC)7}$CLAMAV-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*` **AND** filename begins with `clamav-standard-antivirus-test-file`?

Thank you for your consideration. :)

**Comment by mavjop** [comment]
Thank you very much for your detailed response, @val-ms! I'll look into extended signatures for testing purposes. I guess that does solve the problem.

I do still wonder if it would be worth having some test signature that isn't EICAR that ClamAV would support (it could presumably be highly unlikely to ever occur in any file unintentionally), only when placed at the start of an arbitrarily large file, to avoid people having to roll their own, but I'll make do with rolling my own signature. :)

**Comment by val-ms** [comment]
@mavjop someone will probably want it to be detected in the middle or end of an arbitrarily large file as well. I'm not opposed to the idea, though the middle/end support may make it difficult to tell people how to use it without the instructions alerting on the test signature. Perhaps we could add the test signature file separately to the clamav online documentation for download so it isn't in the standard database.

**Comment by mavjop** [comment]
Yeah, I said "at the start (only)" because I understand that you don't want the source file to trip the scanner, and you don't want a document describing how to test with it to trip the scanner, and you don't want an e-mail that mentions it to trip the scanner. I would think, however, that it could be safe to have some arbitrary but very unique string of bytes at the start of a file be sufficient to test with large files (does the scanner even try to scan the file). :)

If could be "will only recognize it if it is this string followed by zeros (bytes with value 0 (`\0`))", but perhaps that would be difficult, so maybe just have it be long enough that anchored at the very start of the file is sufficient to avoid any false positives?
