### ISSUE TITLE
^FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).

### ISSUE THREAD

**Issue by yuneltoro** [Cisco-Talos/clamav#1285]
Sat Jun 22 08:34:38 2024 -> ^Can't download daily.cvd from https://database.clamav.net/daily.cvd
Sat Jun 22 08:34:38 2024 -> ^FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
Sat Jun 22 08:34:38 2024 -> ^You are on cool-down until after: 2024-06-23 08:34:38
Sat Jun 22 08:34:38 2024 -> !Database update process failed: Forbidden; Blocked by CDN
Sat Jun 22 08:34:38 2024 -> !Update failed.

  Cloudflare Ray ID: 897c4a6079ad74b2 • Your IP: (BUTTON) Click to reveal 152.206.118.150 • Performance & security by Cloudflare

How can resolve it

**Comment by micahsnyder** [comment]
@yuneltoro Unfortunately, Cuba is on our list of countries blocked by US sanctions. I'm sorry. You might try this as as a workaround https://github.com/Cisco-Talos/clamav/issues/851#issuecomment-1456869064
