### ISSUE TITLE
False/positive

### ISSUE THREAD

**Issue by freakynl** [Cisco-Talos/clamav#1291]
Hi,

we're running into a false positive on a DLL.

File can be found here: https://freaky.bananateam.nl/Aspose.Words.dll

It's detected as Win.Malware.Ausiv-9881459-0

Besides ClamAV it's clean everywhere else (https://www.virustotal.com/gui/file/b59131a3c05602c982f150edc6570babfd2bcee7b8b6af6d705619d9b8ebed06).

I've submitted this through the false/positive portal over 4 times over the past 1,5 month. Since that doesn't help at all filing the bug here.

**Comment by micahsnyder** [comment]
Sorry the FP report form didn't work for you.  I will investigate.

**Comment by freakynl** [comment]
Thanks :)

If you need anything let me know. Didn't get any e-mails from the false/positive submission either by the way. No clue if it's supposed to send an e-mail upon submission though.

**Comment by micahsnyder** [comment]
A drop has been put in for the signature.  It should be gone in tomorrow's daily database update.
