### ISSUE TITLE
Please provide a solution to load the database into RAM once and automatically

### ISSUE THREAD

**Issue by bekraouiakram96** [Cisco-Talos/clamav#1297]
Hey ClamAV,

I'm using ClamAV on Linux Ubuntu to scan files with the clamscan command. However, I'm encountering a recurring issue where every time I run clamscan /path, it reloads the signature database, causing delays.

Could you please provide a solution to load the database into RAM once and automatically ensure that clamscan uses this pre-loaded database for real-time scans?

Thank you!

**Comment by micahsnyder** [comment]
@bekraouiakram96 Clamd is the solution to load the database into ram once. Once the `clamd` service is running, you can issue scan requests with `clamdscan` (instead of `clamscan`). 

See also https://docs.clamav.net/manual/Usage/Scanning.html#clamdscan
