### ISSUE TITLE
--max-files=X fails to execute on win64x

### ISSUE THREAD

**Issue by MiscMyth** [Cisco-Talos/clamav#1321]
**Greetings, Clams!**
Not sure if that's how I should address this community as it is my first time posting. But long story short, the --max-files option does not appear to be considered by clamscan. Below I'll attach some screenshots to visualize the issue.

![Screenshot 2024-07-28 150806](https://github.com/user-attachments/assets/3c029b9a-14cd-4070-b02f-f22d7f230854)

As visible in the photo above, I have set the maximum files to scan in the directory to eight (8), but if you count the total files scanned it's apparent that though it's scanning exclusively one directory with no sub directories and no references to files within the test document. (They all just say 'Test' inside). But this clamscan test runs across the entire directory and fails to cap the files searched at eight. I am aware this is a very low number, but I do not believe that should affect the issue. This issue happens in all programming languages and in the command prompt as seen. The issue does occur in any directory with or without recursive set. 

For the record, here's the description of what --max-files is supposed to do as according to --help:
`--max-files=#n                       The maximum number of files to scan for each container file (**)`

Again, I'm using win64x
- OS: Windows 11 (64x)
- Version: ClamAV 1.3.1/27349/Sat Jul 27 01:26:14 2024
- Not using the Daemon, this is just clamscan.
- The engine and libraries are up to date and the conf files are properly configured to my needs.

If you'd like a photo of the directory being scanned, here you are:
![Screenshot 2024-07-28 151848](https://github.com/user-attachments/assets/9e2a61db-c247-41c2-8be6-33c08c55a7ac)
Though note that this doesn't appear to have any relevance as though it has this issue regardless as to the scanned directory or sub-directory. For all of the mentioned reasons, I believe I have reason to assume this as a bug. I could not find any specific posts here on this subject nor could I find a solution or workaround anywhere.

Cheers, :)
Misc. Myth

**Comment by brebell** [comment]
Container does not mean directory.  It means a file containing other files, such as:
- an email with attachments
- a zip containing files
- a document with attached images
There is no option to limit the number of files scanned when scanning a directory.
If you want that functionality, you will have to make a script that calls clamscan for each file in a directory and add their own limits to the script.

If you want to go that route and have further questions please join us on the ClamAV discord https://discord.gg/rhsK5MUY
