### ISSUE TITLE
can only download GPG key if I use a real browser user-agent

### ISSUE THREAD

**Issue by maxadamo** [Cisco-Talos/clamav#1334]
Describe the bug
----------------

on #1329  I asked to be able to download `talos.gpg`. 
However it seems to work only from a browser, but not with curl or wget, unless I set a bogus user-agent header. 

How to reproduce the problem
----------------------------

This one doesn't work:

```bash
curl -I https://docs.clamav.net/manual/cisco-talos.gpg
HTTP/2 403
```

However, if I try a different user-agent I can download the file:

**Firefox**

```bash
curl -I -A "Mozilla" https://docs.clamav.net/manual/cisco-talos.gpg
HTTP/2 200
```

**Chrome**
```bash
curl -I -A "Chrome" https://docs.clamav.net/manual/cisco-talos.gpg
HTTP/2 200
```

Do you think we should leave it like this, and specify in the documentation that the header needs to be amended?

**Comment by maxadamo** [comment]
these user agents work: 

```
curl -I -A "Mozilla" https://docs.clamav.net/manual/cisco-talos.gpg
curl -I -A "Chrome" https://docs.clamav.net/manual/cisco-talos.gpg
```

**Comment by micahsnyder** [comment]
I'm not an expert with curl flags. The `-I` flag seems to be for document info and not for download:
```
-I, --head          Show document info only
```

You can use the `-O` flag to download, like:
```
curl -O https://docs.clamav.net/manual/cisco-talos.gpg
```
Alternatively, you can pull it from the github repo
```
curl -O https://raw.githubusercontent.com/Cisco-Talos/clamav-documentation/main/src/manual/cisco-talos.gpg
```
Or use `wget`:
```
wget https://docs.clamav.net/manual/cisco-talos.gpg
```

**Comment by maxadamo** [comment]
I used the `-I` switch for the sake of sharing with you the response code, otherwise you don't see the problem and you believe that it's working.  This is what happened the first time to me. 

If you run the curl and the wget command, you seem to have download the file, but if you `cat` the file, it's not a GPG public key, buy a response page from your Web server, saying "sorry".

**Comment by maxadamo** [comment]
this one works: 

```bash
curl -O https://raw.githubusercontent.com/Cisco-Talos/clamav-documentation/main/src/manual/cisco-talos.gpg
```

**Comment by micahsnyder** [comment]
> If you run the curl and the wget command, you seem to have download the file, but if you `cat` the file, it's not a GPG public key, buy a response page from your Web server, saying "sorry".
> 
> In other words, the `curl -O` and `wget` the you provided do not work

I tested each, with `cat` afterwards, before sharing them. All of my commands worked in my tests. Perhaps it is different for me because I am testing from within the Cisco Talos VPN right now.

**Comment by micahsnyder** [comment]
Ok tested from my home network and I see the Cloudflare 403 response. 

I'll change the documentation link to point directly to the github link.

**Comment by micahsnyder** [comment]
Done: https://github.com/Cisco-Talos/clamav-documentation/commit/88b2f7878475131bc6c5b127ef7b95a50366ef07

It will take a little bit for cloudflare's cache to pick up the changes.
