### ISSUE TITLE
Latest clamav release 1.4.0 does not provide clamav-1.4.0.tar.gz file

### ISSUE THREAD

**Issue by mingxiao** [Cisco-Talos/clamav#1335]
Latest clamav release 1.4.0 does not provide clamav-1.4.0.tar.gz file, even though there are  clamav-1.4.0.tar.gz.sig  and 
clamav-1.4.0.win.x64.zip.sig  files

We see that in the 1.3.1 release, the .tar.gz and .win.x64.zip files were provided.

Is this change intentional?

**Comment by micahsnyder** [comment]
Thanks for the report @mingxiao.  It appears as though the upload to GitHub was interrupted.  I have added the missing files.  You can also find them here https://www.clamav.net/downloads

**Comment by aramprice** [comment]
@micahsnyder - thanks for the quick turnaround!
