### ISSUE TITLE
Feature Request: Endpoint Central Manager

### ISSUE THREAD

**Issue by davidngrc** [Cisco-Talos/clamav#1355]
I am new to this, this feature might already exists, but I can't seems able to find it.

We have some Macbook/Mac, Windows Laptop/PC, and some Win / Ubuntu / CentOS server in different subnet.

1. Can we have a clamav 'Endpoint Central Manager", which install to a dedicate Linux server

2. this clamav 'Endpoint Central Manager" server can 
control (like uninstall/update_agent/update_db/sync_setting in the client)  
and monitor (like device ip, hostname, device_online_offline, device_last_seen, client scan logs) 
in all the clamav client in all the Macbook , Windows, Linux in different subnet?

3. While installing the clamav client in Macbook , Windows, Linux, 
we can specific the Endpoint Central Manager server ip in command line or GUI, 
after installation, we disallow changes by user except admin user in that client machine.

Please help.
Thank you.

**Comment by tj-cisco** [comment]
This sounds like an excellent candidate for a community driven product.  If you need this solution today you should consider our commercial offering Cisco Secure Endpoint.
