### ISSUE TITLE
Upgrade Alpine Linux packages to 1.4.1

### ISSUE THREAD

**Issue by miriamstreit** [Cisco-Talos/clamav#1381]
We're using the Alpine Linux package of ClamAV for our installation. As we were trying to upgrade to 1.4.1 we noticed that the Alpine Linux package is not up to date with the newest version being 1.3.2: [https://pkgs.alpinelinux.org/packages?name=clamav&branch=edge&repo=&arch=&origin=yes&flagged=&maintainer=
](https://pkgs.alpinelinux.org/packages?name=clamav&branch=edge&repo=&arch=&origin=yes&flagged=&maintainer=)

Could you please update the Alpine Linux package to 1.4.1 so we can upgrade?

Thank you!

**Comment by micahsnyder** [comment]
Hi @miriamstreit,

We don't maintain the Alpine packages. They're produced by volunteers working in the Alpine community.

Sorry!
