### ISSUE TITLE
Add the possibility to see the already found possibile threats during an active scanning

### ISSUE THREAD

**Issue by All3xJ** [Cisco-Talos/clamav#1391]
Describe the bug
----------------

It would be great if, instead of waiting for the entire scan to complete, you could see the possible threats currently detected in the meantime.

How to reproduce the problem
----------------------------

-Run a scan

Attachments
-----------

![image](https://github.com/user-attachments/assets/46fd2c2b-2d23-4327-a946-ab83f3fa655e)

**Comment by micahsnyder** [comment]
The issue you're reporting is for ClamTK which was made by a community member and is not made or supported by my team. 

Unfortunately, ClamTK is also no longer supported. https://gitlab.com/dave_m/clamtk/-/issues/144
