### ISSUE TITLE
Threats listed as "None" filename if the directory has a "&" character

### ISSUE THREAD

**Issue by All3xJ** [Cisco-Talos/clamav#1392]
Describe the bug
----------------

Threats listed after scan complete have a "None" filename if directory contains the "&" character.

How to reproduce the problem
----------------------------

-Run a scan in a directory that contains "&" character

Attachments
-----------

![image](https://github.com/user-attachments/assets/8e4e0035-b05d-4768-a556-a63c69e11c39)

**Comment by micahsnyder** [comment]
We don't make a GUI for ClamAV. I suspect the bug is in the GUI recording the results from ClamAV. What GUI are you using for ClamAV?

If I test this with the `clamscan` utility, it works okay:

```sh
❯ mkdir "Allie & Betty"

❯ cp ~/eicar ./Allie\ \&\ Betty/

❯ ~/clams/1.4.1/bin/clamscan -d ~/.cvdupdate/database ./Allie\ \&\ Betty/
Loading:    18s, ETA:   0s [========================>]    8.70M/8.70M sigs
Compiling:   2s, ETA:   0s [========================>]       41/41 tasks

/home/micah/Allie & Betty/eicar: Win.Test.EICAR_HDB-1 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8701623
Engine version: 1.4.1
Scanned directories: 1
Scanned files: 1
Infected files: 1
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 22.352 sec (0 m 22 s)
Start Date: 2024:10:28 09:45:35
End Date:   2024:10:28 09:45:57
```

**Comment by All3xJ** [comment]
> We don't make a GUI for ClamAV. I suspect the bug is in the GUI recording the results from ClamAV. What GUI are you using for ClamAV?

clamtk, sorry I thought it was maintained by this repo
