### ISSUE TITLE
ClamAV 1.0.7: clamscan and clamdscan on Ubuntu 24.04.1 (LTS) is really awful slow

### ISSUE THREAD

**Issue by MarkyMarkDE** [Cisco-Talos/clamav#1393]
clamscan => 0103.6/7 (LTS) 42k Files ~ 45 mins. (great time!)
clam**d**scan => 1.0.7 (LTS) 42k Files 2 hours 56 mins. or 176 mins. and clamscan has relative same times.
I do not/never scan my whole computer, I scan only specified Folders in /home/ partition.
This is really awful slow.

**Comment by micahsnyder** [comment]
I don't think we need another ticket on how slow clamav is.

We already have:
- This generic complaint about it being "awfully awfully unbearable slow": https://github.com/Cisco-Talos/clamav/issues/1393
- These complaints about 0.105 being slower than 0.103 (still the same basic gripe you have): 
  - https://github.com/Cisco-Talos/clamav/issues/1375
  - https://github.com/Cisco-Talos/clamav/issues/877
- This complaint about 0.104.1 and newer being much slower for a specific file than 0.104.0: https://github.com/Cisco-Talos/clamav/issues/715

**Comment by MarkyMarkDE** [comment]
Its okay, I just wanted to inform about this circumstance in ClamASV 1.0.7, because this problem persists here as well.

**Comment by micahsnyder** [comment]
No worries I will be careful with my synonyms. Perhaps 'gripe' came off too strongly. I think it is a fun word.

**Comment by MarkyMarkDE** [comment]
All is fine, maybe I understand some too wordly, you know, I'm not native English/American :wink:
