### ISSUE TITLE
Wazuh Integration. Logging virus detection to /var/log/syslog does not work

### ISSUE THREAD

**Issue by Fre33m0** [Cisco-Talos/clamav#1404]
After viewing the manual, setting LogSyslog to true is supposed to forward all logs to /var/log/syslog, but in the case, the logs related to the virus detection are not forwarded to the file.

Ubuntu 24.04
Install via:
sudo apt-get install clamav clamav-freshclam

Due to this error, we do not receive any warnings regarding viruses in Wazuh.

**Comment by Fre33m0** [comment]
Solved:
clamdscan --fdpass --log=/var/log/myclam.log /home/user/

clamav without "d" does not work.

**Comment by micahsnyder** [comment]
Glad to hear you solved it. 

`clamdscan` connects to `clamd`, and `clamd.conf` only applies to `clamd` and associated clients to `clamd` (e.g. `clamdscan`, `clamonacc`, and `clamav-milter`). 

`clamscan` does not use any config file and relies purely on commandline options.
