### ISSUE TITLE
Cloudflare blocking too agressive

### ISSUE THREAD

**Issue by optimapw** [Cisco-Talos/clamav#1422]
About 9 days ago my ClamAV quit updating. This is the message I am receiving today:

$ sudo freshclam
[sudo] password for mirror: 
ClamAV update process started at Tue Dec 17 22:01:19 2024
WARNING: Tue Dec 17 22:01:19 2024 -> FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).
Tue Dec 17 22:01:19 2024 -> This means that you have been rate limited or blocked by the CDN.
Tue Dec 17 22:01:19 2024 ->  1. Verify that you're running a supported ClamAV version.
Tue Dec 17 22:01:19 2024 ->     See https://docs.clamav.net/faq/faq-eol.html for details.
Tue Dec 17 22:01:19 2024 ->  2. Run FreshClam no more than once an hour to check for updates.
Tue Dec 17 22:01:19 2024 ->     FreshClam should check DNS first to see if an update is needed.
Tue Dec 17 22:01:19 2024 ->  3. If you have more than 10 hosts on your network attempting to download,
Tue Dec 17 22:01:19 2024 ->     it is recommended that you set up a private mirror on your network using
Tue Dec 17 22:01:19 2024 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Tue Dec 17 22:01:19 2024 ->     CDN and your own network.
Tue Dec 17 22:01:19 2024 ->  4. Please do not open a ticket asking for an exemption from the rate limit,
Tue Dec 17 22:01:19 2024 ->     it will not be granted.
WARNING: Tue Dec 17 22:01:19 2024 -> You are still on cool-down until after: 2024-12-18 21:32:47

I have repeatedly waited for the cool-down to expire but it remains blocked. Why am I being blocked?

Item 1 states "Verify that you're running a supported ClamAV version. See https://docs.clamav.net/faq/faq-eol.html for details." But attempt to open that results in (can not capture the whole page... at top displays 
"Sorry, you have been blocked
You are unable to access clamav.net"):
![image](https://github.com/user-attachments/assets/c37758c0-5208-4f92-8fef-3e3c72455ac7)
Perhaps a user should not be blocked from accessing information needed to self-resolve a problem. 
FYI my FreshClam version is:
$ freshclam --version
ClamAV 1.0.7/27482/Mon Dec  9 01:36:44 2024

Item 2 says not to run FreshClam more than once per hour. I manually run the following two commands once a day:
$ sudo /etc/init.d/clamav-freshclam stop
$ sudo freshclam

Item 3 is concerned about "your network". My network consists of Google WiFi installed in my residence with devices: My wife's Apple laptop, My Ubuntu laptop, Brother printer, 3 iPhones, FireTV, my son's, my daughter in law's, my daughter's iPhones when they stop by. Only my laptop uses ClamAV and my laptop is never used by anyone else and my laptop is well secured.  My laptop connects to the network using Proton VPN connection US-FREE#25. 

Instead of opening this bug report I tried the item above it. I can not remember what it was and do not want to lose what I am writing here to search for it. But when I tried that I am again blocked:
![image](https://github.com/user-attachments/assets/52c99eb1-98f2-4bed-870b-266958170158)
The URL in the above screen capture should identify what I tried. Once again, my actions to resolve this problem is blocked. The supposed reason I am blocked is because freshclam was run too often. You all want to minimize the load on your "ClamAV Content Delivery Network (CDN)". But you have also included all non-CDN content in the block. 

Somewhere in my web searches it was mentioned all issues must be submitted via GitHub. So I created YAWA! (yet another web account!) so I can log into GitHub to write this bug report. Why am I being blocked?

**Comment by micahsnyder** [comment]
The screenshots are helpful.  It shows you're being blocked by Cloudflare. However, I don't know if that's because rules or Cloudflare's own rules.  Your IP in the screenshot shows a US location so I suspect it's nothing we're doing. 

I've shared the CF-Ray ID from the screenshot with our Cloudflare account admin to see if they can find it in the logs.  If it's not in the logs, that means Cloudflare's own protections are blocking you and we won't be able to help.  I'll let you know what I hear.

**Comment by micahsnyder** [comment]
@optimapw our Cloudflare admin found an issue with the Geo-based IP block list. They've fixed it. You should be able to connect again.

**Comment by optimapw** [comment]
Freshclam just updated!

Thank you for your assistance.
