### ISSUE TITLE
Invalid link in warning message

### ISSUE THREAD

**Issue by alisonw** [Cisco-Talos/clamav#177]
Although my mail server (Modoboa) doesn't report it, the log on that machine issued a warning which tells you to go to a particular webpage for further information. Thing is, that page 404s. The warning text needs to be updated with the replaced target.
---
```
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> Received signal: wake up
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> ClamAV update process started at Tue Jun 29 13:02:59 2021
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> ^Your ClamAV installation is OUTDATED!
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> ^Local version: 0.103.2 Recommended version: 0.103.3
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> daily.cld database is up-to-date (version: 26216, sigs: 3992662, f-level: 63, builder: raynman)
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> main.cvd database is up-to-date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Jun 29 13:02:59 mail freshclam[1830]: Tue Jun 29 13:02:59 2021 -> bytecode.cvd database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)
```
---

**Comment by finchy** [comment]
Redirection created for now, leaving this here until @micahsnyder  can correct the URL link to: https://docs.clamav.net/faq/faq-upgrade.html

**Comment by micahsnyder** [comment]
I just updated all the links for the documentation and to recommend people use github issues instead of bugzilla. 
See:
https://github.com/Cisco-Talos/clamav/commit/d46832d5cf020ce9c0d093c87d8a3654d28cc913
https://github.com/Cisco-Talos/clamav/commit/cf63dad598ef57d083083449177be6cd2bebbcd4
