### ISSUE TITLE
Ubuntu not detecting latest version

### ISSUE THREAD

**Issue by zignzag12** [Cisco-Talos/clamav#188]
apt-get upgrade does not detect recommended version: 0.103.3:

# systemctl stop clamav-freshclam.service

# freshclam
Sun Jul  4 20:17:50 2021 -> ClamAV update process started at Sun Jul  4 20:17:50 2021
Sun Jul  4 20:17:50 2021 -> ^Your ClamAV installation is OUTDATED!
Sun Jul  4 20:17:50 2021 -> ^Local version: 0.103.2 Recommended version: 0.103.3
Sun Jul  4 20:17:50 2021 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Sun Jul  4 20:17:50 2021 -> daily.cld database is up-to-date (version: 26221, sigs: 3993342, f-level: 63, builder: raynman)
Sun Jul  4 20:17:50 2021 -> main.cvd database is up-to-date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Sun Jul  4 20:17:50 2021 -> bytecode.cld database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)

# systemctl start clamav-freshclam.service

# apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done

# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

# clamconf -n
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
PreludeAnalyzerName = "ClamAV"
LogFileMaxSize = "4294967295"
LogTime = "yes"
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
LocalSocket = "/var/run/clamav/clamd.ctl"
LocalSocketGroup = "clamav"
LocalSocketMode = "666"
MaxConnectionQueueLength = "15"
MaxThreads = "12"
ReadTimeout = "180"
SendBufTimeout = "200"
SelfCheck = "3600"
User = "clamav"
BytecodeTimeout = "60000"
MaxScanTime = "120000"
PCREMatchLimit = "10000"
PCRERecMatchLimit = "5000"
*** AllowSupplementaryGroups is DEPRECATED ***

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "4294967295"
LogTime = "yes"
LogRotate = "yes"
UpdateLogFile = "/var/log/clamav/freshclam.log"
Checks = "24"
DatabaseMirror = "db.local.clamav.net", "database.clamav.net"
MaxAttempts = "5"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.103.2
Optional features supported: MEMPOOL IPv6 FRESHCLAM_DNS_FIX AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR

Database information
--------------------
Database directory: /var/lib/clamav
main.cvd: version 59, sigs: 4564902, built on Mon Nov 25 07:56:15 2019
bytecode.cld: version 333, sigs: 92, built on Mon Mar  8 09:21:51 2021
daily.cld: version 26221, sigs: 3993342, built on Sun Jul  4 06:09:25 2021
Total number of signatures: 8558336

Platform information
--------------------
uname: Linux 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
Full OS version: Ubuntu 20.04.2 LTS
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x0a217b7b0800000000090300

Build information
-----------------
GNU C: 9.3.0 (9.3.0)
CPPFLAGS: -Wdate-time -D_FORTIFY_SOURCE=2
CFLAGS: -g -O2 -fdebug-prefix-map=/build/clamav-TW4JTf/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS: -g -O2 -fdebug-prefix-map=/build/clamav-TW4JTf/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64
LDFLAGS: -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed
Configure: '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-TW4JTf/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-TW4JTf/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FILE_OFFSET_BITS=64' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed' '--with-dbdir=/var/lib/clamav' '--sysconfdir=/etc/clamav' '--disable-clamav' '--disable-unrar' '--enable-milter' '--enable-dns-fix' '--with-libjson' '--with-system-libmspack' '--with-libcurl=/usr' '--with-gnu-ld' '--with-systemdsystemunitdir=/lib/systemd/system' 'build_alias=x86_64-linux-gnu' 'OBJCFLAGS=-g -O2 -fdebug-prefix-map=/build/clamav-TW4JTf/clamav-0.103.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security'
sizeof(void*) = 8
Engine flevel: 123, dconf: 123

**Comment by zignzag12** [comment]
# dpkg -l | grep clam
ii  clamav                                 0.103.2+dfsg-0ubuntu0.20.04.2     amd64        anti-virus utility for Unix - command-line interface
ii  clamav-base                            0.103.2+dfsg-0ubuntu0.20.04.2     all          anti-virus utility for Unix - base package
ii  clamav-daemon                          0.103.2+dfsg-0ubuntu0.20.04.2     amd64        anti-virus utility for Unix - scanner daemon
ii  clamav-freshclam                       0.103.2+dfsg-0ubuntu0.20.04.2     amd64        anti-virus utility for Unix - virus database update utility
ii  clamdscan                              0.103.2+dfsg-0ubuntu0.20.04.2     amd64        anti-virus utility for Unix - scanner client
ii  libclamav9:amd64                       0.103.2+dfsg-0ubuntu0.20.04.2     amd64        anti-virus utility for Unix - library
ii  libclamunrar9                          0.101.2-1build1                   amd64        anti-virus utility for Unix - unrar support

**Comment by finchy** [comment]
0.103.3 may not be released for the Debian/Ubuntu apt program yet.  you’ll need to contact the package maintainers for Ubuntu/Debian.

**Comment by dmknght** [comment]
There is a bug in `debian/rules` of Debian repository which doesn't allow version 1.10.3.3 compile code.

**Comment by micahsnyder** [comment]
Closing this ticket because Debian needs to publish the latest version. It's not something the clamav team works on.
