### ISSUE TITLE
cloudflare error-1020-access-denied

### ISSUE THREAD

**Issue by gowdab** [Cisco-Talos/clamav#189]
We have been using cvdupdate( [cvdupdate.py](https://github.com/Cisco-Talos/cvdupdate/blob/main/cvdupdate/cvdupdate.py)) as lambda service in AWS to download the required files into s3 bucket once per day.
Even though the frequency is once per day in all the environments(4) , we have been blocked by cloudflare.
We are also using the latest official docker image and using the S3 bucket as our hosted PrivateMirror.
We have confirmed from the logs that freshclam uses the S3  PrivateMirror we have hosted.

Please help on why we have been blocked , running 4 requests/day.

**Comment by finchy** [comment]
Can you give me the public IP you are hitting our IP space with?  Are you using the most up to date version of cvdupdate?

**Comment by gowdab** [comment]
These are public IP's that we connect to your domain and we are using the latest version of cvdupdate. The issue started from June 25th to be precise .Before June 25th we used to download all the three files main.cvd, daily.cvd and bytecode.cvd once per day.

      'dev' => '54.208.200.178/32'
      'qa' => '54.208.200.178/32'
      'stg2' => '3.18.21.66/32'
      'prod' => '107.21.6.134/32'

**Comment by finchy** [comment]
Your CVDUPDATE isn't giving us a version.  That's why you're being blocked.  Are you using the most up to date version of cvdupdate?

**Comment by gowdab** [comment]
we have made changes to use the latest version and it worked .
Thank you very much for the help!
