### ISSUE TITLE
INSTALL.md still refers to the no-longer-existent autotools build system

### ISSUE THREAD

**Issue by ryandesign** [Cisco-Talos/clamav#211]
INSTALL.md says in part:

> the Autotools build system will likely be removed in the near future

The autotools build system was removed in a746d344dff2449b3a70f6e2c6c5225327e1a3c8. The documentation should be updated to reflect that.

**Comment by micahsnyder** [comment]
Fixed in this update for the 0.104 RC: https://github.com/Cisco-Talos/clamav/pull/216

**Comment by micahsnyder** [comment]
(thanks for the heads up btw!)
