### ISSUE TITLE
Unit tests fail when building without unRAR support

### ISSUE THREAD

**Issue by arjendekorte** [Cisco-Talos/clamav#225]
When building without unRAR support by adding `-D ENABLE_UNRAR=OFF` to the cmake command line, one also has to set `-D ENABLE_TESTS=OFF`, otherwise the build will fail fairly quickly due to the following error:
```
Error evaluating generator expression:

  $<TARGET_FILE_DIR:ClamAV::libunrar_iface>

No target "ClamAV::libunrar_iface"
```
The resulting binaries run fine after build, so this seems to be a problem with the unit tests only.

**Comment by micahsnyder** [comment]
Fixed in rel/0.104 and main
