### ISSUE TITLE
clamd changing owner/permissions of /tmp

### ISSUE THREAD

**Issue by Leebre** [Cisco-Talos/clamav#235]
Hi, I am using clamav with Parabola (Arch Linux variant) and openrc. I have encountered what seems to be a bug with clamd. Whenever I start (or restart) clamd, it seems to be changing the owner/permissions of my /tmp folder to:

`drwxr-xr-x   6 clamav clamav  4096 Jul 27 11:23 tmp`

If I manually change the owner/permissions back to what they should be, i.e.:

`drwxrwxrwt   6 root root  4096 Jul 27 11:23 tmp`

then clamd will change it back the next time I start it.

I have tried changing the `TemporaryDirectory` setting in `clamd.conf` to `/tmp/clamav`, but the same issue still happens. This seems to be a bug, since it will clearly cause problems for other applications that need to use /tmp (however, I do not think it is a security issue).

My clamav version is 0.103.3, which I believe is the latest stable release version. Output of clamconf -n:

```
Config file: clamd.conf
-----------------------
AlertExceedsMax = "yes"
LogFile = "/var/log/clamav/clamd.log"
LogTime = "yes"
LogVerbose = "yes"
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
PidFile = "/run/clamav/clamd.pid"
TemporaryDirectory = "/tmp/clamav"
LocalSocket = "/tmp/clamd.socket"
LocalSocketMode = "660"
SelfCheck = "14400"
DetectPUA = "yes"
AlertBrokenExecutables = "yes"
AlertEncrypted = "yes"
AlertEncryptedArchive = "yes"
AlertEncryptedDoc = "yes"
MaxScanTime = "300000"
MaxScanSize = "4194304000"
MaxFileSize = "2097152000"
MaxEmbeddedPE = "524288000"
MaxZipTypeRcg = "524288000"

Config file: freshclam.conf
---------------------------
LogTime = "yes"
LogRotate = "yes"
PidFile = "/run/clamav/freshclam.pid"
UpdateLogFile = "/var/log/clamav/freshclam.log"
DatabaseMirror = "database.clamav.net"

Config file: clamav-milter.conf
-------------------------------
LogFile = "/var/log/clamav/clamav-milter.log"
LogTime = "yes"
PidFile = "/run/clamav/clamav-milter.pid"
TemporaryDirectory = "/tmp"
User = "clamav"

Software settings
-----------------
Version: 0.103.3
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON 

Database information
--------------------
Database directory: /var/lib/clamav
main.cvd: version 61, sigs: 6607162, built on Wed Jul 14 22:39:10 2021
bytecode.cvd: version 333, sigs: 92, built on Mon Mar  8 10:21:51 2021
daily.cld: version 26248, sigs: 1965045, built on Fri Jul 30 04:19:07 2021
Total number of signatures: 8572299

Platform information
--------------------
uname: Linux 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
Full OS version: "Parabola GNU/Linux-libre"
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x0a217c7c08000000000b0100

Build information
-----------------
GNU C: 11.1.0 (11.1.0)
CPPFLAGS: -D_FORTIFY_SOURCE=2
CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/build/clamav/src=/usr/src/debug  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/build/clamav/src=/usr/src/debug
LDFLAGS: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
Configure: '--prefix=/usr' '--sbindir=/usr/bin' '--sysconfdir=/etc/clamav' '--with-dbdir=/var/lib/clamav' '--with-user=clamav' '--with-group=clamav' '--with-system-libmspack' '--disable-rpath' '--disable-clamav' '--disable-llvm' '--enable-zlib-vcheck' '--enable-milter' '--enable-clamdtop' '--disable-unrar' '--enable-llvm=no' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/build/clamav/src=/usr/src/debug' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/build/clamav/src=/usr/src/debug'
sizeof(void*) = 8
Engine flevel: 124, dconf: 124
```

**Comment by micahsnyder** [comment]
Hi @Leebre I've never seen this behavior before. ClamD includes logic to change ownership of its PID files and log files, but never the scan temp directory. 
Would you be able to try installing ClamAV from source to see if a from-source version has the same issue?

**Comment by Leebre** [comment]
@micahsnyder thanks for your reply. Sure, I'll be happy to compile the current version from source and see if the problem repeats. It might take me a few days to find some time, but I will try it and report back. If I build it from this [AUR package](https://aur.archlinux.org/packages/clamav-git/), would that be ok? I think that should pull the latest version.

**Comment by micahsnyder** [comment]
If I'm honest, I was hoping you would try downloading (the source from our website](https://www.clamav.net/downloads/production/clamav-0.103.3.tar.gz) and using [these instructions](https://docs.clamav.net/manual/Installing/Installing-from-source-Unix-old.html). 

I'm not very familiar with AUR, but the linked AUR package references version 0.99 which is old enough that we block it from downloading databases. Of course, it also has updates for changes we made in 0.103 (autogen.sh), so I don't really know what I'm looking at. 😅

**Comment by Leebre** [comment]
Hi @micahsnyder . I just downloaded the source from the link you gave, compiled and installed. As before, as soon as I start the `clamd` service with OpenRC, it changes the ownership/permission of my top-level `/tmp` directory. It is possible the issue could be with the OpenRC init script (which is from a separate Arch package), so I will have a look at that in case and report back.

To build, I used the PKGBUILD from that AUR version, but modified it to download your tar archive and build the pacman package from there. I think that should be ok, I doubt there would be an issue with that.

**Comment by Leebre** [comment]
I had a quick look at the `clamav-openrc` package that I have. It contains two fairly short scripts and neither seems to contain the string '/tmp'. So, it seems unlikely the issue would be there?

**Comment by AlexanderS** [comment]
Are you using [this](https://aur.archlinux.org/cgit/aur.git/tree/clamd.initd?h=clamav-openrc) script from the `clamav-openrc` package? 

The issue might be these lines (line 36 and following):

```bash
checkpath --quiet --mode 755 \
	--owner "${clamd_user}":"${clamd_user}" \
	--directory `dirname ${clamd_socket}`
```

This will modify the permission of the directory containing the clamd.socket file. So this is a problem of the openrc Script and not a problem of clamav.

**Comment by micahsnyder** [comment]
Some of the other distributions place the socket file in a different directory, e.g. `LocalSocket /var/run/clamav/clamd.ctl`. I think it's a good option, and would resolve this problem.

**Comment by micahsnyder** [comment]
I think the socket directory is only ever configured in the clamd.conf file.

**Comment by Leebre** [comment]
@micahsnyder I made that change that you recommended to the socket location in `clamd.conf` and that has resolved the problem - the permissions for `/tmp` no longer change when starting clamd. `clamdscan` seems to be working fine from my user account too. I will double check the default config settings for clamav in my distribution and if it is using `/tmp` as the default location for the socket file, I will submit a bug report to them to suggest they change it. Otherwise, I think the issue is resolved. Thanks very much for your help with this, and @AlexanderS too! :-)

**Comment by micahsnyder** [comment]
Thanks @Leebre and thanks @AlexanderS, that's great news.
