### ISSUE TITLE
Broken Link to online documentation in README.md

### ISSUE THREAD

**Issue by A-Pisani** [Cisco-Talos/clamav#247]
The Issue
----------------
In the README.md file the link to step-by-step instructions for source build are broken:
- [Unix/Linux/Mac Instructions](Installing-from-source/Installing-from-source-Unix.md)
- [Windows Instructions](Installing-from-source/Installing-from-source-Windows.md)

They lead to a 404 GitHub page.

**Comment by micahsnyder** [comment]
Whoops!  Thanks for the tip.  Must've been a copy-paste from the clamav-documentation source, which of course wouldn't work 🤦‍♀️
