### ISSUE TITLE
Problem building 0.104.0-rc2 on rhel7 based system

### ISSUE THREAD

**Issue by bleve** [Cisco-Talos/clamav#258]
cmake reports this issue:

-- Could NOT find SYSTEMD (missing: SYSTEMD_INCLUDE_DIR) (found version "219")

And result is no service files gets installed.

Exactly same parameters for cmake works on rhel8 based system where there is newer systemd.

I guess check is for wrong file in /usr/include/systemd because older systemd has:

-rw-r--r--. 1 root root  2339 Feb  2  2021 _sd-common.h
-rw-r--r--. 1 root root 11440 Feb  2  2021 sd-daemon.h
-rw-r--r--. 1 root root  6466 Feb  2  2021 sd-id128.h
-rw-r--r--. 1 root root  7131 Feb  2  2021 sd-journal.h
-rw-r--r--. 1 root root  8842 Feb  2  2021 sd-login.h
-rw-r--r--. 1 root root  4908 Feb  2  2021 sd-messages.h

And newer systemd has:

-rw-r--r--. 1 root root 27224 Aug 10 15:21 sd-bus.h
-rw-r--r--. 1 root root  5074 Jun 22  2018 sd-bus-protocol.h
-rw-r--r--. 1 root root  7793 Jun 22  2018 sd-bus-vtable.h
-rw-r--r--. 1 root root 12927 Jun 22  2018 sd-daemon.h
-rw-r--r--. 1 root root  6976 Aug 10 15:22 sd-event.h
-rw-r--r--. 1 root root  6635 Jun 22  2018 sd-id128.h
-rw-r--r--. 1 root root  7779 Jun 22  2018 sd-journal.h
-rw-r--r--. 1 root root  9421 Jun 22  2018 sd-login.h
-rw-r--r--. 1 root root 12037 Aug 10 15:21 sd-messages.h
-rw-r--r--. 1 root root  2652 Jun 22  2018 _sd-common.h

**Comment by bleve** [comment]
find_path(SYSTEMD_INCLUDE_DIR
    NAMES systemd/sd-bus.h
    PATHS ${PC_SYSTEMD_INCLUDE_DIRS}
    PATH_SUFFIXES systemd
)

My guess was right. change sd-bus.h to sd-daemon.h to make things work....

**Comment by micahsnyder** [comment]
Nice find, thanks for the PR! I just confirmed this as well.  Will merge and cherry-pick it to the 0.104 release branch.
