### ISSUE TITLE
Change 403 instructions

### ISSUE THREAD

**Issue by finchy** [Cisco-Talos/clamav#268]
When FreshClam encounters a 403 From the CDN, we instruct them to go to bugzilla.clamav.net to open a bug.  We should instruct them to come here, and we’ll use an appropriate label, and assign them the bugs to me.

**Comment by micahsnyder** [comment]
@finchy this is already changed. See:
- `main`: https://github.com/Cisco-Talos/clamav/commit/d46832d5cf020ce9c0d093c87d8a3654d28cc913
- `dev/0.103.4`: https://github.com/Cisco-Talos/clamav/commit/f549c18083d971058c1d6fe615568cf3436858e7
