### ISSUE TITLE
clamdscan --allmatch option is sticky: all subsequent scans will be allmatch-mode

### ISSUE THREAD

**Issue by klingerko** [Cisco-Talos/clamav#276]
Describe the bug
----------------

I have two cdb rules in a single rule database cdb file. Both rules should fire with the allmatch option enabled, but only the chronological "last" rule of the rule file fires. Switching the order of the rules will lead to a different result. I'd expect both rules to fire with the allmatch function enabled.

How to reproduce the problem
----------------------------

```
$ cat test_1.cdb 
Rule1.Zip_vbs:CL_TYPE_ZIP:*:\.[Vv][Bb][Ss]$:*:*:*:*:*:*
Rule2.Zip_vbs:CL_TYPE_ZIP:*:^[a-zA-Z0-9]{12}\.[Vv][Bb][Ss]$:*:*:*:*:*:*
$ clamscan --allmatch=yes -d test_1.cdb 18c5335e8ea82d729cb931a02839bfd3f0cf070a53f7d1a886a1ee4daab64ecf.bin 
Loading:     0s, ETA:   0s [========================>]        2/2 sigs    
Compiling:   0s, ETA:   0s [========================>]       10/10 tasks 

/home/18c5335e8ea82d729cb931a02839bfd3f0cf070a53f7d1a886a1ee4daab64ecf.bin: Rule2.Zip_vbs.UNOFFICIAL FOUND
/home/18c5335e8ea82d729cb931a02839bfd3f0cf070a53f7d1a886a1ee4daab64ecf.bin: Rule2.Zip_vbs.UNOFFICIAL FOUND

----------- SCAN SUMMARY -----------
Known viruses: 2
Engine version: 0.104.0-rc2
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 0.47 MB
Data read: 0.46 MB (ratio 1.01:1)
Time: 0.010 sec (0 m 0 s)
Start Date: 2021:08:30 15:30:37
End Date:   2021:08:30 15:30:37
$ cat test_2.cdb 
Rule2.Zip_vbs:CL_TYPE_ZIP:*:^[a-zA-Z0-9]{12}\.[Vv][Bb][Ss]$:*:*:*:*:*:*
Rule1.Zip_vbs:CL_TYPE_ZIP:*:\.[Vv][Bb][Ss]$:*:*:*:*:*:*
$ clamscan --allmatch=yes -d test_2.cdb 18c5335e8ea82d729cb931a02839bfd3f0cf070a53f7d1a886a1ee4daab64ecf.bin 
Loading:     0s, ETA:   0s [========================>]        2/2 sigs    
Compiling:   0s, ETA:   0s [========================>]       10/10 tasks 

/home/18c5335e8ea82d729cb931a02839bfd3f0cf070a53f7d1a886a1ee4daab64ecf.bin: Rule1.Zip_vbs.UNOFFICIAL FOUND
/home/18c5335e8ea82d729cb931a02839bfd3f0cf070a53f7d1a886a1ee4daab64ecf.bin: Rule1.Zip_vbs.UNOFFICIAL FOUND

----------- SCAN SUMMARY -----------
Known viruses: 2
Engine version: 0.104.0-rc2
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 0.47 MB
Data read: 0.46 MB (ratio 1.01:1)
Time: 0.013 sec (0 m 0 s)
Start Date: 2021:08:30 15:31:10
End Date:   2021:08:30 15:31:10
```

Replace this text with the output from the ClamAV command:
```
Checking configuration files in /usr/local/etc

clamd.conf not found

freshclam.conf not found

clamav-milter.conf not found

Software settings
-----------------
Version: 0.104.0-rc2
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /usr/local/share/clamav
WARNING: freshclam.conf and clamd.conf point to different database directories
print_dbs: Can't open directory /usr/local/share/clamav

Platform information
--------------------
uname: Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
OS: Linux, ARCH: x86_64, CPU: x86_64
Full OS version: Debian GNU/Linux 10 (buster)
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x0a218c8c0800000000050400

Build information
-----------------
GNU C: 5.4.0 20160609 (5.4.0)
sizeof(void*) = 8
Engine flevel: 140, dconf: 140
```

Attachments
-----------
https://www.virustotal.com/gui/file/18c5335e8ea82d729cb931a02839bfd3f0cf070a53f7d1a886a1ee4daab64ecf/

**Comment by klingerko** [comment]
Also tested with 0.103.3 on Mac. Same behaviour as above. Please let me know if you need anything else from me.

**Comment by micahsnyder** [comment]
Thanks for the report. Sorry about the delay replying.  There are widespread issues with allmatch support as it's implemented haphazardly throughout the different file type scanners.  I have a plan to re-architect how allmatch works to make it less error prone and so I won't be trying to fix each individual issue one at a time. 

That is to say, I'm going to let this ticket sit idle until the whole thing is re-done. I hope to work on it after 0.105 is out, but we're still prioritizing tasks for the next release and I'm not making any promises.

**Comment by micahsnyder** [comment]
Hi Rob!

Thank you for evaluating the release candidate.

Unfortunately we didn't have time to work on this bug during 1.0 development.  As you've noticed, it's not really a problem with the allmatch feature. It is a bug in `clamd` where using `--allmatch` for one scan causes all subsequent scans to use all-match mode as well. 

I don't mean to say that it isn't a priority. We should definitely fix this. Sorry it's not fixed yet.  It may actually be a really simple fix -- I'll put the investigation in the sprint and if it's feasible, maaaybe we can get it in before the stable release. (no promises).

Respectfully,
Micah
