### ISSUE TITLE
 clamav/clamav:latest not found: manifest unknown

### ISSUE THREAD

**Issue by cocoonkid** [Cisco-Talos/clamav#278]
❯ docker pull clamav/clamav
Using default tag: latest
Error response from daemon: manifest for clamav/clamav:latest not found: manifest unknown: manifest unknown

**Comment by dylanjustice** [comment]
> ❯ docker pull clamav/clamav
> Using default tag: latest
> Error response from daemon: manifest for clamav/clamav:latest not found: manifest unknown: manifest unknown

@cocoonkid Ran into this as well. Lots of new tags up on docker hub as of today.

**Comment by micahsnyder** [comment]
This issue should be resolved.  We added a `latest` tag with the release of 0.104.

On my machine I get this:
```
❯ docker pull clamav/clamav
Using default tag: latest
latest: Pulling from clamav/clamav
a0d0a0d46f8b: Already exists
3f67d67725f7: Already exists
b7e89741dbc6: Already exists
a9e57bcf2015: Already exists
e654b98e97d9: Already exists
286cc84346a7: Pull complete
Digest: sha256:95fa843024541f17416005846b72d0b541acb77300a619a86ab9316dcafcbb7d
Status: Downloaded newer image for clamav/clamav:latest
docker.io/clamav/clamav:latest
```

**Comment by cocoonkid** [comment]
Great! Thanks so much!
