### ISSUE TITLE
DatabaseMirror param length control too short for long access_token  

### ISSUE THREAD

**Issue by heurtemattes** [Cisco-Talos/clamav#281]
Describe the bug
----------------

Using freshclam with a private and authenticated DatabaseMirror can't be possible if the authentication have an access_token too long, like something : https://user:my_long_access_token@mymirror.com

Limit rich around 498 char

# How to reproduce the problem

Freshclam.conf DatabaseMirror exemple : 

DatabaseMirror https://dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd

Result : 

ERROR: Missing argument for option at /etc/clamav/freshclam.conf:27
ERROR: Can't open/parse the config file /etc/clamav/freshclam.conf

with char-1 : 

ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
ERROR: initialize: libfreshclam init failed.
ERROR: Initialization error!

**Comment by micahsnyder** [comment]
This has to do with the maximum line length for any config line. That's 512 bytes.  We could bump it up pretty comfortably to 1024 or higher.  Making it support any line length would take a tiny bit more work.  

Do you have a minimum line line length for your use-case?

**Comment by heurtemattes** [comment]
@micahsnyder Would be grateful to have 1024, our token is around 850 char!
