### ISSUE TITLE
ClamAV 0.104.0 Win64 .msi package missing files

### ISSUE THREAD

**Issue by phrossignol** [Cisco-Talos/clamav#285]
Until previous version (0.103.3) the ClamAV installer could be downloaded in .exe executable file.
With version 0.104.0 a msi installer is available which contains only some files. 
What is the new installation procedure under Windows (64-bit) ?.
Many thanks for your help.

**Comment by micahsnyder** [comment]
Hi @phrossignol Thank you for reporting this issue. 

We perform our automated testing using the .zip install package and failed to notice a packaging issue with the .msi installer.  It appears that it's only installing the documentation, vc redistributable DLLs, config templates, news, and readme documents. 

Unfortunately your only right now will be to use the .zip package until we can repair the .msi package. You can find the .zip packages next to the .msi packages on https://www.clamav.net/downloads#otherversions

**Comment by phrossignol** [comment]
Hello,
When do you expect to repair the .msi packages ?.
Many thanks for your information.

**Comment by micahsnyder** [comment]
I forgot to update this.  We fixed this in 0.104.1
