### ISSUE TITLE
freshclam getting killed during an update

### ISSUE THREAD

**Issue by diegomanansala** [Cisco-Talos/clamav#299]
Describe the bug
----------------

I'm currently on clamav 0.103.2 since this is the stable version available for the docker image I'm using. I noticed that whenever freshclam would attempt to make an update, it would suddenly be killed without any error ID during the "Testing database" phase. The instance would create a new container, and the local database version would be reverted to the state it was at when the image was created. After this happens, the update would go through and then it would crash again when a new database version is detected.

Here are some of the log messages before it crashed if it helps:

daily database available for update (local version: 26294, remote version: 26297)
...
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:256
LibClamAV debug: hashtab.c: new capacity: 2048
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:512
LibClamAV debug: Table 0x7faf4553d948 size after grow:2048
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:1024
LibClamAV debug: Table 0x7faf4553d948 size after grow:1024
LibClamAV debug: hashtab.c: new capacity: 1024
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:2048
LibClamAV debug: hashtab.c: new capacity: 4096
LibClamAV debug: Table 0x7faf4553d948 size after grow:4096
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:4096
LibClamAV debug: Table 0x7faf4553d948 size after grow:8192
LibClamAV debug: hashtab.c: new capacity: 8192
LibClamAV debug: Table 0x7faf4553d948 size after grow:16384
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:8192
LibClamAV debug: hashtab.c: new capacity: 16384
LibClamAV debug: Table 0x7faf4553d948 size after grow:32768
LibClamAV debug: hashtab.c: new capacity: 32768
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:16384
LibClamAV debug: hashtab.c: new capacity: 65536
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:32768
LibClamAV debug: Table 0x7faf4553d948 size after grow:65536
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:65536
LibClamAV debug: hashtab.c: new capacity: 131072
LibClamAV debug: Table 0x7faf4553d948 size after grow:131072
LibClamAV debug: hashtab.c: new capacity: 262144
LibClamAV debug: hashtab.c:Growing hashtable 0x7faf4553d948, because it has exceeded maxfill, old size:131072
LibClamAV debug: Table 0x7faf4553d948 size after grow:262144
Killed

How to reproduce the problem
----------------------------

The problem is that I cannot replicate it in my local, and it only happens in the dev server.

**Comment by micahsnyder** [comment]
I suspect your system may be running out of RAM when `freshclam` tests the database. Does your system have adequate memory for `freshclam` to load the databases while `clamd` is running (with the databases also loaded)?

You disable database load testing to reduce RAM usage by setting `TestDatabases no` in `freshclam.conf`

**Comment by diegomanansala** [comment]
@micahsnyder Ah thanks for pointing that out! Let me try that out. I already suspected that it was a memory problem, but wasn't sure what to change. I also tried turning off `ConcurrentDatabaseReload`, but I still encountered the problem.

**Comment by micahsnyder** [comment]
Sounds good.  Let me know if `TestDatabases no` resolves the issue so I can close the ticket or so we can investigate further.

**Comment by micahsnyder** [comment]
@diegomanansala any update?

**Comment by diegomanansala** [comment]
Hello @micahsnyder! Sorry for the late reply. Unfortunately setting `TestDatabases no` did not work. In the end, I had to increase my memory allocation from 1.5gb to 3gb, and now it never crashes. Thank you for the help!

**Comment by micahsnyder** [comment]
Sure.  Glad to hear it's resolved.  Sorry that you had to increase the RAM size :(  I'm working with some others to try to figure how how to get the RAM requirements down.  🤞
