### ISSUE TITLE
Clamav failed to complete full update | downloadPatch: Can't download daily-26294.cdiff from https://database.clamav.net/daily-26294.cdiff Downloaded 6 patches for daily, which is fewer than the 13 expected patches.

### ISSUE THREAD

**Issue by rsramkis** [Cisco-Talos/clamav#300]
When running the Clamav virus definitions update via terminal "sudo freshclam" I have been getting the follow output which indicates I am only get 6 of the expected 13 files. I tried to run Freshclam over a couple of days and still I get the below error.

I am using clamav 0.104.0-1 on Arch Linux (last updated on 09/09/2021).

**Output from running sudo freshclam:**

```
❯ sudo freshclam
[sudo] password for
ClamAV update process started at Wed Sep 22 09:08:58 2021
daily database available for update (local version: 26287, remote version: 26300)
Current database is 13 versions behind.
Downloading database patch # 26288...
Time:    0.3s, ETA:    0.0s [========================>]   18.31KiB/18.31KiB
Downloading database patch # 26289...
Time:    0.5s, ETA:    0.0s [========================>]   15.17KiB/15.17KiB
Downloading database patch # 26290...
Time:    0.1s, ETA:    0.0s [========================>]   21.13KiB/21.13KiB
Downloading database patch # 26291...
Time:    0.1s, ETA:    0.0s [========================>]   17.73KiB/17.73KiB
Downloading database patch # 26292...
Time:    0.1s, ETA:    0.0s [========================>]   22.50KiB/22.50KiB
Downloading database patch # 26293...
Time:    0.1s, ETA:    0.0s [========================>]   18.05KiB/18.05KiB
Downloading database patch # 26294...
Time:    0.1s, ETA:    0.0s [========================>]        16B/16B
WARNING: downloadPatch: Can't download daily-26294.cdiff from https://database.clamav.net/daily-26294.cdiff
Downloaded 6 patches for daily, which is fewer than the 13 expected patches.
We'll settle for this partial-update, at least for now.
Testing database: '/var/lib/clamav/tmp.aebadaeba0/clamav-0035465b39182c37f19e3a08440c591f.tmp-daily.cld' ...
[LibClamAV] **************************************************
[LibClamAV] ***  The virus database is older than 7 days!  ***
[LibClamAV] ***   Please update it as soon as possible.    ***
[LibClamAV] **************************************************
Database test passed.
daily.cld updated (version: 26293, sigs: 1972500, f-level: 90, builder: raynman)
main database available for update (local version: 61, remote version: 62)
Current database is 1 version behind.
Downloading database patch # 62...
Time:    0.1s, ETA:    0.0s [========================>]        16B/16B
WARNING: downloadPatch: Can't download main-62.cdiff from https://database.clamav.net/main-62.cdiff
The database server doesn't have the latest patch for the main database (version 62). The server will likely have updated if you check again in a few hours.
bytecode.cvd database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)
WARNING: Clamd was NOT notified: Can't connect to clamd through /run/clamav/clamd.ctl: No such file or directory
```

**Comment by rsramkis** [comment]
This is the  listing in the /var/lib/clamav:

```
/var/lib/clamav🔒
❯ ls -al
total 343788
drwxr-xr-x  2 clamav clamav      4096 Sep 22 09:09 .
drwxr-xr-x 41 root   root        4096 Sep 17 00:00 ..
-rw-r--r--  1 clamav clamav    293670 Jul 16 13:52 bytecode.cvd
-rw-r--r--  1 clamav clamav 183519744 Sep 22 09:09 daily.cld
-rw-r--r--  1 clamav clamav        69 Jul 16 13:50 freshclam.dat
-rw-r--r--  1 clamav clamav 168205379 Jul 16 13:52 main.cvd
```

**Comment by micahsnyder** [comment]
Hi @rsramkis  sorry about the delay.  I'm investigating this now.  I observed something similar with a different cdiff file (but only when connected to our VPN and not when disconnected). I am forwarding this investigation to our Cloudflare account admins to find out if they know why it might not be serving up all files for all geographic regions.

**Comment by finchy** [comment]
What is the IP that you are coming from @rsramkis

**Comment by rsramkis** [comment]
@finchy @micahsnyder 

At the time my IP Address was in the range of 104.234.81.X, which is from my internet service provider.

**Comment by finchy** [comment]
I either need an exact IP or the RayID for the block. (RayID is displayed in the response back from cloudflare).

**Comment by rsramkis** [comment]
Hi Finchy

For privacy reasons I can't disclose my full IP Address. If your cloud service is rejecting the request from my IP range then that should show in your configuration and logs. Keep in mind that they issue was happen for a couple weeks.

Below is what I am getting as of 9/28/2021 at 5:09 pm EST.
```
sudo freshclam
ClamAV update process started at Tue Sep 28 17:09:15 2021
daily.cld database is up-to-date (version: 26306, sigs: 1936902, f-level: 90, builder: raynman)
main.cld database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode.cvd database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)
```

So if the version information is correct then I'm not sure if I can help you trace it.

```
/var/lib/clamav🔒
❯ ls -al
total 644324
drwxr-xr-x  2 clamav clamav      4096 Sep 28 17:09 .
drwxr-xr-x 42 root   root        4096 Sep 26 00:00 ..
-rw-r--r--  1 clamav clamav    293670 Jul 16 13:52 bytecode.cvd
-rw-r--r--  1 clamav clamav 176641024 Sep 28 16:27 daily.cld
-rw-r--r--  1 clamav clamav        69 Jul 16 13:50 freshclam.dat
-rw-r--r--  1 clamav clamav 464053248 Sep 22 11:05 main.cld
```

**Comment by micahsnyder** [comment]
> Below is what I am getting as of 9/28/2021 at 5:09 pm EST.

It looks like you're up to date now. 👍

I think what happened in your initial report is that your `freshclam` client was rate limited when downloading `daily-26294.cdiff` and `main-62.cdiff`. While we may not be able to find the exact incident in the logs to confirm, I was able to reproduce a similar failure on my end with a different cdiff file.  I will try to work with @finchy to figure out what to do.

**Comment by finchy** [comment]
> For privacy reasons I can't disclose my full IP Address. If your cloud service is rejecting the request from my IP range then that should show in your configuration and logs. Keep in mind that they issue was happen for a couple weeks.

Unfortunately that's not the way our system works.  As I said, if you can't provide your public IP that the world can see, you can provide the RayID.  But it looks like you're good to go.

**Comment by rsramkis** [comment]
> > For privacy reasons I can't disclose my full IP Address. If your cloud service is rejecting the request from my IP range then that should show in your configuration and logs. Keep in mind that they issue was happen for a couple weeks.
> 
> Unfortunately that's not the way our system works. As I said, if you can't provide your public IP that the world can see, you can provide the RayID. But it looks like you're good to go.

Thanks for your feedback. Slight correction here. The world does not all see your IP (this is a generalization). I don't provide my full IP so information about my systems are not easily aggregated on open platforms (as I participate on other open source platforms). I posted what I saw in cooperation with your organization including provided a partial IP and logs. There was no need for you to be snarky and rude. Alls it does is discourage people to not report issues.
