### ISSUE TITLE
clamsubmit: confusing and unhelpful error message when missing required commandline options

### ISSUE THREAD

**Issue by debian-user-france1** [Cisco-Talos/clamav#304]
Just try this:

clamsubmit -e EMAIL -n FILE-PATH

And it will say that itbis nessecary to specify -n or -p (And pass in - as the filename for stdin)

So I can't submit a virus

**Comment by micahsnyder** [comment]
`clamsubmit`'s error message is definitely not helpful.  It is failing because you must also specify `-N "your name"`. 

E.e.
```bash
clamsubmit -e "your.email@example.com" -N "Your Name" -n /path/to/file
```

You can also report a false negative on our website: https://www.clamav.net/reports/malware

**Comment by debian-user-france1** [comment]
Oh I'm stupid lol

I just thaught there must be a bug and smh I didn't see it
Sorry for wasting time :/

**Comment by debian-user-france1** [comment]
Then Authenticity token element not found. What's that ??

**Comment by micahsnyder** [comment]
Clamsubmit is broken in version 0.103.2 and prior because of a change cloudflare made. It should work in 0.103.3 and 0.104.

**Comment by debian-user-france1** [comment]
Ok thanks. I reported the Virus through the Browser (had to go to my phone)

I hope the Ubuntu Repo gets updated but yk - Ubuntu is bad, zero updates
