### ISSUE TITLE
Manual Download of Virus database

### ISSUE THREAD

**Issue by StBlade** [Cisco-Talos/clamav#313]
I have a QNAP NAS that makes use of ClamAV.  This NAS has problems updating from the online repository.  Doing a manual update gets you blocked from CloudFlare.  Not sure how to get a manual download of the AV database.

![image](https://user-images.githubusercontent.com/91721889/135582353-812657e4-396a-4213-b5a3-b39a6b242d07.png)

**Comment by micahsnyder** [comment]
We no longer allow manual downloads using a browser or other tools like curl/wget/etc because these tools download the whole files every time, even if there hasn't been a change to the database.  Serving the databases is expensive and we are trying to reduce data costs.

Please use the `freshclam` tool that comes with ClamAV to maintain a copy of the latest databases on your computer. ClamAV is available on Linux, Mac, and Windows. You can then copy from there to your NAS as needed if you're not able to run `freshclam` on the NAS directly.  

https://docs.clamav.net/faq/faq-cvd.html#can-i-download-the-virus-database-manually

**Comment by dirtyharrycallahan** [comment]
Or the Python cvdupdate package. It works well for us.

**Comment by micahsnyder** [comment]
Both of `cvdupdate` and `freshclam` resolve the "_download the whole files every time, even if there hasn't been a change to the database_"-problem.

But only `freshclam` eliminates the need to download the larger `.cvd` database archive after the first update.

`cvdupdate` was created for users that need to host a private mirror. It will download `daily.cvd`, `main.cvd`, or `bytecode.cvd` whenever there is a new version in addition to the smaller `*.cdiff` patch file.  `cvdupdate` is therefore still a bit of a data hog. 

`daily.cvd` is now 54MB, and `main.cvd` is up to 163MB. By contrast, most `.cdiff` files for the `daily` database are between 10-30K.  So the whole `daily.cvd` download is ~2750x larger than your average `daily-#.cdiff` file 😲. This is why I recommend using `freshclam`.

`freshclam` will only download the `*.cdiff` files after you get your first copy of the `.cvd` files, except if there is a large enough change to the databases such that we only issue a new `.cvd` file and don't issue a `.cdiff` patch (very rare).  `freshclam` applies each `.cdiff` patch to your existing `.cvd` *or `.cld`) database archive to create an updated `.cld` database archive.

**Comment by mithusingh32** [comment]
Sorry to revive this, but what about systems that are completely are offline and can never touch the internet or have access to external systems that have access to the internet. 

Would this mean ClamAV should not be used, and alternative AVs should be looked at?

**Comment by finchy** [comment]
Some computer, somewhere on your network has internet connectivity.  You can set it up there and move the files. Just as you do now.

**Comment by BatmanJMF** [comment]
Hello,
I have a DS 412+ and I can no longer update the Essential antivirus. I have to manually download the databases and then install them on my NAS via a script. I wanted to know if it's possible to download the ClamAV databases using Docker?

Thank you

**Comment by finchy** [comment]
@BatmanJMF you're commenting on a closed issue, but yes, please check out https://github.com/Cisco-Talos/cvdupdate
