### ISSUE TITLE
ALLMATCHES is set for all consecutive scans 

### ISSUE THREAD

**Issue by eriklax** [Cisco-Talos/clamav#319]
It appears that the CL_SCAN_GENERAL_ALLMATCHES flag is set for all consecutive scans. Affecting the second call to MULTISCAN.

```
printf "zMULTISCAN /test.eml\0" | nc -U /tmp/clamd.socket
printf "zALLMATCHSCAN /test.eml\0" | nc -U /tmp/clamd.socket
printf "zMULTISCAN /test.eml\0" | nc -U /tmp/clamd.socket
```

https://github.com/Cisco-Talos/clamav/blob/10260c77b3162b5dafbf4221e22437f52b053b54/clamd/session.c#L352-L361

While there, would it make sense to add a "ALLINSTREAM" option (feature request) for remote scanning of files.

**Comment by micahsnyder** [comment]
I just realized this issue is a duplicate of https://github.com/Cisco-Talos/clamav/issues/276

Going to close so we can track it there.
