### ISSUE TITLE
Update failed. Your network may be down or none of the mirrors listed in /etc/freshclam.conf is working. Check http://www.clamav.net/doc/mirrors-faq.html for possible reasons.

### ISSUE THREAD

**Issue by brydzysta** [Cisco-Talos/clamav#346]
**I have been receiving messages on several of my servers for several days
there is communication with the clamv server
everything worked fine so far** 

[root@saturn ~]# host db.pl.clamav.net
db.pl.clamav.net is an alias for db.pl.clamav.net.cdn.cloudflare.net.
db.pl.clamav.net.cdn.cloudflare.net has address 104.16.218.84
db.pl.clamav.net.cdn.cloudflare.net has address 104.16.219.84
db.pl.clamav.net.cdn.cloudflare.net has IPv6 address 2606:4700::6810:db54
db.pl.clamav.net.cdn.cloudflare.net has IPv6 address 2606:4700::6810:da54

[root@saturn~]# host database.clamav.net
database.clamav.net is an alias for database.clamav.net.cdn.cloudflare.net.
database.clamav.net.cdn.cloudflare.net has address 104.16.219.84
database.clamav.net.cdn.cloudflare.net has address 104.16.218.84
database.clamav.net.cdn.cloudflare.net has IPv6 address 2606:4700::6810:da54
database.clamav.net.cdn.cloudflare.net has IPv6 address 2606:4700::6810:db54

--------------------------------------------------------------------------------

ClamAV update process started at Mon Nov  1 10:11:57 2021
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.3
DON'T PANIC! Read http://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.pl.clamav.net (IP: 2606:4700::6810:db54)
Trying host db.pl.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.pl.clamav.net (IP: 2606:4700::6810:da54)
WARNING: Can't download main.cvd from db.pl.clamav.net
Trying again in 5 secs...
ClamAV update process started at Mon Nov  1 10:12:08 2021
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.3
DON'T PANIC! Read http://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
Trying host db.pl.clamav.net (2606:4700::6810:db54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.pl.clamav.net (IP: 2606:4700::6810:db54)
Trying host db.pl.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.pl.clamav.net (IP: 2606:4700::6810:da54)
WARNING: Can't download main.cvd from db.pl.clamav.net
Trying again in 5 secs...
ClamAV update process started at Mon Nov  1 10:12:18 2021
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.3
DON'T PANIC! Read http://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
ERROR: getpatch: Can't download main-60.cdiff from db.pl.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
Trying host db.pl.clamav.net (2606:4700::6810:db54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.pl.clamav.net (IP: 2606:4700::6810:db54)
Trying host db.pl.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.pl.clamav.net (IP: 2606:4700::6810:da54)
ERROR: Can't download main.cvd from db.pl.clamav.net
Giving up on db.pl.clamav.net...
ClamAV update process started at Mon Nov  1 10:12:21 2021
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.3 Recommended version: 0.103.3
DON'T PANIC! Read http://www.clamav.net/documents/upgrading-clamav
WARNING: getpatch: Can't download main-60.cdiff from db.local.clamav.net
WARNING: getpatch: Can't download main-60.cdiff from db.local.clamav.net
ERROR: getpatch: Can't download main-60.cdiff from db.local.clamav.net
WARNING: Incremental update failed, trying to download main.cvd
Trying host db.local.clamav.net (2606:4700::6810:db54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.local.clamav.net (IP: 2606:4700::6810:db54)
Trying host db.local.clamav.net (2606:4700::6810:da54)...
nonblock_connect: connect(): fd=5 errno=101: Network is unreachable
Can't connect to port 80 of host db.local.clamav.net (IP: 2606:4700::6810:da54)
ERROR: Can't download main.cvd from db.local.clamav.net
Giving up on db.local.clamav.net...
Update failed. Your network may be down or none of the mirrors listed in /etc/freshclam.conf is working. Check http://www.clamav.net/doc/mirrors-faq.html for possible reasons.

**Comment by micahsnyder** [comment]
@brydzysta the issue you're having is that you're still using ClamAV 0.100 which exceeded end of life late last week and is now actively blocked from receiving updates. Curl is also blocked to prevent download abuse (downloading when there is no new database update). You will need to update to a newer version of clamav to continue receiving free databases updates.

See blog.clamav.net/2021/10/clamav-0100-end-of-life-today-and.html for more details.

**Comment by brydzysta** [comment]
thanks I didn't know
and written so as not to panic ;)
