### ISSUE TITLE
DESTDIR bug in freshclam/CMakeLists.txt

### ISSUE THREAD

**Issue by toddr** [Cisco-Talos/clamav#350]
Describe the bug
----------------

cmake install fails when using DESTDIR

How to reproduce the problem
----------------------------

When you run:
```
/usr/bin/cmake3 -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/my/prefix
DESTDIR=$(BUILD_ROOT) /usr/bin/cmake --build . -- install
```
You can get the following error:
```
CMake Error at freshclam/cmake_install.cmake:61 (FILE):
    FILE problem creating directory: /my/prefix
```

The error appears to be that the rendered text in `freshclam/cmake_install.cmake` is:
```
  FILE(MAKE_DIRECTORY ${ENV}${CMAKE_INSTALL_PREFIX}/${DATABASE_DIRECTORY})
```
When it should be:
```
  FILE(MAKE_DIRECTORY $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/${DATABASE_DIRECTORY})
```

I assume this is because of this line in `CMakeLists.txt` but given the rendered file autopopulates `DESTDIR` in all of the other places, I'm not sure what the right fix is:
```
INSTALL(CODE "FILE(MAKE_DIRECTORY \${ENV}\${CMAKE_INSTALL_PREFIX}/\${DATABASE_DIRECTORY})" COMPONENT programs)
```

**Comment by micahsnyder** [comment]
I haven't reproduced this issue but it sort of makes sense to me that there may be a problem here. 

For reference, `DESTDIR` is a CMake environment variable you can use to build as thought you're installing to: 
   `${CMAKE_INSTALL_PREFIX}`,
but actually install to: 
   `${DESTDIR}/${CMAKE_INSTALL_PREFIX}`

See https://cmake.org/cmake/help/latest/envvar/DESTDIR.html

**Comment by toddr** [comment]
> I haven't reproduced this issue 
Fair enough. I can only produce this in a debian fakeroot build environment.

```diff
 -INSTALL(CODE "FILE(MAKE_DIRECTORY \${ENV}\${CMAKE_INSTALL_PREFIX}/\${DATABASE_DIRECTORY})" COMPONENT programs)
-+INSTALL(CODE "FILE(MAKE_DIRECTORY \$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/\${DATABASE_DIRECTORY})" COMPONENT programs)
++INSTALL(CODE "FILE(MAKE_DIRECTORY \${DESTDIR}\${CMAKE_INSTALL_PREFIX}/\${DATABASE_DIRECTORY})" COMPONENT programs)
```

I attempted `${DESTDIR}` and it did not work. `$ENV{DESTDIR}` works for me. Could it be the backslash?

**Comment by ragusaa** [comment]
I am able to install to DESTDIR using 
mkdir build && cd build && cmake -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=<install prefix> && make DESTDIR=<destdir>  install
