### ISSUE TITLE
[Doc] Wrong MaxScanTime default value

### ISSUE THREAD

**Issue by SecT0uch** [Cisco-Talos/clamav#356]
I think I spotted a little mistake here:
https://github.com/Cisco-Talos/clamav/blob/78f99bef34784d15e60a4b4a384dacdd2e22a1e6/docs/man/clamd.conf.5.in#L544

Shouldn't it be 120000, as the [blog post says](https://blog.clamav.net/2019/08/clamav-01014-security-patch-release-has.html) ?

**Comment by micahsnyder** [comment]
Oops!  Yes it should.  Would you like to submit a PR to fix this for the git commit credit?  If not, I can make the change.

**Comment by SecT0uch** [comment]
PR Open :)

**Comment by micahsnyder** [comment]
Thanks again @SecT0uch
