### ISSUE TITLE
0.104.1 fails to detect curses on FreeBSD 13 or earlier

### ISSUE THREAD

**Issue by yasuhirokimura** [Cisco-Talos/clamav#358]
I'm maintainer of FreeBSD ClamAV port. While updating FreeBSD ClamAV port from 0.104.0 to 0.104.1 I found the problem that curses isn't detected on FreeBSD 13 or earlier.

```
-- The C compiler identification is Clang 11.0.1
-- The CXX compiler identification is Clang 11.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1k")  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found LibXml2: /usr/local/lib/libxml2.so (found version "2.9.12") 
-- Found PCRE2: /usr/local/lib/libpcre2-8.so  
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Found Iconv: /usr/lib/libc.so  
-- Found JSONC: /usr/local/lib/libjson-c.so  
-- Found CURL: /usr/local/lib/libcurl.so (found version "7.79.1")  
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CURSES (missing: CURSES_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCURSES.cmake:65 (find_package_handle_standard_args)
  CMakeLists.txt:490 (find_package)
```

I checked commit messages of `rel/0.104` branch and found following commit.

> commit e45596f70
> Author: Luca Barbato <luca.barbato@gmail.com>
> Date:   Sat Oct 30 06:53:16 2021
> 
>     CMake: Fix FindCurses.cmake issue when tinfo is separate library
>     
>     Use all the link line from ncurses pkg-config.
>     Otherwise it would fail at link time if ncurses has a stand alone tinfo library.

If I revert this commit, then curses is successfully detected.

All supported versions of FreeBSD have ncurses library in their base system and FreeBSD ClamAV port uses it to build ClamAV. However, while FreeBSD 14 also has .pc files for ncurses in its base system, FreeBSD 13 or earlier don't have it. And this seems to result in failure to detect curses on FreeBSD 13 or earlier.

**Comment by micahsnyder** [comment]
OpenBSD raised the same complaint.  I guess the `.pc` files aren't present for all versions of ncurses or curses.  It sounds like we need it to try the old way if using pkg-config did not work.

For now you may be able use these options (or something similar) to hardcode the curses include and lib paths:
```
            -D NCURSES_INCLUDE_DIR="/usr/local/include/ncurses"       \
            -D CURSES_LIBRARY="/usr/local/lib/libncurses.so"           \
```

**Comment by micahsnyder** [comment]
For reference: https://github.com/Cisco-Talos/clamav/pull/331#issuecomment-960240395

**Comment by sthen** [comment]
It needs the full path to library, so for OpenBSD that's currently "-D CURSES_LIBRARY=/usr/lib/libncurses.so.14.0 " (the header is detected anyway so no need to provide INCLUDE_DIR). For the OpenBSD port I added a patch to backout the commit as a lower-maintenance approach (we don't have an automated way to keep the version number in sync).

Is this approach any good? It works OK on OpenBSD.

```
Index: cmake/FindCURSES.cmake
--- cmake/FindCURSES.cmake.orig
+++ cmake/FindCURSES.cmake
@@ -58,8 +58,14 @@ if(NCURSES_NOT_FOUND EQUAL -1)
     set(HAVE_LIBNCURSES 1)
     set(CURSES_INCLUDE "<ncurses.h>")
 
-    set(CURSES_LIBRARY ${PC_NCurses_LINK_LIBRARIES})
-    set(CURSES_VERSION ${PC_NCurses_VERSION})
+    if (DEFINED PC_NCurses_LINK_LIBRARIES)
+	set(CURSES_LIBRARY ${PC_NCurses_LINK_LIBRARIES})
+    else()
+        find_library(CURSES_LIBRARY
+            NAMES ncurses
+            PATHS ${PC_NCurses_LIBRARY_DIRS}
+        )
+    endif()
 
     include(FindPackageHandleStandardArgs)
     find_package_handle_standard_args(CURSES
```

**Comment by yasuhirokimura** [comment]
@sthen I confirmed your patch works fine with all supported FreeBSD versions.

**Comment by micahsnyder** [comment]
@sthen your patch looks good to me!  Would you like to submit it as a PR so you get the commit credit? Else I can do it and just put your name in the News doc for the next patch version.

Btw, next patch release is planned for mid-January.

**Comment by sthen** [comment]
Please go ahead and commit if that's OK with you, it will save me
remembering how to use git :)

**Comment by micahsnyder** [comment]
Here's the PR: https://github.com/Cisco-Talos/clamav/pull/364
