### ISSUE TITLE
Docker container missed to expose port and health check

### ISSUE THREAD

**Issue by sammyhk** [Cisco-Talos/clamav#368]
Describe the bug
----------------
This is using multi-stage docker build, while the port and health check info incorrectly placed in immediate stage of the build instead of in the final build.
https://github.com/Cisco-Talos/clamav/blob/b5e4d953738ad8c804f297653369ba2b458d126e/Dockerfile#L11-L14

How to reproduce the problem
----------------------------
Running docker image, do not see any health check occurred.

Recommended Fix
-----------
Place those statement to the final stage of the build.

**Comment by mko-x** [comment]
Fixed by https://github.com/Cisco-Talos/clamav/commit/37a68c2ff0f47c7a4ad09bd0bf1ee3af90e07e6d#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

**Comment by micahsnyder** [comment]
For reference: https://github.com/Cisco-Talos/clamav/pull/369

But this reminds me we should probably backport this for 0.104

**Comment by micahsnyder** [comment]
Merged the backport (0.104) PR for inclusion in 0.104.3
