### ISSUE TITLE
Freshclam on windows SSL peer certificate or SSH remote key not found

### ISSUE THREAD

**Issue by clamavuser** [Cisco-Talos/clamav#404]
Describe the bug
----------------

When running freshclam against database.clamav.net for daily.cvd, the error is reported : SSL peer certificate or SSH remote key not found

How to reproduce the problem
----------------------------

execute freshclam.exe on windows

Checking configuration files in D:\ClamAV

Config file: clamd.conf
-----------------------
LogFile = "D:\ClamAV\logs\clamd.txt"
LogFileMaxSize = "5242880"
LogTime = "yes"
LogClean = "yes"
LogRotate = "yes"
DatabaseDirectory = "D:\ClamAV\database\"
TCPSocket = "3310"
MaxConnectionQueueLength = "20000"
MaxThreads = "100"
ReadTimeout = "10"
CommandReadTimeout = "5"
SendBufTimeout = "200"
MaxQueue = "200"
IdleTimeout = "5"
CrossFilesystems disabled
SelfCheck = "10000"
ExitOnOOM = "yes"

Config file: freshclam.conf
---------------------------
LogTime = "yes"
LogRotate = "yes"
UpdateLogFile = "D:\ClamAV\logs\freshclam.txt"
Checks = "24"
DatabaseMirror = "db.us.clamav.net"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.104.1
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 JSON RAR 

Database information
--------------------
Database directory: D:\ClamAV\database
WARNING: freshclam.conf and clamd.conf point to different database directories
Total number of signatures: 0

Platform information
--------------------
uname: Microsoft Windows Server 6.2 SP0.0 Build 9200 
OS: Windows, ARCH: AMD64, CPU: AMD64
zlib version: 1.2.11 (1.2.11), compile flags: 65
platform id: 0x10058d8d080000000000077c

Build information
-----------------
Microsoft Visual C++: (0.7.124)
sizeof(void*) = 8
Engine flevel: 141, dconf: 141

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by clamavuser** [comment]
I imported the certs to my machine and it now works.  Just a temp solution until they expire/get renewed but it works. Thanks!

**Comment by micahsnyder** [comment]
That's great to hear!
