### ISSUE TITLE
`freshclam --datadir=.` fails to build CLD for incremental update

### ISSUE THREAD

**Issue by rkm-github** [Cisco-Talos/clamav#407]
Describe the bug
----------------

I am runnung freshclam to obtain my first set of data files for clamscan. My clamscan installation is entirely under my un-privileged account. Here is the output:

ClamAV update process started at Mon Dec 27 11:20:18 2021
daily database available for download (remote version: 26404)
Time:    8.7s, ETA:    0.0s [========================>]   54.32MiB/54.32MiB
Testing database: './tmp.6a544870f6/clamav-ad3a45bba75657890517a7cf2e60987c.tmp-daily.cvd' ...
Database test passed.
daily.cvd updated (version: 26403, sigs: 1953932, f-level: 90, builder: raynman)
Received an older daily CVD than was advertised. We'll retry so the incremental update will ensure we're up-to-date.
daily database available for update (local version: 26403, remote version: 26404)
Current database is 1 version behind.
Downloading database patch # 26404...
Time:    1.2s, ETA:    0.0s [========================>]   12.81KiB/12.81KiB
ERROR: buildcld: Can't open ./tmp.6a544870f6/clamav-2dfd7a162de6efab0ff1caf06de97318.tmp for writing
ERROR: updatedb: Incremental update failed. Failed to build CLD.
ERROR: Unexpected error when attempting to update daily: Failed to update database
ERROR: Database update process failed: Failed to update database
ERROR: Update failed.

I don't understand why freshclam needs to update daily.cvd, since I didn't have any data files to start with. I also don't understand why it can't open a file under the ./tmp directory, since I am the owner of the installation. I don't know if this is a bug, or if I am doing something wrong.
Thanks for any suggestions

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
Some clamav packages come with a copy of the databases. When you run `freshclam`, it will update those to the latest versions.  It sounds like the user running `freshclam` does not have write-access to the database directory.  It is likely that you must run `sudo freshclam` instead.

**Comment by rkm-github** [comment]
Thanks for your help. Unfortunately that is not the problem. I have run sudo freshclam and I have also run freshclam as root, in both cases I get exactly the same error. Also, as I mentioned, my user id is the owner (set in freshclam.conf) and I also installed clamav using the same id, so I have write access to the data file directory (I checked and that is the case).
Here is the output from another run, where I have re-built the source to include two printouts at the point where the error occurs (identified by ***):

rkm:~/clamav/share$ /home/rkm/clamav/bin/freshclam --datadir=.
ClamAV update process started at Sun Jan  2 11:06:21 2022
daily database available for update (local version: 26408, remote version: 26410)
Current database is 2 versions behind.
Downloading database patch # 26409...
Time:    0.9s, ETA:    0.0s [========================>]  108.62KiB/108.62KiB
Downloading database patch # 26410...
Time:    0.1s, ETA:    0.0s [========================>]   68.99KiB/68.99KiB
ERROR: buildcld: Can't open ./tmp.fe58ec25df/clamav-1fe8a2149c35f515fd027a2163073508.tmp for writing
ERROR: tmpdir is ./tmp.fe58ec25df/clamav-17b1a9d7dab102621478a9988756c2ea.tmp ***
ERROR: errno = 2 ***
ERROR: updatedb: Incremental update failed. Failed to build CLD.
ERROR: Unexpected error when attempting to update daily: Failed to update database
ERROR: Database update process failed: Failed to update database
ERROR: Update failed.

I believe errno=2 means that freshclam can't open a file or directory.
I think tmpdir is the present directory, because there was a chdir(tmpdir) in the same function, but tmpdir looks to me like a file name rather than a directory name. But if it is a directory, I can see why freshclam can't open the file above for writing, since it is not in the proper present directory. I admit I don't understand the program, but I am guessing that somehow the proper directory name for tmpdir is not passed to the function bldcld.
By the way, if I happen to run freshclam when the data files are up-to-date and no updates are required, freshclam completes without error.

**Comment by micahsnyder** [comment]
Ah I missed this from your original message:
> My clamscan installation is entirely under my un-privileged account

I see the issue now that you provided the commands you're using.  You're using the `--datadir=.` option.  
It looks like we have a bug with the `--datadir` option fails for incremental updates.

I was able to reproduce this issue on my machine like this:
```
❯ ~/clams/0.104.1/bin/freshclam --datadir=.
ClamAV update process started at Fri Jan  7 12:27:26 2022
daily database available for update (local version: 26411, remote version: 26415)
Current database is 4 versions behind.
Downloading database patch # 26412...
Time:    0.0s, ETA:    0.0s [========================>]   22.26KiB/22.26KiB
Downloading database patch # 26413...
Time:    0.0s, ETA:    0.0s [========================>]   29.38KiB/29.38KiB
Downloading database patch # 26414...
Time:    0.0s, ETA:    0.0s [========================>]   22.23KiB/22.23KiB
Downloading database patch # 26415...
Time:    0.0s, ETA:    0.0s [========================>]   23.73KiB/23.73KiB
ERROR: buildcld: Can't open ./tmp.b2b475533d/clamav-1acbe3256aaedfd60362a05974ae0fe7.tmp for writing
ERROR: updatedb: Incremental update failed. Failed to build CLD.
ERROR: Unexpected error when attempting to update daily: Failed to update database
ERROR: Database update process failed: Failed to update database
ERROR: Update failed.
```

I tried setting the database directory using `freshclam.conf` instead, adding this line:
```
DatabaseDirectory /home/micasnyd/blah
```

That worked fine:
```
❯ ~/clams/0.104.1/bin/freshclam
ClamAV update process started at Fri Jan  7 12:30:52 2022
daily database available for update (local version: 26411, remote version: 26415)
Current database is 4 versions behind.
Downloading database patch # 26412...
Time:    0.0s, ETA:    0.0s [========================>]   22.26KiB/22.26KiB
Downloading database patch # 26413...
Time:    0.0s, ETA:    0.0s [========================>]   29.38KiB/29.38KiB
Downloading database patch # 26414...
Time:    0.0s, ETA:    0.0s [========================>]   22.23KiB/22.23KiB
Downloading database patch # 26415...
Time:    0.0s, ETA:    0.0s [========================>]   23.73KiB/23.73KiB
Testing database: '/home/micasnyd/blah/tmp.5802bdf28c/clamav-6ddb1b6612d52f1d0affba4786e2c96d.tmp-daily.cld' ...
Database test passed.
daily.cld updated (version: 26415, sigs: 1970061, f-level: 90, builder: raynman)
```

As a workaround, for now, you can use `freshclam.conf` to customize the `DatabaseDirectory` as I did, or simply omit the `--datadir` option and let it use the default, which for you should be `/home/rkm/clamav/share/clamav`.

I'll mark this issue as a bug and we can figure out how to fix the `--datadir` issue as time permits.

**Comment by micahsnyder** [comment]
Thinking about this a little more, I think the issue is that `freshclam` isn't evaluating your `./` relative path before the `chdir(tmpdir)` you described.  You could also just use an absolute path for now until we can fix this bug.

**Comment by rkm-github** [comment]
You are right, I set DatabaseDirectory in my freshclam.conf and omitted the --datadir option in the run command, and now freshclam works when there are updates. Thanks!

**Comment by McPatate** [comment]
Hello, FYI I've had issues with relative path even in the conf file, e.g. this doesn't work:
```conf
DatabaseDirectory .
```

**Comment by ragusaa** [comment]
This is working for me with our current main.  Please re-open if you are still having this issue.

**Comment by McPatate** [comment]
Will do, thank you for letting me know!
