### ISSUE TITLE
Malformed database - ClamAv

### ISSUE THREAD

**Issue by tejaspandhare** [Cisco-Talos/clamav#409]
Hi,

Below error is reported
ClamAV version 
ClamAV 0.98.4

LibClamAV Error: Can't load daily.ldb: Malformed database
LibClamAV Error: cli_tgzload: Can't load daily.ldb
Malformed database
LibClamAV Error: Can't load /var/clamav/daily.cvd: Malformed database
ERROR: Malformed database
[FAILED]
clamd.service: control process exited, code=exited status=1

I do  not have my CentOS machine (CentOS 7) exposed  to internet,  I have to download cvd files manually and update the virus DBs

Also cant update the Clam Version on Prod.  Can anyone help?

Tejas

**Comment by finchy** [comment]
That version of ClamAV is EOL, and has been for several years.  You’ll need to upgrade. 

—

**Comment by micahsnyder** [comment]
@tejaspandhare Yes that version is really old. You must use a newer version.
