### ISSUE TITLE
remove from CDN blacklist request

### ISSUE THREAD

**Issue by vixns** [Cisco-Talos/clamav#410]
Hi,

Freshclam fails with the following error :  

ERROR: Database update process failed: Forbidden; Blocked by CDN

Could you please allow the following ipv4 addresses ?

51.68.38.78
51.68.38.79
51.75.130.33
51.75.130.34
51.91.72.154
51.91.107.190
51.210.1.76
51.83.96.43

**Comment by micahsnyder** [comment]
Before I request help from our CDN admin, please confirm that the `freshclam` clients at those IP's are using a supported ClamAV version.  

Versions 0.100 and older are actively blocked from downloading updates. 
Version 0.102 and older just exceeded End-Of-Life and will be actively blocked starting next week.  

Please ensure you are running the latest patch version of 0.103 or 0.104. 

For details on our EOL policy, see: https://docs.clamav.net/faq/faq-eol.html#version-support-matrix

**Comment by vixns** [comment]
We are using version 0.104

**Comment by micahsnyder** [comment]
I checked with our CDN admin and they don't see any of these IP's being blocked in the last 72 hours. 

How are you installing clamav?  Are you building from source or using a package?  

If they're set up the same way, can you provide the output of `clamconf -n` from one of them?

If you're building from source, can you provide the `clamav-config.h` file found in the build directory?  It may contain a clue that will help me triage this issue.

**Comment by vixns** [comment]
Not related to cdn, this issue occurs only when freshclam is ran in a distinct container without a running clamd.

**Comment by micahsnyder** [comment]
I don't know why that would be. 

Perhaps there is a configuration difference between the freshclam.conf in your freshclam+clamd container and the freshclam.conf in your freshclam-only container?
