### ISSUE TITLE
Content Credentials on photo showing malware only through Clam

### ISSUE THREAD

**Issue by nftmake** [Cisco-Talos/clamav#417]
Describe the bug
----------------

I have tried to upload several pictures with Content Credentials attached to them through photoshop. They have been rejected due to virus/malware activity. When doing a scan with VirusTotal the only service throwing that malware is Clam. That is true for both VirusTotal and https://virusscan.jotti.org/, both times clean everywhere but Clam. I do not know whether Namecheap is using Clam as well but that would explain the issue. Is there something about Content Credentials that it just doesn't like
? There is literally nothing attracted to the photo other than my social addresses and my crypto wallet address. Any ideas?
https://www.virustotal.com/gui/file/6c73d827a3c1030aa0758b38861023c4a347764ae6ca4a7c6c933991b8f6d5b8/details
https://virusscan.jotti.org/en-US/filescanjob/frltq7ci91
How to reproduce the problem
----------------------------

Attach Content Credentials to any exported file in Photoshop

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
False positives should be reported through https://www.clamav.net/reports/fp

Please upload the file to our false positive report form.
