### ISSUE TITLE
Unnecessary keyword in cmake foreach loop

### ISSUE THREAD

**Issue by mmmds** [Cisco-Talos/clamav#431]
`foreach` loops in clamav/fuzz/CMakeLists.txt unnecessarily use `in` keyword. In fact, it is not treated as a keyword but as an element. It leads to creating `fuzz/clamav_scanmap_in_fuzzer`, `fuzz/clamav_scanfile_in_fuzzer`, `fuzz/clamav_dbload_in_fuzzer`files that do not serve any purpose. `in` keyword can be removed from the loops.

https://github.com/Cisco-Talos/clamav/blob/0037f5825b0b17a789c7eb29c9cb9a2d39c452bc/fuzz/CMakeLists.txt#L46
https://github.com/Cisco-Talos/clamav/blob/0037f5825b0b17a789c7eb29c9cb9a2d39c452bc/fuzz/CMakeLists.txt#L62

**Comment by micahsnyder** [comment]
Huh! I never noticed that.  Nice observation.  I'm working on a fix for #432 and will include this fix there.

**Comment by micahsnyder** [comment]
Elsewhere in the project we have `foreach(m IN LISTS SOME_LIST_VARIABLE)`, as described in https://stackoverflow.com/a/68018445/3430496.  This is probably how I got confused when adding this one.
