### ISSUE TITLE
clamav-0.104.2/libclamav/others_common.c cannot be compiled on Mac OS X 10.4.11, Tiger, because O_SYMLINK is nowhere defined

### ISSUE THREAD

**Issue by ballapete** [Cisco-Talos/clamav#435]
The case is documented [here](https://trac.macports.org/ticket/64021). A patch is proposed. clamconf -n reports:

Checking configuration files in /opt/local/etc

Config file: clamd.conf
-----------------------
LocalSocket = "/tmp/clamd.socket"

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "4194304"
DatabaseDirectory = "/usr/local/clamXav/share/clamav"
UpdateLogFile = "/usr/local/clamXav/share/clamav/freshclam.log"
DatabaseMirror = "database.clamav.net"
NotifyClamd = "/usr/local/clamXav/etc/clamd.conf"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.104.2
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /usr/local/clamXav/share/clamav
WARNING: freshclam.conf and clamd.conf point to different database directories
bytecode.cld: version 333, sigs: 92, built on Mon Mar  8 16:21:51 2021
daily.cld: version 26431, sigs: 1972512, built on Sun Jan 23 10:22:56 2022
main.cld: version 62, sigs: 6647427, built on Thu Sep 16 14:32:42 2021
Total number of signatures: 8620031

Platform information
--------------------
uname: Darwin 8.11.0 Darwin Kernel Version 8.11.0: Wed Oct 10 18:26:00 PDT 2007; root Power Macintosh
OS: Darwin, ARCH: powerpc, CPU: powerpc
zlib version: 1.2.11 (1.2.11), compile flags: 95
platform id: 0x04018e8e1400000000070500

Build information
-----------------
GNU C: 7.5.0 (7.5.0)
sizeof(void*) = 4
Engine flevel: 142, dconf: 142

**Comment by micahsnyder** [comment]
Hi @ballapete,

I'm sorry to say that I'm not willing to add `#ifdef` clutter to the codebase to support Mac OS X 10.4. I'm trying to reduce the amount of untested code in ClamAV so this would accomplish the opposite.

Mac OS X 10.4 Tiger was discontinued by Apple in 2007, and the last security update provided by Apple was in 2009.  
I believe that the best line of defense for computer security is to keep your software up to date with the latest security patches. Newer operating systems also add security features, like ASLR added in macOS 10.7 and System Integrity Protection added in macOS 10.11.

If the change didn't introduce code that is effectively dead for our officially supported platforms, or if the change was for a platform that we don't officially support but is still supported by the vendor, then my decision would probably be different. 

I'm sorry for the bad news. I think this patch will have to stay in MacPorts only, if they'll take it.

Regards,
Micah
