### ISSUE TITLE
RPM:  clamav-update updating to latest version instead of version matching other clam components

### ISSUE THREAD

**Issue by Abashag** [Cisco-Talos/clamav#450]
We wrap clamav.x86_64 0:0.103.4-1.el7 into another RPM that includes scripts to schedule scan jobs.  Our wrapper RPM had an equal (=) dependency on the version of Clam we use to test/verify behavior with.  In this case 0.103.4-1.  However, if a newer version of Clam exists on the repo the Clam RPM gets confused and tries to update to the latest clamav-update instead of the one being requested by all other clam components.  

This causes setup to fail.  We believe the fix is to not enforce clamav-filsystem / clamav-update to require the latest versions but instead to use the version listed as the dependency:

[1] output from yum install
# yum install <WrapperRPMName>
Loaded plugins: langpacks, versionlock
Resolving Dependencies
--> Running transaction check
---> Package clamav-filesystem.noarch 0:0.103.4-1.el7 will be installed
---> Package clamav-lib.x86_64 0:0.103.4-1.el7 will be installed
--> Processing Dependency: libprelude.so.28()(64bit) for package: clamav-lib-0.103.4-1.el7.x86_64
--> Processing Dependency: libpcre2-8.so.0()(64bit) for package: clamav-lib-0.103.4-1.el7.x86_64
--> Processing Dependency: libltdl.so.7()(64bit) for package: clamav-lib-0.103.4-1.el7.x86_64
**---> Package clamav-update.x86_64 0:0.103.5-1.el7 will be installed**
--> Processing Dependency: clamav-filesystem = 0.103.5-1.el7 for package: clamav-update-0.103.5-1.el7.x86_64
--> Running transaction check
---> Package clamav-filesystem.noarch 0:0.103.4-1.el7 will be installed
--> Processing Dependency: clamav-filesystem = 0.103.4-1.el7 for package: clamav-0.103.4-1.el7.x86_64
---> Package clamav-filesystem.noarch 0:0.103.5-1.el7 will be installed
---> Package libprelude.x86_64 0:5.2.0-2.el7 will be installed
---> Package libtool-ltdl.x86_64 0:2.4.2-22.el7_3 will be installed
---> Package pcre2.x86_64 0:10.23-2.el7 will be installed
**--> Processing Conflict: clamav-filesystem-0.103.5-1.el7.noarch conflicts clamav < 0.103.5-1.el7**
--> Finished Dependency Resolution
Error: Package: clamav-0.103.4-1.el7.x86_64 (Repo2)
           Requires: clamav-filesystem = 0.103.4-1.el7
           Available: clamav-filesystem-0.103.1-3.el7.noarch (Repo1)
               clamav-filesystem = 0.103.1-3.el7
           Available: clamav-filesystem-0.103.2-1.el7.noarch (Repo1)
               clamav-filesystem = 0.103.2-1.el7
           Available: clamav-filesystem-0.103.2-2.el7.noarch (Repo1)
               clamav-filesystem = 0.103.2-2.el7
           Available: clamav-filesystem-0.103.3-1.el7.noarch (Repo1)
               clamav-filesystem = 0.103.3-1.el7
           Available: clamav-filesystem-0.103.3-5.el7.noarch (Repo1)
               clamav-filesystem = 0.103.3-5.el7
           Available: clamav-filesystem-0.103.3-8.el7.noarch (Repo1)
               clamav-filesystem = 0.103.3-8.el7
           Available: clamav-filesystem-0.103.4-1.el7.noarch (Repo2)
               clamav-filesystem = 0.103.4-1.el7
           **Installing: clamav-filesystem-0.103.5-1.el7.noarch (Repo1)
               clamav-filesystem = 0.103.5-1.el7**
Error: clamav-filesystem conflicts with clamav-0.103.4-1.el7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by micahsnyder** [comment]
This looks to me like an issue with EPEL's clamav packages. Please open the ticket with them.  
I think this is EPEL's issue tracker, but I'm not 100% certain: https://pagure.io/epel
