### ISSUE TITLE
Small mistake on documentation

### ISSUE THREAD

**Issue by nerux1** [Cisco-Talos/clamav#467]
Hello,

I show a little mistake on your [documentation](https://docs.clamav.net/manual/Installing/Docker.html#controlling-the-container).
> CLAMAV_NO_MILTERD [true|false] Do not start the clamav-milter daemon. (default: start the clamav-milter daemon )

It must be :
`CLAMAV_NO_MILTERD [true|false] Do not start the clamav-milter daemon. (default: clamav-milter daemon is not started )`

Regards,

**Comment by micahsnyder** [comment]
Thanks @nerux1 

By the way, our documentation is also open source: https://github.com/Cisco-Talos/clamav-documentation/blob/main/src/manual/Installing/Docker.md#controlling-the-container

If you find any additional issues, feel free to submit a PR on the clamav-documentation repo.

**Comment by micahsnyder** [comment]
Fixed here. Documentation online will be updated within minutes after it rebuilds https://github.com/Cisco-Talos/clamav-documentation/commit/8c7d7bf3db5d382e12e23d80242a7124f2b8130f
