### ISSUE TITLE
Not able to download antivirus databases

### ISSUE THREAD

**Issue by satheeshkmrss** [Cisco-Talos/clamav#495]
Describe the bug
----------------

Not able to download antivirus databases
**dockerfile**
# Install ClamAV and supervisor
RUN echo "deb http://http.debian.net/debian/ $DEBIAN_VERSION main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://http.debian.net/debian/ $DEBIAN_VERSION-updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://security.debian.org/ $DEBIAN_VERSION/updates main contrib non-free" >> /etc/apt/sources.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --allow-unauthenticated -y -qq \
    clamav-daemon \
    clamav-freshclam \
    libclamunrar7 \
    supervisor \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Initial update of av databases
RUN wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd && \
    wget -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd && \
    wget -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd && \
    chown clamav:clamav /var/lib/clamav/*.cvd

# Update Permission
RUN mkdir /var/run/clamav && \
    chown clamav:clamav /var/run/clamav && \
    chmod 750 /var/run/clamav

# Configuration update
RUN sed -i 's/^Foreground .*$/Foreground true/g' /etc/clamav/clamd.conf && \
    sed -i 's/^MaxScanSize .*$/MaxScanSize 300M/g' /etc/clamav/clamd.conf && \
    sed -i 's/^MaxFileSize .*$/MaxFileSize 250M/g' /etc/clamav/clamd.conf && \
    sed -i 's/^StreamMaxLength .*$/StreamMaxLength 1000M/g' /etc/clamav/clamd.conf && \
    echo "TCPSocket 3310" >> /etc/clamav/clamd.conf && \
    sed -i 's/^Foreground .*$/Foreground true/g' /etc/clamav/freshclam.conf

# Volume provision
VOLUME ["/var/lib/clamav"]

WORKDIR /server

COPY . /server

RUN npm install 

# Copy supervisor config
COPY ./configs/supervisord.conf /etc/supervisor/conf.d/supervisord-nodejs.conf

Attachments
-----------
![image](https://user-images.githubusercontent.com/101258417/157432139-36c148ca-247c-4028-8c77-69b46445fde9.png)

Im installing the clam av in docker container. It is not able to download antivirus databases. When i tried to upgrade the version iam not able to. first uninstalled the clamav in container, then installed the clamav but still it shows the older version.

**Comment by micahsnyder** [comment]
Hello!

In your attachment I see that you have ClamAV 0.101.5. This version is no longer supported and is actively blocked from getting database updates. You will need ClamAV 0.103 or newer to get database updates. 

For details on our End of Life policy, please see: https://docs.clamav.net/faq/faq-eol.html
