### ISSUE TITLE
ERROR: Database update process failed: Forbidden; Blocked by CDN

### ISSUE THREAD

**Issue by Archont13** [Cisco-Talos/clamav#502]
We are being blocked by Clamav CDN. Our IP's: 213.156.210.101 , 85.113.45.100 . Clamav version 0.103.2 (zimbra server). Update timer 2h. Website blocked too (error 1020) Ray ID: 6ec4a2672f445f98. database.clamav.net blocked Ray ID: 6ec4a2dafe4a5faa.
What happened?

**Comment by finchy** [comment]
Please see: https://github.com/Cisco-Talos/clamav/issues/500

**Comment by Archont13** [comment]
tnx... so sad
