### ISSUE TITLE
LibClamAV Error: cli_loaddbdir: No supported database files found in /usr/local/share/clamav

### ISSUE THREAD

**Issue by Azaretdodo** [Cisco-Talos/clamav#509]
Describe the bug
----------------
when i launch : '''sudo clamscan --remove -r /''' 

i get : '''LibClamAV Error: cli_loaddbdir: No supported database files found in /usr/local/share/clamav
ERROR: Can't open file or directory

----------- SCAN SUMMARY -----------
Known viruses: 0
Engine version: 0.105.0-rc
Scanned directories: 0
Scanned files: 0
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 0.003 sec (0 m 0 s)
Start Date: 2022:03:18 16:22:26
End Date:   2022:03:18 16:22:26
'''

How to reproduce the problem
----------------------------

'''sudo clamscan --remove -r /'''

Replace this text with the output from the ClamAV command:
    clamconf -n = 

'''clamconf -n
Checking configuration files in /usr/local/etc

clamd.conf not found

freshclam.conf not found

clamav-milter.conf not found

Software settings
-----------------
Version: 0.105.0-rc
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /usr/local/share/clamav
WARNING: freshclam.conf and clamd.conf point to different database directories
Total number of signatures: 0

Platform information
--------------------
uname: Linux 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64
OS: Linux, ARCH: x86_64, CPU: x86_64
Full OS version: Ubuntu 20.04.4 LTS
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x0a2196960800000000090400

Build information
-----------------
GNU C: 9.4.0 (9.4.0)
sizeof(void*) = 8
Engine flevel: 150, dconf: 150
'''

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by Azaretdodo** [comment]
i have repair by myself this problem

**Comment by Justuser3310** [comment]
Great, how repaired?
