### ISSUE TITLE
clamav entirely blocks Russian IPs via cloudflare - can't use freshclam at all

### ISSUE THREAD

**Issue by qumuq-til** [Cisco-Talos/clamav#513]
Since 9.03 clamav fully blocks Russian IPs from accessing anything clamav-related, the main website, databases, everything. Specifying mirrors by hand always leads to the same error as everything is fully blocked. Is there a way around that so we can still receive freshclam updates on servers normally?

**Comment by finchy** [comment]
Please see: https://github.com/Cisco-Talos/clamav/issues/500
