### ISSUE TITLE
freshclam stopped working

### ISSUE THREAD

**Issue by lehel0** [Cisco-Talos/clamav#517]
Describe the bug
----------------
Relevant log records from mail.skpress.ru. Same from mail.ineos.ac.ru and mail.fluorine1.ru. Checks parameter in freshclam.conf - 12. What could be wrong? Why 3 different networks blocked by CDN?

freshclam daemon 0.104.2 (OS: FreeBSD, ARCH: amd64, CPU: amd64)
freshclam[70622]: ClamAV update process started at Wed Mar 23 16:50:54 2022
freshclam[70622]: Cool-down expired, ok to try again.
freshclam[70622]: daily database available for update (local version: 26475, remote version: 26490)
freshclam[70622]: downloadPatch: Can't download daily-26476.cdiff from https://database.clamav.net/daily-26476.
cdiff
freshclam[70622]: Incremental update failed, trying to download daily.cvd
freshclam[70622]: Can't download daily.cvd from https://database.clamav.net/daily.cvd
freshclam[70622]: FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
freshclam[70622]: This could mean several things:
freshclam[70622]:  1. You are running an out-of-date version of ClamAV / FreshClam.
freshclam[70622]:     Ensure you are the most updated version by visiting https://www.clamav.net/downloads
freshclam[70622]:  2. Your network is explicitly denied by the FreshClam CDN.
freshclam[70622]:     In order to rectify this please check that you are:
freshclam[70622]:    a. Running an up-to-date version of FreshClam
freshclam[70622]:    b. Running FreshClam no more than once an hour
freshclam[70622]:    c. If you have checked (a) and (b), please open a ticket at
freshclam[70622]:       https://github.com/Cisco-Talos/clamav/issues
freshclam[70622]:       and we will investigate why your network is blocked.
freshclam[70622]: You are on cool-down until after: 2022-03-24 16:51:01
freshclam[70622]: Database update process failed: Forbidden; Blocked by CDN
freshclam[70622]: Update failed.
freshclam[70622]: FreshClam was forbidden from downloading a database.
freshclam[70622]: This is fatal. Retrying later won't help. Exiting now.

How to reproduce the problem
----------------------------

Checking configuration files in /usr/local/etc

Config file: clamd.conf
-----------------------
LogSyslog = "yes"
PidFile = "/var/run/clamav/clamd.pid"
LocalSocket = "/var/run/clamav/clamd.sock"
User = "root"

Config file: freshclam.conf
---------------------------
LogSyslog = "yes"
PidFile = "/var/run/clamav/freshclam.pid"
DatabaseMirror = "db.ru.clamav.net", "db.de.clamav.net", "database.clamav.net"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.104.2
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR

Database information
--------------------
Database directory: /var/db/clamav
[3rd Party] whitelist.ign2: 1 sig
main.cld: version 62, sigs: 6647427, built on Thu Sep 16 15:32:42 2021
daily.cld: version 26475, sigs: 1975374, built on Tue Mar  8 12:31:43 2022
bytecode.cld: version 333, sigs: 92, built on Mon Mar  8 18:21:51 2021
Total number of signatures: 8622894

Platform information
--------------------
uname: FreeBSD 11.3-RELEASE-p11 FreeBSD 11.3-RELEASE-p11 #0: Wed Jul  8 05:43:42 UTC 2020     ro amd64
OS: FreeBSD, ARCH: amd64, CPU: amd64
zlib version: 1.2.11 (1.2.11), compile flags: a9
platform id: 0x03238e8e0800000000040201

Build information
-----------------
Clang: 4.2.1 Compatible FreeBSD Clang 8.0.0 (tags/RELEASE_800/final 356365) (4.2.1)
sizeof(void*) = 8
Engine flevel: 142, dconf: 142

**Comment by net1** [comment]
Please see #500
