### ISSUE TITLE
LibClamAV Error: cli_realloc(): Attempt to allocate 190840848 bytes. Please report to https://github.com/Cisco-Talos/clamav/issues

### ISSUE THREAD

**Issue by newwhitebear** [Cisco-Talos/clamav#518]
clamscan reports this error. LibClamAV Error: cli_realloc (): Attempt to allocate 190840848 bytes. Please report to https://github.com/Cisco-Talos/clamav/issues
s.o. ubunto 20.04 lts, clamav packages 0.103.5 + dfsg-1-20.04.1

**Comment by ragusaa** [comment]
I am attempting to clean up old issues that are no longer relevant. I believe this has been addressed, so I am going to close, but if not, please re-open.
