### ISSUE TITLE
Is not available in Russia

### ISSUE THREAD

**Issue by gedonis** [Cisco-Talos/clamav#524]
http://www.clamav.net website, as well as automatic virus databases updates, are not available from Russia, since March 7, 2022, Please enable it again.
![Uploading image_2022-04-03_153238.png…]()

I see the text on http://www.clamav.net/downloads#tools - 
Access was denied Error code 1020
You do not have access to www.clamav.net.
The site owner may have set restrictions that prevent you from accessing the site. Contact the site owner for access or try loading the page again.

Additional information
The access policies of a site define which visits are allowed. Your current visit is not allowed according to those policies.
Only the site owner can change site access policies.

RayID: 6f61ddaa0e6616e3

**Comment by micahsnyder** [comment]
Please see #500
