### ISSUE TITLE
ClamAv is not able to detect the attached sample files as virus.

### ISSUE THREAD

**Issue by njaciklum** [Cisco-Talos/clamav#539]
I have tested with following versions

0.105
0.104
0.103

Execution of following command doesn't consider this file as virus, but anti-viruses installed on system level are detecting this file as virus.

`clamscan /Users/naveedjavaid/Downloads/Customer\ Test\ PDF-Virus.pdf`

`clamdscan -i --no-summary --fdpass --remove /Users/naveedjavaid/Downloads/Customer\ Test\ PDF-Virus.pdf`

**OutPut of the command**

<img width="622" alt="image" src="https://user-images.githubusercontent.com/82313037/162690919-f2be9140-ee79-48cb-b666-061f0f5fe040.png">

[Test PDF-Virus.pdf](https://github.com/Cisco-Talos/clamav/files/8462083/Test.PDF-Virus.pdf)

Any help will be appreciated.

Thanks

**Comment by micahsnyder** [comment]
The attached file is a copy of the EICAR test string with a generic PDF concatenated to the end:

It starts out like this:
```
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*%PDF-1.5
%����
10 0 obj
<</Linearized 1/L 18461/O 12/E 13979/N 1/T 18159/H [ 484 163]>>
endobj
                  
27 0 obj
```

ClamAV is very strict about following the EICAR specification and will not detect this, intentionally. 

The specification states:

> The first 68 characters is the known string. It may be optionally appended by any combination of whitespace characters with the total file length not exceeding 128 characters. The only whitespace characters allowed are the space character, tab, LF, CR, CTRL-Z. To keep things simple the file uses only upper case letters, digits and punctuation marks, and does not include spaces. The only thing to watch out for when typing in the test file is that the third character is the capital letter „O“, not the digit zero.

Ref: https://www.eicar.org/?page_id=3950

In this case, the file starts with the 68-byte EICAR string but continues on with PDF data and does not match the rest of the requirements.  The other AV software you are testing with are more casual about the EICAR specification.
