### ISSUE TITLE
File not scanned if file size is larger than MaxScanSize

### ISSUE THREAD

**Issue by mkrueger-sabio** [Cisco-Talos/clamav#541]
Describe the bug
----------------

I created a file with 100MB size with random content and run

```
/ # clamscan --max-filesize=100M --max-scansize=25M /etc/clamav/scan.txt 
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
Loading:    13s, ETA:   0s [========================>]    8.61M/8.61M sigs       
Compiling:   4s, ETA:   0s [========================>]       41/41 tasks 

/etc/clamav/scan.txt: OK

----------- SCAN SUMMARY -----------
Known viruses: 8609030
Engine version: 0.104.2
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 0.00 MB
Data read: 32.00 MB (ratio 0.00:1)
Time: 18.012 sec (0 m 18 s)
Start Date: 2022:04:12 13:32:32
End Date:   2022:04:12 13:32:50
/ # clamscan --max-filesize=100M --max-scansize=100M /etc/clamav/scan.txt 
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
Loading:    14s, ETA:   0s [========================>]    8.61M/8.61M sigs       
Compiling:   3s, ETA:   0s [========================>]       41/41 tasks 

/etc/clamav/scan.txt: OK

```

I was confused because I expected that the first 25MB are scanned according to the argument description:

```
--max-scansize=#n                    The maximum amount of data to scan for each container file (**)
```

When I set `--max-scansize=100M` the file is scanned. I also create a 100MB zip file with four 25MB files with the same result.

Can you explain the parameter in more detail?

**Comment by micahsnyder** [comment]
The behavior you observed in the intended behavior.  ClamAV will skip any file (or embedded file) larger than the max-scansize. 
The documentation for the equivalent feature in ClamD is more clear: https://github.com/Cisco-Talos/clamav/blob/main/etc/clamd.conf.sample#L530-L539

You may use the `--alert-exceeds-max` command line option (or for ClamD `AlertExceedsmax yes` config option) if you want an indication that the file has been skipped because it exceeded a scan limit.

**Comment by mkrueger-sabio** [comment]
The question is not about `--max-filesize` but `--max-scansize`. The file is not scanned when the filesize exceeds `max-scansize`. At least in `clamscan`. I don't know if `clamd` behaves the same.
