### ISSUE TITLE
Error 403 while manually downloading the virus database

### ISSUE THREAD

**Issue by Gulraiz832** [Cisco-Talos/clamav#562]
Hi I am trying to download virus database using
wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd

But it is returning 403 forbidden
![image](https://user-images.githubusercontent.com/41158802/164992545-13a9c991-a1e1-4636-9e60-5af7a9af8f77.png)

**Comment by finchy** [comment]
You must use freshclam or cvdupdate to download the ruleset.

**Comment by micahsnyder** [comment]
@finchy answer is correct.  

Please do not try to find a work-around to use some other tool.  Freshclam and cvdupdate are specially designed to only download the databases if there is a newer version.  Freshclam, specifically, will update using patch file to further save bandwidth.  These are cost-saving measures to keep it affordable for us to continue to deliver the free malware detection rules.
