### ISSUE TITLE
Clamav 0.105.0 test libclamav_rust failed

### ISSUE THREAD

**Issue by teoberi** [Cisco-Talos/clamav#569]
Describe the bug
----------------
2/6 Test 2: libclamav_rust ...................***Failed  361.12 sec
The following tests FAILED:
          2 - libclamav_rust **(Failed)**

How to reproduce the problem
----------------------------
llvm-config --version: 13.0.1
https://packages.slackware.com/?r=slackware64-current&p=llvm-13.0.1-x86_64-1.txz&f

cd clamav-0.105.0
mkdir build && cd build
cmake .. \
        -D CMAKE_INSTALL_PREFIX:PATH=/opt/clamav \
        -D ENABLE_CLAMONACC=OFF \
        -D ENABLE_MILTER=OFF \
        -D ENABLE_SYSTEMD=OFF \
        -D BYTECODE_RUNTIME="llvm"
cmake --build . --config Release
ctest

Attachments
-----------

[LastTest.log](https://github.com/Cisco-Talos/clamav/files/8629490/LastTest.log)

**Comment by tpotega** [comment]
Same behaviour on CentOS 7/LLVM 9.0 (EPEL), trouble being the test is passing "-lLLVM..." as the library name - which ends up as "-l-lLLVM..." during linking.

Worked around with a patch stripping the "-l" prefix (will do for many of Unix-alikes, but may fail miserable elsewhere).

[libclamav_rust-llvm-linking-test-failure.patch.txt](https://github.com/Cisco-Talos/clamav/files/8638725/libclamav_rust-llvm-linking-test-failure.patch.txt)

**Comment by teoberi** [comment]
Thanks @tpotega I think the problem has been solved with a small change!
Your code:
`string(REPLACE "-l" "" LLVM_LIBRARIES ${LLVM_LIBRARIES})`
My change:
`string(REPLACE "-l" "" LLVM_LIBRARIES "${LLVM_LIBRARIES}")`

With double quotes I do no longer lose the delimiter between libs.

> /usr/bin/ld: cannot find -lLLVMWindowsManifest-lLLVMXRay-lLLVMLibDriver ... -lLLVMTableGen-lLLVMSupport-lLLVMDemangle: File name too long

A little help from:
https://stackoverflow.com/questions/48292694/why-does-string-replace-of-cmake-have-this-behavior
> The semicolon character is used as a separator for lists in the [CMake language]
(https://cmake.org/cmake/help/latest/manual/cmake-language.7.html?highlight=semicolon#lists).

> Note also, that you need to enclose content of your file into double quotes. The thing is that your file contains semicolons ; , which in unquoted form are interpreted by CMake as arguments delimiters.
Specific of [string(REGEX REPLACE)](https://cmake.org/cmake/help/latest/command/string.html#regex-replace) is that it concatenates all input arguments, so without quotes semicolons will be lost.

https://stackoverflow.com/questions/69930610/how-to-use-cmake-string-regex-replace-to-get-last-part-of-path-url-from-multiple

**Comment by micahsnyder** [comment]
This issue isn't one that I was aware of.  I'm really excited you found a solution, and so quickly. Are you interested in submitting a PR?

There are also a handful of known issues in 0.105.0 with getting LLVM packages to properly link with libclamav:  https://github.com/Cisco-Talos/clamav/blob/clamav-0.105.0/INSTALL.md?plain=1#L722-L736
In case you run into them, and want to help solve them - we'd enjoy the help 😉.

**Comment by teoberi** [comment]
Are you sure this workaround is the best solution or should the Clamav programmers fix the cause not the effect?
It's not a problem to submit a PR, I can do that now.

**Comment by micahsnyder** [comment]
> Are you sure this workaround is the best solution or should the Clamav programmers fix the cause not the effect? It's not a problem to submit a PR, I can do that now.

I'm not sure -- it might actually be an issue with the FindLLVM.cmake module, or just because the text it grabs from the `llvm-config` program is inconsistent (which is what I was guessing).  We can look at closer in PR review.  Thanks for making that PR :)

**Comment by micahsnyder** [comment]
Merged https://github.com/Cisco-Talos/clamav/pull/572

The fix will appear in the next feature release
