### ISSUE TITLE
“The newest LLVM version supported is 3.6.2” and “it can use LLVM versions 8 through 12”.

### ISSUE THREAD

**Issue by dilyanpalauzov** [Cisco-Talos/clamav#574]
The file [NEWS.md](https://github.com/Cisco-Talos/clamav/blob/main/NEWS.md#notable-changes) contains:
> Updated the LLVM bytecode runtime support so that it can use LLVM versions 8 through 12 and removed support for earlier LLVM versions.

while [INSTALL.md](https://github.com/Cisco-Talos/clamav/blob/main/INSTALL.md#known-issues--to-dos) states:
> The newest LLVM version supported is 3.6.2. We ran out of time during 0.104 development to add support for newer versions of LLVM. 

The information in both files is mutually exclusive.

**Comment by teoberi** [comment]
Works even with LLVM 13.0.1

**Comment by micahsnyder** [comment]
Thanks for the heads up.  We totally forgot to remove the "The newest LLVM version supported is 3.6.2..." line.

**Comment by wschlich** [comment]
When will LLVM 14 or 15 be supported?

**Comment by teoberi** [comment]
https://github.com/Cisco-Talos/clamav/issues/580#issuecomment-1188054430

**Comment by wschlich** [comment]
@teoberi I can't see any date related estimates for LLVM 14+ support in issue #580 🤷🏼‍♂️

**Comment by teoberi** [comment]
I don't even think it exists yet!

**Comment by wschlich** [comment]
@teoberi maybe I misinterpreted your previous comment, just mentioning another issue right after I asked for a date related estimate 🙃
