### ISSUE TITLE
Not able to download .cvd files using wget.

### ISSUE THREAD

**Issue by UtpalCerta** [Cisco-Talos/clamav#585]
By using browser I am able to download the .cvd files i.e main.cvd, daily.cvd and bytecode.cvd from server : https://database.clamav.net/

<img width="804" alt="Screenshot 2022-05-16 at 1 09 02 PM" src="https://user-images.githubusercontent.com/103642359/168543393-3764850d-cf3b-4aea-ad91-ea5cfd89b00b.png">

But I am getting 403 access denied error when downloading the files by wget. Below given is the command that I ran.

wget https://database.clamav.net/main.cvd

**Comment by teoberi** [comment]
https://docs.clamav.net/faq/faq-freshclam.html

> [HTTP Error Codes](https://docs.clamav.net/faq/faq-freshclam.html#http-error-codes)
If you are receiving a 403, 503, or 1020 error codes when downloading from Cloudflare, then you are either explicitly blocked, using an [EOL'ed version of ClamAV](https://docs.clamav.net/faq/faq-eol.html) or you are downloading incorrectly.
>If FreshClam is failing and you're not sure why, you may run freshclam -v for "Verbose Mode" to see the HTTP request & response details (ClamAV 0.102+).
>After checking that you are using a current version of ClamAV, please discontinue whatever method of download you are using and immediately move to using either FreshClam or [cvdupdate](https://github.com/Cisco-Talos/cvdupdate). These are the two supported methods for downloading AV updates from ClamAV. All other methods may be rate limited, or blocked at our discretion. Use of Wget, Curl, or other command line tools that are scripted are explicitly denied.

**Comment by micahsnyder** [comment]
Sorry @UtpalCerta we do not want anyone using `wget`, `curl`, etc to download these files.  The tools `freshclam` and `cvdupdate` have features that prevent them from downloading the file if the the local copy is already the latest version.  In addition, `freshclam` will update local copies using patch files (`.cdiff` files).  This has a meaningful cost savings for our project and enables us to continue to provide it for free.

**Comment by pacocc** [comment]
Is there much difference between using curl and linking to libcurl?  Given they both are the source of numerous CVEs would like to remove this package from the ClamAV host, but that breaks freshclam:

  freshclam --debug
    ld-elf.so.1: Shared object "libcurl.so.4" not found, required by "freshclam"

**Comment by micahsnyder** [comment]
@pacocc  freshclam uses libcurl for HTTPS connections.  freshclam has the logic to check if there is an update before trying to download the files, and then uses libcurl to download those files.  curl does not have that logic, so if you try to download with curl it would download every time even if there is no change, and waste lots of bandwidth.
