### ISSUE TITLE
***BEFORE OPENING AN ISSUE IN GITHUB***

### ISSUE THREAD

**Issue by vrtadmin** [Cisco-Talos/clamav#59]
**Our official bug tracking system is**:

[https://bugzilla.clamav.net](https://bugzilla.clamav.net)

Please submit any bugs there.  

 If you need to ask a question, please do so on the [ClamAV Mailing lists](http://www.clamav.net/contact#ml)

To Submit malware, please visit our website and fill out the [form](http://www.clamav.net/contact) there.

**Comment by micahsnyder** [comment]
Our security policy is in place, and accidental vuln disclosure warnings in place in our new GitHub Issue template.  I'm happy to start receiving GitHub Issues now.  

When we're ready to announce this migration, and after we have changed all links on clamav.net to point to GitHub Issues, then we should change Bugzilla so it is still accessible but new tickets may not be created (if possible?).

> *Note*: The docs.clamav.net documentation now direct people here, but we haven't yet switched to direct people to docs.clamav.net.
