### ISSUE TITLE
Some PDFs fail to scan with 0.105 (but work with 0.104)

### ISSUE THREAD

**Issue by alext** [Cisco-Talos/clamav#593]
Describe the bug
----------------

I'm experiencing a scanning failure for a specific PDF that only occurs with 0.105. The file scans clean when scanned with 0.104.

How to reproduce the problem
----------------------------

Running using the official docker images: `docker run -ti --rm -p 3310:3310 clamav/clamav:0.105`, and then scanning the file with clamdscan from the host: `clamdscan --config-file=./clamd.conf --stream file.pdf`.

Running against 0.105 reports:
```
/tmp/file.pdf: Can't parse data ERROR

----------- SCAN SUMMARY -----------
Infected files: 0
Total errors: 1
Time: 0.543 sec (0 m 0 s)
Start Date: 2022:05:24 09:57:30
End Date:   2022:05:24 09:57:31
```

Running against 0.104 reports:
```
/tmp/test.pdf: OK

----------- SCAN SUMMARY -----------
Infected files: 0
Time: 0.760 sec (0 m 0 s)
Start Date: 2022:05:24 10:16:09
End Date:   2022:05:24 10:16:10
```

I'm not able to provide the specific file as an attachment as it contains sensitive information, however, I've captured a debug log from the failed scan here:

https://gist.github.com/alext/a97a3ce43701ab64ab6ad35e821723f0

I'm not familiar with the ClamAV codebase, but one thing that stands out to me is the line:

```
LibClamAV debug: Failed to calculate image fuzzy hash for CL_TYPE_JPEG: Failed to load image: The decoder for Jpeg does not support the format features DNL
```

/ # clamd --version
ClamAV 0.105.0/26537/Tue May 10 08:08:04 2022

/ # clamconf -n
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
LogFile = "/var/log/clamav/clamd.log"
LogTime = "yes"
PidFile = "/run/lock/clamd.pid"
LocalSocket = "/run/clamav/clamd.sock"
TCPSocket = "3310"
User = "clamav"

Config file: freshclam.conf
---------------------------
PidFile = "/run/lock/freshclam.pid"
UpdateLogFile = "/var/log/clamav/freshclam.log"
DatabaseMirror = "database.clamav.net"

Config file: clamav-milter.conf
-------------------------------
LogFile = "/var/log/clamav/milter.log"
LogTime = "yes"
PidFile = "/run/lock/clamav-milter.pid"
User = "clamav"
ClamdSocket = "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock"
MilterSocket = "inet:7357"

Software settings
-----------------
Version: 0.105.0
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /var/lib/clamav
bytecode.cvd: version 333, sigs: 92, built on Mon Mar  8 15:21:51 2021
daily.cvd: version 26537, sigs: 1984235, built on Tue May 10 08:08:04 2022
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 12:32:42 2021
Total number of signatures: 8631754

Platform information
--------------------
uname: Linux 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64
OS: Linux, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.12 (1.2.12), compile flags: a9
platform id: 0x0a21969608000000000a0301

Build information
-----------------
GNU C: 10.3.1 20211027 (10.3.1)
sizeof(void*) = 8
Engine flevel: 150, dconf: 150

Attachments
-----------

I'm not able to attach the specific file.  If the above debug log is insufficient to diagnose the problem, please let me know, and I'll see if there's a way to provide the file to you.

**Comment by martin-ms** [comment]
Can't also attach a PDF due to its sensitive content, but since it is not limited on PDFs and also occurs with PNGs I have an example for you:

`fritz.png: PNG image data, 112 x 87, 8-bit/color RGBA, non-interlaced`

![fritz](https://user-images.githubusercontent.com/7189867/170017689-e1903272-a0b6-4896-a0ea-10d8cdd035fb.png)

This could be scanned with version 0.104.2
```
/tmp/clamav/issue#593/fritz.png: OK
 
----------- SCAN SUMMARY -----------
Known viruses: 8616621
Engine version: 0.104.2
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 0.02 MB
Data read: 0.02 MB (ratio 1.00:1)
Time: 10.825 sec (0 m 10 s)
Start Date: 2022:05:24 12:27:19
End Date:   2022:05:24 12:27:29

```
but not with verion 0.105.0
```
/tmp/clamav/issue#593/fritz.png: Can't parse data ERROR
 
----------- SCAN SUMMARY -----------
Known viruses: 8616571
Engine version: 0.105.0
Scanned directories: 0
Scanned files: 0
Infected files: 0
Total errors: 1
Data scanned: 0.02 MB
Data read: 0.02 MB (ratio 1.00:1)
Time: 10.770 sec (0 m 10 s)
Start Date: 2022:05:24 12:28:17
End Date:   2022:05:24 12:28:28

```
I am also confused that 0.104.2 know more "Known viruses" than 0.105.0, despite if I used the same virus databases.

**Comment by ragusaa** [comment]
Thank you for the sample.  I am able to reproduce the error with no problem.  I'll open a ticket internally, and let you know when we have something.

**Comment by sbstp** [comment]
Hey, just wanted to let you know that we are also experiencing this error on some PDFs that we try to scan. The PDF themselves are large res scan of files, could be PNG. I can't share those files with you because they contain PII.

**Comment by martin-ms** [comment]
I have now attached a PDF showing the problem: [Einwilligung-de.pdf](https://github.com/Cisco-Talos/clamav/files/8822731/Einwilligung-de.pdf). 

It's a real PDF, searchable and with an embedded character set, and not a PNG or JPEG image.

Although this PDF is an editable form, that is not the reason, the problem also occurs with non-editable PDFs.
