### ISSUE TITLE
Freshclam.log - WARNING: DNS record is older than 3 hours

### ISSUE THREAD

**Issue by phrossignol** [Cisco-Talos/clamav#595]
Hello,
For about one week from now the following message is logged in freshclam.log :

Thu May 26 12:23:45 2022 -> WARNING: DNS record is older than 3 hours.
Thu May 26 12:23:45 2022 -> Trying to retrieve CVD header from https://database.clamav.net/daily.cvd
Thu May 26 12:23:45 2022 -> daily.cld database is up-to-date (version: 26552, sigs: 1984573, f-level: 90, builder: raynman)
Thu May 26 12:23:45 2022 -> Trying to retrieve CVD header from https://database.clamav.net/main.cvd
Thu May 26 12:23:45 2022 -> main.cld database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Thu May 26 12:23:45 2022 -> Trying to retrieve CVD header from https://database.clamav.net/bytecode.cvd
Thu May 26 12:23:45 2022 -> bytecode.cld database is up-to-date (version: 333, sigs: 92, f-level: 63, builder: awillia2)

ClamAV version is 0.105.0 for Windows 64 bits (Mercury/32 Mail Transport Agent).
I checked eventual DNS problems on the server. All the posts related to this warning are for Linux.
Any idea ?.
Tia.

**Comment by ragusaa** [comment]
Thank you for the report.  This warning is nothing to worry about.  We are considering whether or not to extend the timeout for the warning.

**Comment by micahsnyder** [comment]
We decided to increase the rate at which we refresh the DNS record before we consider changing freshclam to wait longer before complaining that the DNS record is stale. Hopefully this solves the issue.  

Please re-open this issue if it happens again.  If you or others continue to see this warning, we can patch freshclam to be less fussy.
