### ISSUE TITLE
Can't find the docker image for the LTS version (v0.103) in the official docker images for the ClamAV project

### ISSUE THREAD

**Issue by kibnelbachyr** [Cisco-Talos/clamav#603]
Describe the bug
----------------
As mentioned [here](https://docs.clamav.net/faq/faq-eol.html#long-term-support-lts-feature-releases ) ClamAV 0.103 is the Long Term Support (LTS) release. But we can't find it the official docker images for the ClamAV project.

How to reproduce the problem
----------------------------

Check the official docker images for the ClamAV project : https://hub.docker.com/r/clamav/clamav/tags

**Comment by micahsnyder** [comment]
Hi @kibnelbachyr 

We only started publishing docker images with version 0.104. There is no official image for 0.103. Sorry!
