### ISSUE TITLE
False Positive Signature "Archive.Test.Agent2-9953724-0"

### ISSUE THREAD

**Issue by hebelal** [Cisco-Talos/clamav#620]
Hi,

This morning we received an update for our signature database from freshclam which includes a signature that leads to many zip files being detected as virus.
The signature is: "Archive.Test.Agent2-9953724-0", which already sounds like it is not a virus.
On virustotal only ClamAV detects this zip file as virus.
Unfortunately since the zip file contains confidential data I can not post it here.
Please double check with the team responsible for the signature database. 

Best regards,
Alex

**Comment by SBKila** [comment]
I have created a zip file with 1 javascript file, from a clean PC and upload on virustotal.com , I get the same error only with clamav

**Comment by Auroray** [comment]
We started getting these false positives from ServiceNow's virus scanning service, which must be powered by either Virus Total or ClamAV directly. A lot of customers affected, internal log bundles can't be attached to support cases because they are reported to contain this threat. Manually scanning these in VirusTotal shows that only ClamAV reports a threat.

**Comment by mrblug** [comment]
Same issue occurred when scanning /usr/lib/. Clamscan said there were 10 infected files. One of the results is: 

/usr/lib/firefox/browser/omni.ja: Archive.Test.Agent2-9953724-0 FOUND

There is hardly any information about Archive.Test.Agent2 on the Internet, but I got 10 files 'infected', which is strange.

**Comment by Auroray** [comment]
We've reported this issue to ServiceNow as well - since ClamAV is used in some way to provide them with a commercial A/V scanning offering they might be able to put pressure on ClamAV more effectively than we can in a GitHub issue.

**Comment by harridu** [comment]
Metoo

**Comment by harridu** [comment]
I would strongly recommend to provide a fix asap. In a 3.7 GByte tar.gz file with 9099 files clamav found 71 false positives (0.78%). Thats a pretty high rate.

**Comment by shoan** [comment]
We are seeing this in python whl files

**Comment by micahsnyder** [comment]
> I would strongly recommend to provide a fix asap. In a 3.7 GByte tar.gz file with 9099 files clamav found 71 false positives (0.78%). Thats a pretty high rate. Imagine 1% of all EMails with an attachment is rejected.

The daily database is being republished early and should be out as soon as it can be built and tested.  I don't have a specific ETA, but it is already in progress and will be sooner than the normal publishing time.

**Comment by The-Gae-Bolg** [comment]
I have problems uploading my projects that contain javascript files, it tells me that this virus was detected in the zip file.

**Comment by Mil152** [comment]
Have issue when I submit my .tex research paper in zip file to Publish group. Sad

**Comment by micahsnyder** [comment]
The new daily database update is out and should resolve this issue.

**Comment by chrisgaraffa** [comment]
Thanks @micahsnyder - I can confirm this cleared up the false positive for us.

**Comment by harridu** [comment]
After a freshclam at 18:45 GMT the problem appears to be gone.

Thank you very much. Good work

**Comment by RealDrJ** [comment]
Is this completely fixed? I was hit by this false pos and I finally tracked down and restored all the files I "lost" as a result, but a small number seem to be permanently scarred by Archive.Test.Agent2-9953724. Regardless of whether I restore these files or move them out of the Trash, they are immediately flagged and quarantined again. I updated the database around 9a EST Jun 25 and confirmed like everyone else here that the issue no longer existed going forward, but there seems to be something not quite right. I'm using ClamXAV as the front end to clamd on macOS Mojave. I've restarted clamd and ClamXAV. Is this likely a ClamXAV issue?

**Comment by docdyhr** [comment]
I am using the Mac version ClamXAV and I got a lot of false positives. Does anyone know the relevance of "Archive.Test.Agent2-9953724-0" ?

**Comment by mjbroekman** [comment]
If you are still seeing this, make sure to update your virus definitions.

Archive.Test was a test signature that was accidentally published and then removed. If you are still seeing it, it's because the virus definitions haven't been updated since it was published.

**Comment by RealDrJ** [comment]
FYI my issue was that although the database was updated 4 days ago according to this thread, the corrections were not pulled by my copy of ClamXAV for 3 addl days, despite the app reporting otherwise. I will address this unacceptable oversight with those developers.
