### ISSUE TITLE
Freshclam does not download daily.cvd file causing private mirror rate-limit false-positive

### ISSUE THREAD

**Issue by mvs5465** [Cisco-Talos/clamav#622]
Freshclam fails to download or persist the file called "daily.cvd" from upstream. This causes a cascade of issues. Note that the daily.cvd file actually exists on the `clamav/clamav:latest` docker image, but **the file gets deleted by running freshclam.**

This issue is further compounded when we try to download the files from our private mirror again using freshclam. Since the daily.cvd file doesn't exist, our private mirror returns 403. This then causes freshclam to think it is getting rate limited, and the definition update fails.

Describe the bug
----------------

We use freshclam to populate a private mirror, but it fails to download or persist daily.cvd. Then when we use freshclam again to download definition updates from our private mirror, it fails because daily.cvd is missing. Since we use Cloudfront to host these files from S3, a missing file returns the error code 403. This error code then tricks freshclam into thinking it got rate limited, compounding the issue further.

How to reproduce the problem
----------------------------

1. Run the clamav:latest docker image in interactive mode:

```
$ docker run --rm -it --entrypoint="/bin/sh" clamav/clamav:latest
```

2. Inside the container, navigate to the `/var/lib/clamav` directory and note the presence of the daily.cvd file:
```
# cd /var/lib/clamav
# ls 
bytecode.cvd  daily.cvd     main.cvd
```

3. Run the command `freshclam` inside the container, and then list the files after it runs. **Note that the daily.cvd file is gone.**
```
# ls
bytecode.cvd   daily.cld      freshclam.dat  main.cvd
```

4. Upload the new definitions files to your private mirror:
```
# aws s3 sync /var/lib/clamav s3://${MIRROR_BUCKET_NAME}
```

5. Download the new definitions files from the private mirror by running freshclam with a config to point at your private mirror. This is where the error occurs.
```
WARNING: Can't download daily.cvd from https://{private-mirror-address}/daily.cvd
WARNING: FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
WARNING: You are on cool-down until after: 2022-06-29 03:58:31
```

Summary
---------

Is the daily.cvd file meant to be mirrored? If so, why does freshclam delete it?

**Comment by micahsnyder** [comment]
This is normal behavior. 

When freshclam updates the `.cvd` databases, it does so using `.cdiff` patch files.  This process replaces the original `.cvd` database archive with a `.cld` database archive.  The `.cld` file is a decompressed and unsigned version of the `.cvd` database that has been updated using one or more `.cdiff` files.  Additional updates to the `.cld` will replace the old `.cld` with a new `.cld`.  

The `.cdiff` patching process that results in the `.cld` equivalent archive saves us a considerable amount of data costs, and we highly discourage any attempt to work around it or download the whole `.cvd` file for daily updates. 

The clamav database directory should only ever contain the CVD or CLD version of `daily`, `main`, and `bytecode` database archives, plus any additional files such as the `freshclam.dat` file, and any third-party/custom database files which are usually like `.ldb`, `.ndb`, `.hdb`, etc.
