### ISSUE TITLE
ClamAV 105.1 Rust 1.62.1 tiff::decoder::Decoder range start index out of range for slice of length

### ISSUE THREAD

**Issue by Donwulff** [Cisco-Talos/clamav#665]
thread '<unnamed>' panicked at 'range start index 741762 out of range for slice of length 719838', library/core/src/slice/index.rs:52:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::slice::index::slice_start_index_len_fail_rt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:52:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
   4: core::intrinsics::const_eval_select
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/intrinsics.rs:2372:5
   5: core::slice::index::slice_start_index_len_fail
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:42:9
   6: tiff::decoder::DecodingResult::as_buffer
   7: tiff::decoder::Decoder<R>::read_image
             at ./libclamav_rust/.cargo/vendor/tiff/src/decoder/mod.rs:1230:17
   8: <image::codecs::tiff::TiffDecoder<R> as image::image::ImageDecoder>::read_image
             at ./libclamav_rust/.cargo/vendor/image/./src/codecs/tiff.rs:222:15
   9: image::image::decoder_to_vec
             at ./libclamav_rust/.cargo/vendor/image/./src/image.rs:587:5
  10: image::dynimage::decoder_to_image
             at ./libclamav_rust/.cargo/vendor/image/./src/dynimage.rs:1025:23
  11: image::dynimage::DynamicImage::from_decoder
             at ./libclamav_rust/.cargo/vendor/image/./src/dynimage.rs:175:9
  12: <image::io::free_functions::load_inner::LoadVisitor as image::io::free_functions::DecoderVisitor>::visit_decoder
             at ./libclamav_rust/.cargo/vendor/image/./src/io/free_functions.rs:107:13
  13: image::io::free_functions::load_decoder
             at ./libclamav_rust/.cargo/vendor/image/./src/io/free_functions.rs:64:37
  14: image::io::free_functions::load_inner
             at ./libclamav_rust/.cargo/vendor/image/./src/io/free_functions.rs:111:5
  15: image::io::free_functions::load
             at ./libclamav_rust/.cargo/vendor/image/./src/io/free_functions.rs:37:5
  16: image::dynimage::load_from_memory_with_format
             at ./libclamav_rust/.cargo/vendor/image/./src/dynimage.rs:1221:5
  17: image::dynimage::load_from_memory
             at ./libclamav_rust/.cargo/vendor/image/./src/dynimage.rs:1206:5
  18: clamav_rust::fuzzy_hash::fuzzy_hash_calculate_image
             at ./libclamav_rust/src/fuzzy_hash.rs:412:20
  19: fuzzy_hash_calculate_image
             at ./libclamav_rust/src/fuzzy_hash.rs:213:23
  20: calculate_fuzzy_image_hash
             at ./libclamav/scanners.c:4088:10
  21: cli_magic_scan
             at ./libclamav/scanners.c:4722:19
  22: cli_magic_scan_desc_type
             at ./libclamav/scanners.c:5073:14
  23: unz
             at ./libclamav/unzip.c:357:15
  24: cli_unzip
             at ./libclamav/unzip.c:1277:27
  25: cli_magic_scan
             at ./libclamav/scanners.c:4491:23
  26: scan_common
             at ./libclamav/scanners.c:5419:14
  27: cl_scandesc_callback
             at ./libclamav/scanners.c:5595:14
  28: cl_scanfile_callback
             at ./libclamav/scanners.c:5690:11
  29: scan_callback
             at ./clamd/scanner.c:270:24
  30: handle_entry
             at ./libclamav/others_common.c:668:16
  31: cli_ftw
             at ./libclamav/others_common.c:752:14
  32: command
             at ./clamd/session.c:378:11
  33: scanner_thread
             at ./clamd/server-th.c:126:11
  34: thrmgr_worker
             at ./clamd/thrmgr.c:703:13
  35: start_thread
  36: clone

This is an older system (Oracle Linux 6) so other dependencies aren't necessarily up to date, rust via rustup and compiled with Software Collections gcc-8.3. Edit: This happens with just the official signatures alone, reproducible on a given TIFF file standalone with clamd & clamscan.

**Comment by micahsnyder** [comment]
Hi @Donwulff looks like this is the same issue as #662, so I'll close it as a duplicate.

It looks like the image-rs/image-tiff project are working on it. Hopefully we can re-publish with an updated version of the affected library soon.
