### ISSUE TITLE
Please extend the life of version 103 indefinitely or drop Rust in 106

### ISSUE THREAD

**Issue by kjpetrie** [Cisco-Talos/clamav#677]
Describe the bug
----------------

Replace this text with a clear and concise description of the bug or feature request.

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by kjpetrie** [comment]
When bulk-building packages for Linux repositories or FreeBSD servers, processor time is precious and we cannot afford the 3-6 hours it takes to build Rust before we can build Clamav. It is therefore imperative, if Clamav is to continue to be useful on such platforms, that a version which is not reliant on Rust should remain available.

That either means extending the life of version 103, currently supported for another year, or removing the build dependency in future versions. Otherwise this huge overhead will mean Clamav will have to be abandoned by system administrators as too expensive to maintain on their systems.

It's not so much a bug as a practical reality.

**Comment by micahsnyder** [comment]
Is there some reason you cannot use either:
A) the rust compiler provided by rustup (https://www.rust-lang.org/tools/install)?
B) the rust packages provided freebsd and linux package maintainers?

**Comment by kjpetrie** [comment]
It would be tedious to make special workarounds for individual packages, especially ones of marginal usefulness. On reviewing my mail logs I have found Clamav has not caught a single message going through my server in the last week. Virus mail is a subset of spam and appears to be successfully intercepted by general spam filtering methods which operate before Clamav is consulted and are evidently sufficient to prevent it reaching Clamav. In view of that my remedy is obvious, and I have removed Clamav from my systems and will no longer have to build it.

**Comment by micahsnyder** [comment]
Fair enough :).  Take care.

For everyone else:  

Rust is the language that our team enjoys now, and that we have a lot of confidence in.  I am looking forward to the future where we will do more and more in Rust. Given the size of this project and the size of our team, I'm not sure if we can ever put C completely behind us, but I can cross my fingers.🤞

The new fuzzy image hash detection mechanism (one of two ClamAV features now implemented in Rust) is quite important to us.  Further, C was great in its time but has not aged well.  The Unix/Linux package management model is essentially a C library package management ecosystem.  Rust is certainly not the first of newer languages to find it difficult to work with legacy C/Unix package distribution models.  

OpenSUSE is one distribution that is putting a lot of thought into how to package Rust and Rust-based applications.  The Rust package maintainer for OpenSUSE gave a pretty good talk about it at RustConf last week.  I wish the video were available to share now, but it is still private for conference attendees only.

**Comment by teoberi** [comment]
> It would be tedious to make special workarounds for individual packages, especially ones of marginal usefulness. On reviewing my mail logs I have found Clamav has not caught a single message going through my server in the last week. Virus mail is a subset of spam and appears to be successfully intercepted by general spam filtering methods which operate before Clamav is consulted and are evidently sufficient to prevent it reaching Clamav. In view of that my remedy is obvious, and I have removed Clamav from my systems and will no longer have to build it.
