### ISSUE TITLE
Freshclam does not detect corrupted database files

### ISSUE THREAD

**Issue by hebelal** [Cisco-Talos/clamav#689]
Hi,

We're using the latest clamav docker image (0.105).
Somehow our virus signature files end up in a corrupted state.
That means our main.cvd file is missing some parts (size of our main.cvd = 150MB, size of the actual main.cvd when downloaded newly = 170MB).
However freshclam does neither update the file correctly nor throw an error.
We detect that our signatures are corrupted when starting clamd.
Clamd does fail with:
```
LibClamAV Error: Can't load /opt/local/share/clamav/main.cvd: Can't verify database integrity
LibClamAV Error: cli_loaddbdir: error loading database /opt/local/share/clamav/main.cvd
ERROR: Can't verify database integrity
```
Is there a way to verify the signatures without using clamd?

Reproduce:
1. Download the newest signatures via freshclam.
2. Manipulate the main.cvd by doing `truncate -s -1000 main.cvd`
3. run freshclam -> does not throw error and will no longer be able to put signatures into a valid state
4. run clamd -> throws error

**Comment by dirtyharrycallahan** [comment]
```
[root@localhost tmp]# sigtool -i main.cvd
File: main.cvd
Build time: 16 Sep 2021 08:32 -0400
Version: 62
Signatures: 6647427
Functionality level: 90
Builder: sigmgr
MD5: 137eccce31aacb21b5a98bb8c21cefd6
Digital signature: twaJBls8V5q64R7QY10AatEtPNuPWoVoxTaNO1jpBg7s5jIMMXpitgG1000YLp6rb0TWkEKjRqxneGTxuxWaWm7XBjsgwX2BRWh/y4fhs7uyImdKRLzQ5y8e2EkSChegF/i8clqfn+1qetq9j4gbktJ3JZpOXPoHlyr2Dv9S/Bg
tVerification OK.
[root@localhost tmp]# truncate -s -1000 main.cvd 
[root@localhost tmp]# sigtool -i main.cvd
File: main.cvd
Build time: 16 Sep 2021 08:32 -0400
Version: 62
Signatures: 6647427
Functionality level: 90
Builder: sigmgr
MD5: 137eccce31aacb21b5a98bb8c21cefd6
Digital signature: twaJBls8V5q64R7QY10AatEtPNuPWoVoxTaNO1jpBg7s5jIMMXpitgG1000YLp6rb0TWkEKjRqxneGTxuxWaWm7XBjsgwX2BRWh/y4fhs7uyImdKRLzQ5y8e2EkSChegF/i8clqfn+1qetq9j4gbktJ3JZpOXPoHlyr2Dv9S/Bg
ERROR: cvdinfo: Verification: Can't verify database integrity
[root@localhost tmp]#

**Comment by hebelal** [comment]
Cool, Thanks for the fast response!
