### ISSUE TITLE
Clamav-Development: ERROR: Malformed database

### ISSUE THREAD

**Issue by Salted-Fries** [Cisco-Talos/clamav#697]
Hi there,

since last Friday the ClamAV-Development Branch stopped working.
Today I switched to v0.105.1 which just worked fine.
Heres the clamd.log:
`...`
`Mon Sep 12 03:01:13 2022 -> +++ Started at Mon Sep 12 03:01:13 2022`
`Mon Sep 12 03:01:14 2022 -> Received 0 file descriptor(s) from systemd.`
`Mon Sep 12 03:01:14 2022 -> clamd daemon 1.0.0-devel-20220911 (OS: Linux, ARCH: x86_64, CPU: x86_64)`
`Mon Sep 12 03:01:14 2022 -> Log file size limited to 16777216 bytes.`
`Mon Sep 12 03:01:14 2022 -> Reading databases from /usr/share/clamav`
`Mon Sep 12 03:01:14 2022 -> Not loading PUA signatures.`
`Mon Sep 12 03:01:14 2022 -> Bytecode: Security mode set to "TrustSigned".`
`Mon Sep 12 03:01:16 2022 -> ERROR: Malformed database`
`Mon Sep 12 04:15:52 2022 -> +++ Started at Mon Sep 12 04:15:52 2022`
`Mon Sep 12 04:15:52 2022 -> Received 0 file descriptor(s) from systemd.`
`Mon Sep 12 04:15:52 2022 -> clamd daemon 1.0.0-devel-20220912 (OS: Linux, ARCH: x86_64, CPU: x86_64)`
`Mon Sep 12 04:15:52 2022 -> Log file size limited to 16777216 bytes.`
`Mon Sep 12 04:15:52 2022 -> Reading databases from /usr/share/clamav`
`Mon Sep 12 04:15:52 2022 -> Not loading PUA signatures.`
`Mon Sep 12 04:15:52 2022 -> Bytecode: Security mode set to "TrustSigned".`
`Mon Sep 12 04:15:53 2022 -> ERROR: Malformed database`
`Mon Sep 12 11:36:15 2022 -> +++ Started at Mon Sep 12 11:36:15 2022`
`Mon Sep 12 11:36:15 2022 -> Received 0 file descriptor(s) from systemd.`
`Mon Sep 12 11:36:15 2022 -> clamd daemon 0.105.1 (OS: Linux, ARCH: x86_64, CPU: x86_64)`
`Mon Sep 12 11:36:15 2022 -> Log file size limited to 16777216 bytes.`
`Mon Sep 12 11:36:15 2022 -> Reading databases from /usr/share/clamav`
`Mon Sep 12 11:36:15 2022 -> Not loading PUA signatures.`
`Mon Sep 12 11:36:15 2022 -> Bytecode: Security mode set to "TrustSigned".`
`Mon Sep 12 11:36:31 2022 -> Loaded 6803676 signatures.`
`...`

...and clam.upgrade.log:
`-- Installing: /usr/share/man/man8/clamonacc.8`
`LibClamAV Error: cli_loadldb: The number of subsignatures (== 4) doesn't match the IDs in the logical expression (== 5)`
`LibClamAV Error: Problem parsing database at line 636`
`LibClamAV Error: Can't load main.ldb: Malformed database`
`LibClamAV Error: cli_tgzload: Can't load main.ldb`
`LibClamAV Error: Can't load /usr/share/clamav/main.cld: Malformed database`
`LibClamAV Error: cli_loaddbdir: error loading database /usr/share/clamav/main.cld`
`ERROR: Mon Sep 12 04:15:53 2022 -> Malformed database`
`ClamAV 1.0.0-devel-20220912`

...and heres how i've compiled the dev-branch daily till today:

`echo Starting download of new Clam-AV development release...`
`sleep 1`
`mkdir -p /usr/src/packages/CLAM-AV/Development-Releases`
`cd /usr/src/packages/CLAM-AV/Development-Releases`
`# wget http://www.clamav.net/snapshot/clamav-devel-latest.tar.gz`
`git clone https://github.com/vrtadmin/clamav-devel`
`#`
`# compilation section...`
`#`
`echo configuring and compiling the new clamav package...`
`sleep 1`
`cd /usr/src/packages/CLAM-AV/Development-Releases/clamav-devel/cmake`
`#./autogen.sh`
`#./configure --prefix=/usr --sysconfdir=/etc --with-pcre --enable-all-jit-targets --enable-clamdtop --disable-clamuko --disable-dsig && make`
`cat > /usr/src/packages/CLAM-AV/Development-Releases/clamav-devel/cmake/clam.cmake.sh << "EOF"`
`cmake .. -G Ninja                              \`
 `   -D CMAKE_BUILD_TYPE="Debug"                \`
 `   -D OPTIMIZE=OFF                            \`
 `   -D CMAKE_INSTALL_PREFIX=/usr               \`
 `   -D CMAKE_INSTALL_SYSCONFDIR=/etc           \`
 `   -D CMAKE_INSTALL_LOCALSTATEDIR=/var        \`
 `   -D CMAKE_INSTALL_RUNSTATEDIR=/var/run      \`
 `   -D ENABLE_MILTER=ON                        \`
 `   -D ENABLE_EXAMPLES=ON                      \`
 `   -D ENABLE_STATIC_LIB=ON                    \`
 `   -D ENABLE_SYSTEMD=OFF                      \`
`&& sed -i 's!/usr/etc!/etc!g' clamav-config.h`
`EOF`
`chmod +x /usr/src/packages/CLAM-AV/Development-Releases/clamav-devel/cmake/clam.cmake.sh`
`/usr/src/packages/CLAM-AV/Development-Releases/clamav-devel/cmake/clam.cmake.sh`
`sed -i 's!/usr/etc!/etc!g' install_manifest.txt`
`ninja`
`echo stopping clamd...`
`service clamd stop`
`sleep 3`
`ninja install`
`sleep 2`
`service clamd start`

Any help is wellcome... 
btw. i've filed a very similar bug in March 2022: https://github.com/Cisco-Talos/clamav/issues/494
Thanks :-)

**Comment by micahsnyder** [comment]
Hi @Salted-Fries thanks for the report.  Yes we accidentally broke it a few days ago.  This PR will fix it https://github.com/Cisco-Talos/clamav/pull/696

**Comment by micahsnyder** [comment]
This should be fixed now.
