### ISSUE TITLE
AUSTOR ClamAV App Scan Broken

### ISSUE THREAD

**Issue by kculpepperhpc** [Cisco-Talos/clamav#707]
We have an AUSTOR NAS and ClamAV is the only virus scanner available on it.  When we first setup our NAS, the virus scan ran fine, but since 2022, no scan finishes.  The time counter goes up, but no files scanned count and it never finishes.  We let one run 137 hours and it never finished.  Started a new scan on Wednesday, and it hasn't finished yet either.

**Comment by micahsnyder** [comment]
@kculpepperhpc I'm sorry to hear this.  Unfortunately we don't know anything about Austor products, how they have configured ClamAV, etc.  You will have to contact Austor for support.

**Comment by micahsnyder** [comment]
@kculpepperhpc I'm unsure if this will help.  One thing that did change at the beginning of 2022 was an end to support for some older ClamAV versions: https://blog.clamav.net/2021/12/reminder-clamav-0102-0101-end-of-life.html

If the ClamAV version on your NAS is past end-of-life, it will not be able to update the signature databases.  That should not prevent it from scanning with the (very) dated signature databases it already has.  But again, I don't know how Austor devices are configured, etc.  You should seek help from their product support.
