### ISSUE TITLE
Can't download main.cvd from database.clamav.net

### ISSUE THREAD

**Issue by one-vkhare1** [Cisco-Talos/clamav#713]
Hi Team, 
When we are trying to install Clamav instance, it is not able to download db for clamav. We are getting below exception.

Mon Oct  3 13:03:36 2022 -> *Current working dir is /clamav-db
Mon Oct  3 13:03:36 2022 -> *Max retries == 3
Mon Oct  3 13:03:36 2022 -> ClamAV update process started at Mon Oct  3 13:03:36 2022
Mon Oct  3 13:03:36 2022 -> *Using IPv6 aware code
Mon Oct  3 13:03:36 2022 -> *Querying current.cvd.clamav.net
Mon Oct  3 13:03:36 2022 -> *TTL: 1575
Mon Oct  3 13:03:36 2022 -> *Software version from DNS: 0.103.7
Mon Oct  3 13:03:36 2022 -> ^Your ClamAV installation is OUTDATED!
Mon Oct  3 13:03:36 2022 -> ^Local version: 0.100.3 Recommended version: 0.103.7
Mon Oct  3 13:03:36 2022 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Mon Oct  3 13:03:36 2022 -> *Retrieving http://db.local.clamav.net/main.cvd
Mon Oct  3 13:03:36 2022 -> *Ignoring mirror 104.16.218.84 (due to previous errors)
Mon Oct  3 13:03:36 2022 -> *Ignoring mirror 104.16.219.84 (due to previous errors)
Mon Oct  3 13:03:36 2022 -> nonblock_connect: connect(): fd=4 errno=99: Address not available
Mon Oct  3 13:03:36 2022 -> Can't connect to port 80 of host db.local.clamav.net (IP: 2606:4700::6810:da54)
Mon Oct  3 13:03:36 2022 -> *Ignoring mirror 104.16.218.84 (due to previous errors)
Mon Oct  3 13:03:36 2022 -> *Ignoring mirror 104.16.219.84 (due to previous errors)
Mon Oct  3 13:03:36 2022 -> Trying host db.local.clamav.net (2606:4700::6810:db54)...
Mon Oct  3 13:03:36 2022 -> nonblock_connect: connect(): fd=4 errno=99: Address not available
Mon Oct  3 13:03:36 2022 -> Can't connect to port 80 of host db.local.clamav.net (IP: 2606:4700::6810:db54)
Mon Oct  3 13:03:36 2022 -> *Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Mon Oct  3 13:03:36 2022 -> ^Can't download main.cvd from db.local.clamav.net
Mon Oct  3 13:03:36 2022 -> Trying again in 5 secs...
Mon Oct  3 13:03:41 2022 -> ClamAV update process started at Mon Oct  3 13:03:41 2022
Mon Oct  3 13:03:41 2022 -> *Using IPv6 aware code
Mon Oct  3 13:03:41 2022 -> *Querying current.cvd.clamav.net
Mon Oct  3 13:03:41 2022 -> *TTL: 1800
Mon Oct  3 13:03:41 2022 -> *Software version from DNS: 0.103.7
Mon Oct  3 13:03:41 2022 -> ^Your ClamAV installation is OUTDATED!
Mon Oct  3 13:03:41 2022 -> ^Local version: 0.100.3 Recommended version: 0.103.7
Mon Oct  3 13:03:41 2022 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Mon Oct  3 13:03:41 2022 -> *Retrieving http://db.local.clamav.net/main.cvd
Mon Oct  3 13:03:41 2022 -> *Ignoring mirror 104.16.218.84 (due to previous errors)
Mon Oct  3 13:03:41 2022 -> *Ignoring mirror 104.16.219.84 (due to previous errors)
Mon Oct  3 13:03:41 2022 -> *Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Mon Oct  3 13:03:41 2022 -> *Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
Mon Oct  3 13:03:41 2022 -> ^Can't download main.cvd from db.local.clamav.net
Mon Oct  3 13:03:41 2022 -> Trying again in 5 secs...
Mon Oct  3 13:03:46 2022 -> ClamAV update process started at Mon Oct  3 13:03:46 2022
Mon Oct  3 13:03:46 2022 -> *Using IPv6 aware code
Mon Oct  3 13:03:46 2022 -> *Querying current.cvd.clamav.net
Mon Oct  3 13:03:46 2022 -> *TTL: 1800
Mon Oct  3 13:03:46 2022 -> *Software version from DNS: 0.103.7
Mon Oct  3 13:03:46 2022 -> ^Your ClamAV installation is OUTDATED!
Mon Oct  3 13:03:46 2022 -> ^Local version: 0.100.3 Recommended version: 0.103.7
Mon Oct  3 13:03:46 2022 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Mon Oct  3 13:03:46 2022 -> *Retrieving http://db.local.clamav.net/main.cvd
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 104.16.218.84 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 104.16.219.84 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> !Can't download main.cvd from db.local.clamav.net
Mon Oct  3 13:03:46 2022 -> Giving up on db.local.clamav.net...
Mon Oct  3 13:03:46 2022 -> ClamAV update process started at Mon Oct  3 13:03:46 2022
Mon Oct  3 13:03:46 2022 -> *Using IPv6 aware code
Mon Oct  3 13:03:46 2022 -> *Querying current.cvd.clamav.net
Mon Oct  3 13:03:46 2022 -> *TTL: 1800
Mon Oct  3 13:03:46 2022 -> *Software version from DNS: 0.103.7
Mon Oct  3 13:03:46 2022 -> ^Your ClamAV installation is OUTDATED!
Mon Oct  3 13:03:46 2022 -> ^Local version: 0.100.3 Recommended version: 0.103.7
Mon Oct  3 13:03:46 2022 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Mon Oct  3 13:03:46 2022 -> *Retrieving http://database.clamav.net/main.cvd
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 104.16.218.84 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 104.16.219.84 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 2606:4700::6810:da54 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> *Ignoring mirror 2606:4700::6810:db54 (due to previous errors)
Mon Oct  3 13:03:46 2022 -> !Can't download main.cvd from database.clamav.net
Mon Oct  3 13:03:46 2022 -> Giving up on database.clamav.net...

**Comment by micahsnyder** [comment]
@one-vkhare1 it looks like you're using a very old version of ClamAV that is explicitly blocked from updating:
```
Mon Oct 3 13:03:36 2022 -> ^Your ClamAV installation is OUTDATED!
Mon Oct 3 13:03:36 2022 -> ^Local version: 0.100.3 Recommended version: 0.103.7
```

You will need to upgrade your installation. Please see https://docs.clamav.net/faq/faq-eol.html
