### ISSUE TITLE
How to deal with these errors reported by clamd?

### ISSUE THREAD

**Issue by jpahullo** [Cisco-Talos/clamav#737]
Errors reported
----------------

We have started using clamd as a service and connect to it via TCP connection. Since then, we are facing these kind of errors. The following lines are reported in our production system from the last couple of days:

```
1160  LibClamAV Warning: cli_codepage_to_utf8: Failed to open iconv.
     29  LibClamAV Warning: Bytecode 78 failed to run: Exceeded time limit
     14  LibClamAV Warning: Bytecode run timed out in interpreter after 5000 opcodes
      4  LibClamAV Warning: Bytecode run timed out in interpreter after 25000 opcodes
      4  LibClamAV Warning: Bytecode run timed out in interpreter after 10000 opcodes
      2  LibClamAV Warning: Bytecode run timed out in interpreter after 20000 opcodes
      1  LibClamAV Warning: Bytecode run timed out in interpreter after 55000 opcodes
      1  LibClamAV Warning: Bytecode run timed out in interpreter after 45000 opcodes
      1  LibClamAV Warning: Bytecode run timed out in interpreter after 40000 opcodes
      1  LibClamAV Warning: Bytecode run timed out in interpreter after 35000 opcodes
      1  LibClamAV Warning: Bytecode run timed out in interpreter after 15000 opcodes
      1  LibClamAV Error: cli_realloc(): Attempt to allocate 191102976 bytes. Please report to https://github.com/Cisco-Talos/clamav/issues
      1  LibClamAV Error: cli_pdf: cannot reallocate memory for decoded output
```

Is there anything that we have dismissed or misconfigured?

We are using the docker image, limiting the memory usage to 1,5GiB (never reaching to that amount of memory), with this version and settings:

```
/ # clamconf 
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
AlertExceedsMax disabled
PreludeEnable disabled
PreludeAnalyzerName disabled
LogFile = "/var/log/clamav/clamd.log"
LogFileUnlock disabled
LogFileMaxSize = "1048576"
LogTime = "yes"
LogClean disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate disabled
ExtendedDetectionInfo disabled
PidFile = "/run/lock/clamd.pid"
TemporaryDirectory disabled
DatabaseDirectory = "/var/lib/clamav"
OfficialDatabaseOnly disabled
LocalSocket = "/run/clamav/clamd.sock"
LocalSocketGroup disabled
LocalSocketMode disabled
FixStaleSocket = "yes"
TCPSocket = "3310"
TCPAddr = "0.0.0.0"
MaxConnectionQueueLength = "200"
StreamMaxLength = "734003200"
StreamMinPort = "1024"
StreamMaxPort = "2048"
MaxThreads = "10"
ReadTimeout = "120"
CommandReadTimeout = "30"
SendBufTimeout = "500"
MaxQueue = "100"
IdleTimeout = "30"
ExcludePath disabled
MaxDirectoryRecursion = "15"
FollowDirectorySymlinks disabled
FollowFileSymlinks disabled
CrossFilesystems = "yes"
SelfCheck = "600"
ConcurrentDatabaseReload = "yes"
DisableCache disabled
VirusEvent disabled
ExitOnOOM disabled
AllowAllMatchScan = "yes"
Foreground disabled
Debug disabled
LeaveTemporaryFiles disabled
User = "clamav"
Bytecode = "yes"
BytecodeSecurity = "TrustSigned"
BytecodeTimeout = "190000"
BytecodeUnsigned disabled
BytecodeMode = "Auto"
DetectPUA disabled
ExcludePUA disabled
IncludePUA disabled
ScanPE = "yes"
ScanELF = "yes"
ScanMail = "yes"
ScanPartialMessages disabled
PhishingSignatures = "yes"
PhishingScanURLs = "yes"
HeuristicAlerts = "yes"
HeuristicScanPrecedence disabled
StructuredDataDetection disabled
StructuredMinCreditCardCount = "3"
StructuredMinSSNCount = "3"
StructuredSSNFormatNormal = "yes"
StructuredSSNFormatStripped disabled
ScanHTML = "yes"
ScanOLE2 = "yes"
AlertBrokenExecutables disabled
AlertBrokenMedia disabled
AlertEncrypted disabled
StructuredCCOnly disabled
AlertEncryptedArchive disabled
AlertEncryptedDoc disabled
AlertOLE2Macros disabled
AlertPhishingSSLMismatch disabled
AlertPhishingCloak disabled
AlertPartitionIntersection disabled
ScanPDF = "yes"
ScanSWF = "yes"
ScanXMLDOCS = "yes"
ScanHWP3 = "yes"
ScanArchive = "yes"
ForceToDisk disabled
MaxScanTime disabled
MaxScanSize = "734003200"
MaxFileSize = "734003200"
MaxRecursion = "17"
MaxFiles = "10000"
MaxEmbeddedPE = "10485760"
MaxHTMLNormalize = "10485760"
MaxHTMLNoTags = "2097152"
MaxScriptNormalize = "5242880"
MaxZipTypeRcg = "1048576"
MaxPartitions = "50"
MaxIconsPE = "100"
MaxRecHWP3 = "16"
PCREMatchLimit = "100000"
PCRERecMatchLimit = "2000"
PCREMaxFileSize = "26214400"
OnAccessMountPath disabled
OnAccessIncludePath disabled
OnAccessExcludePath disabled
OnAccessExcludeRootUID disabled
OnAccessExcludeUID disabled
OnAccessExcludeUname disabled
OnAccessMaxFileSize = "5242880"
OnAccessDisableDDD disabled
OnAccessPrevention disabled
OnAccessExtraScanning disabled
OnAccessCurlTimeout = "5000"
OnAccessMaxThreads = "5"
OnAccessRetryAttempts disabled
OnAccessDenyOnError disabled
DevACOnly disabled
DevACDepth disabled
DevPerformance disabled
DevLiblog disabled
DisableCertCheck disabled
AlgorithmicDetection = "yes"
BlockMax disabled
PhishingAlwaysBlockSSLMismatch disabled
PhishingAlwaysBlockCloak disabled
PartitionIntersection disabled
OLE2BlockMacros disabled
ArchiveBlockEncrypted disabled

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "1048576"
LogTime disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate disabled
PidFile = "/run/lock/freshclam.pid"
DatabaseDirectory = "/var/lib/clamav"
Foreground disabled
Debug disabled
UpdateLogFile = "/var/log/clamav/freshclam.log"
DatabaseOwner = "clamav"
Checks = "12"
DNSDatabaseInfo = "current.cvd.clamav.net"
DatabaseMirror = "database.clamav.net"
PrivateMirror disabled
MaxAttempts = "3"
ScriptedUpdates = "yes"
TestDatabases = "yes"
CompressLocalDatabase disabled
ExtraDatabase disabled
ExcludeDatabase disabled
DatabaseCustomURL disabled
HTTPProxyServer disabled
HTTPProxyPort disabled
HTTPProxyUsername disabled
HTTPProxyPassword disabled
HTTPUserAgent disabled
NotifyClamd = "/etc/clamav/clamd.conf"
OnUpdateExecute disabled
OnErrorExecute disabled
OnOutdatedExecute disabled
LocalIPAddress disabled
ConnectTimeout = "30"
ReceiveTimeout disabled
Bytecode = "yes"

Config file: clamav-milter.conf
-------------------------------
LogFile = "/var/log/clamav/milter.log"
LogFileUnlock disabled
LogFileMaxSize = "1048576"
LogTime = "yes"
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate disabled
PidFile = "/run/lock/clamav-milter.pid"
TemporaryDirectory disabled
FixStaleSocket = "yes"
MaxThreads = "10"
ReadTimeout = "120"
Foreground disabled
User = "clamav"
MaxFileSize = "26214400"
ClamdSocket = "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock", "unix:/run/clamav/clamd.sock"
MilterSocket = "inet:7357"
MilterSocketGroup disabled
MilterSocketMode disabled
LocalNet disabled
OnClean = "Accept"
OnInfected = "Quarantine"
OnFail = "Defer"
RejectMsg disabled
AddHeader = "no"
ReportHostname disabled
VirusAction disabled
Chroot disabled
AllowList disabled
Whitelist disabled
SkipAuthenticated disabled
LogInfected disabled
LogClean disabled
SupportMultipleRecipients disabled

Software settings
-----------------
Version: 0.104.4
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /var/lib/clamav
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 12:32:42 2021
bytecode.cvd: version 333, sigs: 92, built on Mon Mar  8 15:21:51 2021
daily.cld: version 26701, sigs: 2009238, built on Thu Oct 27 07:54:47 2022
Total number of signatures: 8656757

Platform information
--------------------
uname: Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64
OS: Linux, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.12 (1.2.12), compile flags: a9
platform id: 0x0a21909008000000000b0201

Build information
-----------------
GNU C: 11.2.1 20220219 (11.2.1)
sizeof(void*) = 8
Engine flevel: 144, dconf: 144
```

There are 3 king of problems, I think:

1. iconv: using your docker image, I'd not expect facing this kind of error. I do not know if it is something from configuration or docker image definition.
2. bytecode execution time out: we extended the execution time a bit. We also defined the maximum file size to the limits we allow to submit in our Moodle instance (700MB).
3. memory allocation: unexpected.

We are using the docker image clamav/clamav:0.104_base.

How to reproduce the problem
----------------------------

We are using it integraded with a docker-compose.yml with our Moodle instance, having Moodle set up to connect via stream to clamav service.

Attachments
-----------

N/A

**Comment by micahsnyder** [comment]
Hi @jpahullo,

> `1160  LibClamAV Warning: cli_codepage_to_utf8: Failed to open iconv.`

This message indicates that clam could not convert some data from a specific encoding over to UTF8. There are a few places where we identify the codepage in either document metadata or document macro content and transcode it to UTF8 before we pattern match it. Sadly, this error message isn't very helpful and doesn't state which encoding failed. We should change that. Although even if it did print which encoding failed, I'm not sure what we could do about it. I'm inclined to also change the message to be a debug-level message since so it it isn't alarming.

> `  29  LibClamAV Warning: Bytecode 78 failed to run: Exceeded time limit`
> `  14  LibClamAV Warning: Bytecode run timed out in interpreter after 5000 opcodes`
> `   4  LibClamAV Warning: Bytecode run timed out in interpreter after 25000 opcodes`
> `   4  LibClamAV Warning: Bytecode run timed out in interpreter after 10000 opcodes`
> `   2  LibClamAV Warning: Bytecode run timed out in interpreter after 20000 opcodes`
> `   1  LibClamAV Warning: Bytecode run timed out in interpreter after 55000 opcodes`
> `   1  LibClamAV Warning: Bytecode run timed out in interpreter after 45000 opcodes`
> `   1  LibClamAV Warning: Bytecode run timed out in interpreter after 40000 opcodes`
> `   1  LibClamAV Warning: Bytecode run timed out in interpreter after 35000 opcodes`
> `   1  LibClamAV Warning: Bytecode run timed out in interpreter after 15000 opcodes`

These messages indicate that ClamAV was running a bytecode signature and that it exceeded a time limit. In the next feature version, it will print the bytecode signature name that was timed out. This is more common than I'd like, particularly with larger documents. You do not need to worry about these either. I am inclined to keep them at the "warning" verbosity level, so that once the bytecode signature names are printed in the newer version we'll more easily tell which bytecode signatures that may need to be refactored / optimized to reduce scan time. 

> `   1  LibClamAV Error: cli_realloc(): Attempt to allocate 191102976 bytes. Please report to https://github.com/Cisco-Talos/clamav/issues`
> `   1  LibClamAV Error: cli_pdf: cannot reallocate memory for decoded output`

This error indicates that when decompressing or extracting content from a file, the amount of data was larger than ClamAV's internal memory allocation threshold for allocations based on untrusted data.  We have reworded this message a bit in the new version, and have significantly increased the threshold.  Hopefully with the next ClamAV version, you will not see this message again.

Regards,
Micah

**Comment by jpahullo** [comment]
Thanks @micahsnyder,

From your kind words, I can understand that no tunning is required from our part, as incrementing execution time for bytecodes or increment some limit for allocating untrusted data, right now.

We have to wait for a new version to see more deteailed messages, so that we altogether can report any issue, and you can address them. Right?

Till now, I was worried to see these messages from our production system, and it let me think that some kind of potentially not verified files were uploaded to our Moodle site.

I'll register this internally, so that we keep it in mind.

Thanks for your time and help.

PS: I'm closing this ticket. If you think anything else we can share and try, please, reopen or share your thoughts.

Jordi

**Comment by micahsnyder** [comment]
Hi @jpahullo,

> We have to wait for a new version to see more deteailed messages, so that we altogether can report any issue, and you can address them. Right?

Hopefully, yes.  The bytecode signatures are created and maintained by our threat research team.  If we find that specific signatures are misbehaving, we can ask them to try to improve them. 

> Thanks for your time and help.

You're welcome.  Sorry for the alarming and confusing messages!

Regards,
Micah
