### ISSUE TITLE
external TomsFastMath unlikely to work for authententicode cert checking and maybe also database signature checking

### ISSUE THREAD

**Issue by micahsnyder** [Cisco-Talos/clamav#743]
Using an external TomsFastMath is expected to fail to verify trusted authenticode certificates. We had to increase the size of floating point numbers in TomsFastMath to fix the bug during 1.0 development, and an external TomsFastMath library is unlikely to have the non-default increased number size.

This concern was identified by @yasuhirokimura in https://github.com/Cisco-Talos/clamav/issues/736#issuecomment-1293572769 

I tried to test with external tomsfastmath library using the ubuntu 20.04 libtfm-dev package with our main branch, and indeed I observed the database load tests fail in the CTest libclamav tests.

**Comment by thesamesam** [comment]
Is there a bug report upstream you can link to asking them to change the defaults?
