### ISSUE TITLE
0.105 not compilable

### ISSUE THREAD

**Issue by Jau83741** [Cisco-Talos/clamav#753]
Due to the requirements of Rust in Clamav 0.105, and the fact that current Rust version do not support compilation from source in a straight forward fashion like any other standard language, it is currently not possible to compile Clamav 0.105 from source

**Comment by micahsnyder** [comment]
@Jau83741 can you provide some additional details?

How are you installing Rust?  
What version of Rust do you have?

A few of ClamAV's Rust-based library dependencies recently published updates and increased their minimum supported Rust version to 1.61.  

If you are building from this 0.105.1-3 package, the bundled Rust library source code has the newer 1.61+ requirement: https://www.clamav.net/downloads/production/clamav-0.105.1-3.tar.gz

If you are building from this 0.105.1-2 package, the bundled Rust library source is about 2 weeks older, and should have lower requirements: https://www.clamav.net/downloads/production/clamav-0.105.1-2.tar.gz.  But be advised that the `tiff` and `jpeg` libraries bundled in have a few bugs that could cause an abort crash (known as a "panic" in Rust lingo) when scanning certain malformed image files.

If you are building from a git clone of the `clamav-0.105.1` tag, then the build will require an internet connection, and the latest version of the Rust libraries will be downloaded during the build, so it will also require Rust version 1.61 or newer.

**Comment by Jau83741** [comment]
To compile current version Rust 1.65 from source, the makefile downloads a binary version of Rust 1.65 and then compiles the source of 1.65 with the sideloaded binary.
There might be (complex) workarounds for bootstrapping Rust from source which is possible to do for some people, but I dont see any documentation, and if there is one Im sure it will take much longer time to do.

So basically the current Rust source code do not support building from source, and anything compiled by rust - including ClamAV - is not going to be an actual verified build from source either.

**Comment by micahsnyder** [comment]
Why are you trying to build Rust from source?  I do not have any experience building Rust from source.  

The standard method for installing the Rust toolchain is here: https://rustup.rs/

**Comment by Kangie** [comment]
@Jau83741 I don't know what to tell you. I have both 0.105 and 1.0.0 (+ RCs!) compiled, packaged, and working on Gentoo (which is entirely source-based). We manage to build both Rust and ClamAV from source with no issues (though bootstrapping *any* language will require some kind of compiler binary!).

If you have concerns about that process perhaps you could compile Rust twice, the second time using the output of your first compilation. I don't pretend to understand your audit requirements, but it's what I'd do in your place.

This isn't a ClamAV bug though, Rust support has been a long time coming and is not optional. Dependency on Rust is a feature, not a bug.

**Comment by micahsnyder** [comment]
Thanks @Kangie for chiming in.  

I feel the same. I don't know what to tell you either which is why I failed to reply. Your inability to compile Rust from source to meet your audit requirements isn't something we can help with.  

Best of luck @Jau83741.
