### ISSUE TITLE
Latest version of docker image doesn't work

### ISSUE THREAD

**Issue by Dan0x54** [Cisco-Talos/clamav#754]
Describe the bug
----------------

When running clamav/clamav:latest using docker to scan a file, it complains with the message:

```
Error loading shared library libunwind.so.8: No such file or directory (needed by /usr/bin/clamscan)
```

When using clamav:0.104.1, I don't get the same issue and it runs normally.

How to reproduce the problem
----------------------------

To run with docker:
```bash
docker run -v $(pwd):/tmp/scandir -it clamav/clamav:latest clamscan--recursive /tmp/scandir
```

When run with previous working version:
```bash
docker run -v $(pwd):/tmp/scandir -it clamav/clamav:0.104.1 clamscan--recursive /tmp/scandir
```

**Comment by denyszrazhevskiy** [comment]
I have error
`Error loading shared library libunwind.so.8: No such file or directory (needed by /usr/bin/freshclam)`

**Comment by alastair-todd** [comment]
fwiw our .Net nClam ci/cd test code just stopped passing using the :stable docker image

**Comment by micahsnyder** [comment]
Hi everyone. I am working on fixing the issue.  I expect to publish the fixed image within an hour.  I'm sorry for the inconvenience.  I will update this issue as soon as it is fixed.

**Comment by micahsnyder** [comment]
The fixed image is published to Docker Hub: https://hub.docker.com/r/clamav/clamav/tags?page=1&ordering=last_updated
The following tags have been updated:
- [latest](https://hub.docker.com/layers/clamav/clamav/latest/images/sha256-7e37eeefa201497fb98eaae8b1b5f294e2dec39bdac80c2e508f345903d00649?context=explore)
- [stable](https://hub.docker.com/layers/clamav/clamav/stable/images/sha256-7e37eeefa201497fb98eaae8b1b5f294e2dec39bdac80c2e508f345903d00649?context=explore)
- [0.105](https://hub.docker.com/layers/clamav/clamav/0.105/images/sha256-7e37eeefa201497fb98eaae8b1b5f294e2dec39bdac80c2e508f345903d00649?context=explore)
- [0.105.1](https://hub.docker.com/layers/clamav/clamav/0.105.1/images/sha256-7e37eeefa201497fb98eaae8b1b5f294e2dec39bdac80c2e508f345903d00649?context=explore)
- [0.105.1-5](https://hub.docker.com/layers/clamav/clamav/0.105.1-5/images/sha256-7e37eeefa201497fb98eaae8b1b5f294e2dec39bdac80c2e508f345903d00649?context=explore)
- [latest_base](https://hub.docker.com/layers/clamav/clamav/latest_base/images/sha256-c4f6747be3b72f9263e0c9ec10d3947f1d64a9fc8c6183bde2d70acd5578ad22?context=explore)
- [stable_base](https://hub.docker.com/layers/clamav/clamav/stable_base/images/sha256-c4f6747be3b72f9263e0c9ec10d3947f1d64a9fc8c6183bde2d70acd5578ad22?context=explore)
- [0.105_base](https://hub.docker.com/layers/clamav/clamav/0.105_base/images/sha256-c4f6747be3b72f9263e0c9ec10d3947f1d64a9fc8c6183bde2d70acd5578ad22?context=explore)
- [0.105.1_base](https://hub.docker.com/layers/clamav/clamav/0.105.1_base/images/sha256-c4f6747be3b72f9263e0c9ec10d3947f1d64a9fc8c6183bde2d70acd5578ad22?context=explore)
- [0.105.1-5_base](https://hub.docker.com/layers/clamav/clamav/0.105.1-5_base/images/sha256-c4f6747be3b72f9263e0c9ec10d3947f1d64a9fc8c6183bde2d70acd5578ad22?context=explore)

I apologize for the trouble.

**Comment by micahsnyder** [comment]
I've pinned this issue for a few days, so it is easy to find.  

Pulling the latest images should resolve the issue.

**Comment by denyszrazhevskiy** [comment]
@micahsnyder 
Now container is starting, but not work
```
Socket for clamd not found yet, retrying (143/1800) ...2022-11-16T07:49:39.403773092Z Starting ClamAV
2022-11-16T07:49:39.406114296Z ERROR: Wed Nov 16 07:49:39 2022 -> Can't save PID to file /var/run/clamav/clamd.pid: No such file or directory
Socket for clamd not found yet, retrying (7/1800) ...2022-11-16T07:49:50.196224845Z Starting ClamAV
2022-11-16T07:49:50.198780461Z ERROR: Wed Nov 16 07:49:50 2022 -> Can't save PID to file /var/run/clamav/clamd.pid: No such file or directory
```

**Comment by micahsnyder** [comment]
@denyszrazhevskiy I think I

**Comment by denyszrazhevskiy** [comment]
My config in docker file
```
    clamv:
        container_name: clamav
        image: clamav/clamav:stable
        ports:
            - "3310:3310"
        environment:
            - CLAMAV_NO_MILTERD=true
            - CLAMAV_NO_FRESHCLAMD=true
        healthcheck:
            test: ["CMD", "clamdcheck.sh"]
            timeout: 5s
            interval: 5s
            retries: 30
        volumes:
            - ./clam:/etc/clamav
        networks:
            - nt
```

**Comment by filipagh** [comment]
@micahsnyder  thanks now its working for us (new release)

**Comment by micahsnyder** [comment]
@filipagh You found it fast!  I just published the updated images with the fix.  I'm glad to hear it's working for you now. 

The updated image tags are:
- [latest](https://hub.docker.com/layers/clamav/clamav/latest/images/sha256-1e793ff8a9a1fce004dfe2024f2bb1c0cefe94d4feed52115644fe2856e15bb9?context=explore)
- [stable](https://hub.docker.com/layers/clamav/clamav/stable/images/sha256-1e793ff8a9a1fce004dfe2024f2bb1c0cefe94d4feed52115644fe2856e15bb9?context=explore)
- [0.105](https://hub.docker.com/layers/clamav/clamav/0.105/images/sha256-1e793ff8a9a1fce004dfe2024f2bb1c0cefe94d4feed52115644fe2856e15bb9?context=explore)
- [0.105.1](https://hub.docker.com/layers/clamav/clamav/0.105.1/images/sha256-1e793ff8a9a1fce004dfe2024f2bb1c0cefe94d4feed52115644fe2856e15bb9?context=explore)
- [0.105.1-6](https://hub.docker.com/layers/clamav/clamav/0.105.1-6/images/sha256-1e793ff8a9a1fce004dfe2024f2bb1c0cefe94d4feed52115644fe2856e15bb9?context=explore)
- [latest_base](https://hub.docker.com/layers/clamav/clamav/latest_base/images/sha256-d3c6909351c98054567d07b4194e11325b0cc195462c9ce38561a6caeb77413a?context=explore)
- [stable_base](https://hub.docker.com/layers/clamav/clamav/stable_base/images/sha256-d3c6909351c98054567d07b4194e11325b0cc195462c9ce38561a6caeb77413a?context=explore)
- [0.105_base](https://hub.docker.com/layers/clamav/clamav/0.105_base/images/sha256-d3c6909351c98054567d07b4194e11325b0cc195462c9ce38561a6caeb77413a?context=explore)
- [0.105.1_base](https://hub.docker.com/layers/clamav/clamav/0.105.1_base/images/sha256-d3c6909351c98054567d07b4194e11325b0cc195462c9ce38561a6caeb77413a?context=explore)
- [0.105.1-6_base](https://hub.docker.com/layers/clamav/clamav/0.105.1-6_base/images/sha256-d3c6909351c98054567d07b4194e11325b0cc195462c9ce38561a6caeb77413a?context=explore)

I have observed one remaining problem with the new images.  `clamdtop` does not start.  
I will make a separate issue for the `clamdtop` issue and consider this issue resolved.

**Comment by micahsnyder** [comment]
Here's the new docker image `clamdtop` issue: https://github.com/Cisco-Talos/clamav/issues/758
