### ISSUE TITLE
CLAMAV Docker 0.105 Error loading shared library libunwind.so since new tag 15.11.22 9:05 AM

### ISSUE THREAD

**Issue by Neonell** [Cisco-Talos/clamav#756]
Hi everybody,

We noticed since the last docker image push 5 hours ago (15.11.2022, 9:05 AM) that the new image is missing a package:

Error loading shared library libunwind.so

https://hub.docker.com/layers/clamav/clamav/0.105/images/sha256-582694780c6d3f800dff0c5c4c6bcd74fceb13b8d84c816d518c13198d5a95c2

This image is no more functional.

It can be due to a change in the base image too, if the unix packages were removed. But even so I think if they are optional they should be now specifically download and added if required.

Hope this help and cheers and thank you for everything,
Frédéric

**Comment by niklasfi** [comment]
Hi, I can confirm the image is currently broken.

**Comment by JacekSmi** [comment]
Hi, We switch temporarily to using image tag 0.105.1-3 which is still working.

**Comment by vidup** [comment]
I confirm it's broken. We reverted to 1-1 and it works.

**Comment by micahsnyder** [comment]
Hi everyone.  The latest image is broken.  I am working to fix it as I type and expect we should be able to publish a fixed within less than an hour. 

This was also reported in https://github.com/Cisco-Talos/clamav/issues/754, so I will track the issue there.
