### ISSUE TITLE
LibClamAV Error: CRITICAL: fmap() failed - macOS Ventura on AARCH64

### ISSUE THREAD

**Issue by IComplainInComments** [Cisco-Talos/clamav#774]
Describe the bug
----------------

Running ClamAV from Macports results in the following error when the file being scanned is ~200MB
Two examples of the file formats would be a .MOV and a .sqlite database

`LibClamAV Error: cli_malloc(): Attempt to allocate 200081408 bytes. Please report to https://github.com/Cisco-Talos/clamav/issues
LibClamAV Warning: fmap: map allocation failed
LibClamAV Error: CRITICAL: fmap() failed`

How to reproduce the problem
----------------------------

launch clamd using `sudo clamd`
run the following in another terminal: `clamdscan -m -z /Users/<username here>/`
wait till it gets to the ~200MB file

Replace this text with the output from the ClamAV command:
`    Checking configuration files in /opt/local/etc

Config file: clamd.conf
-----------------------
PreludeAnalyzerName = "clamav"
LogFile = "/opt/local/var/log/clamav/clamd.log"
LogFileMaxSize = "2097152"
LogTime = "yes"
LogRotate = "yes"
ExtendedDetectionInfo = "yes"
PidFile = "/opt/local/var/run/clamav/clamd.pid"
TemporaryDirectory = "/opt/local/var/tmp"
DatabaseDirectory = "/opt/local/var/lib/clamav"
LocalSocket = "/opt/local/var/run/clamav/clamd.socket"
LocalSocketGroup = "clamav"
LocalSocketMode = "775"
MaxConnectionQueueLength = "30"
MaxThreads = "6"
ExcludePath = "^/Volumes/Files/", "^/Volumes/Time\ Machine/"
MaxDirectoryRecursion = "20"
VirusEvent = "no"
Foreground = "yes"
BytecodeTimeout = "190000"
StructuredMinCreditCardCount = "10"
StructuredMinSSNCount = "7"
StructuredCCOnly = "yes"
MaxScanSize = "4294967295"
MaxFileSize = "4294967295"
MaxRecursion = "20"
MaxFiles disabled
MaxIconsPE = "200"
PCREMatchLimit = "10000"
PCREMaxFileSize = "419430400"

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "2097152"
LogTime = "yes"
LogVerbose = "yes"
LogRotate = "yes"
PidFile = "/opt/local/var/run/clamav/"
DatabaseDirectory = "/opt/local/var/lib/clamav"
UpdateLogFile = "/opt/local/var/log/clamav/freshclam.log"
DatabaseMirror = "database.clamav.net"
MaxAttempts = "5"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.105.1
Optional features supported: AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /opt/local/var/lib/clamav
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 08:32:42 2021
bytecode.cvd: version 333, sigs: 92, built on Mon Mar  8 10:21:51 2021
daily.cld: version 26724, sigs: 2011402, built on Fri Nov 18 03:51:03 2022
Total number of signatures: 8658921

Platform information
--------------------
uname: Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root arm64
OS: Darwin, ARCH: arm64, CPU: arm64
zlib version: 1.2.13 (1.2.13), compile flags: a9
platform id: 0x040397970800000000040201

Build information
-----------------
Clang: Apple LLVM 14.0.0 (clang-1400.0.29.202) (4.2.1)
sizeof(void*) = 8
Engine flevel: 151, dconf: 151
`
Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
Thanks for the bug report @IComplainInComments 

I will attempt to replicate the issue soon.  I would not expect this error.

By the way, we increased the internal max allocation from ~182MB to 1GB for the next version (1.0.0).  And we changed the message a little bit to make it less alarming.  So if you do try with 1.0.0 you may find this issue changes to be for files over 1GB.  But still it shouldn't be having this error at all.  I'll see if I can figure out what is going wrong.

**Comment by micahsnyder** [comment]
Thinking about this some more -- it may be related to an issue where `mmap()` detection was failing on macOS, which is also fixed in for the upcoming 1.0.0 release by this commig https://github.com/Cisco-Talos/clamav/commit/197113cded7b3ae25dd6bd467d78c3db5765d2a5

So actually this issue may be resolved in the 1.0.0 release candidates even for files greater than 1GB, if you wish to try it.

**Comment by IComplainInComments** [comment]
> Thinking about this some more -- it may be related to an issue where `mmap()` detection was failing on macOS, which is also fixed in for the upcoming 1.0.0 release by this commig [197113c](https://github.com/Cisco-Talos/clamav/commit/197113cded7b3ae25dd6bd467d78c3db5765d2a5)
> 
> So actually this issue may be resolved in the 1.0.0 release candidates even for files greater than 1GB, if you wish to try it.

Thank you for looking into this!

I recently updated my version of ClamAV, and I will run it later today and let you know if we have a fix!

Thanks again!

**Comment by IComplainInComments** [comment]
Alright looks like this problem was indeed solved with the 1.0.0 update. Thank you guys for the help, and thanks for the 1.0.0 release!
