### ISSUE TITLE
Missing check for config_dir on arm Macs

### ISSUE THREAD

**Issue by tiiiecherle** [Cisco-Talos/clamav#784]
Describe the bug
----------------
Missing check for config_dir on arm Macs.

```
# Attempt to scan for a valid config dir
if [ -f "/etc/clamav-unofficial-sigs/master.conf" ] ; then
  config_dir="/etc/clamav-unofficial-sigs"
elif [ -f "/usr/local/etc/clamav-unofficial-sigs/master.conf" ] ; then
  config_dir="/usr/local/etc/clamav-unofficial-sigs/"
elif [ -f "/opt/zimbra/conf/clamav-unofficial-sigs/master.conf" ] ; then
  config_dir="/opt/zimbra/conf/clamav-unofficial-sigs/"
else
  xshok_pretty_echo_and_log "ERROR: config_dir (/etc/clamav-unofficial-sigs/master.conf) could not be found"
  exit 1
fi
```

The homebrew directory on arm Macs is 
```
brew --prefix
/opt/homebrew
```

If I understand correctly there should be another check
```
elif [ -f "/opt/homebrew/etc/clamav-unofficial-sigs/master.conf" ] ; then
  config_dir="/opt/homebrew/etc/clamav-unofficial-sigs/"
```

How to reproduce the problem
----------------------------

running `clamav-unofficial-sigs.sh` on arm Mac results in
```
==============================================================================
ERROR: config_dir (/etc/clamav-unofficial-sigs/master.conf) could not be found
==============================================================================
```

Thanks for fixing in advance

**Comment by micahsnyder** [comment]
@tiiiecherle I don't exactly follow what the issue is that you're reporting.
But this reads like an issue with the Homebrew package, which is a third party package defined in https://github.com/Homebrew/homebrew-core/blob/master/Formula/clamav.rb

If there is an issue with the Homebrew package, you should report it in their issue tracker.
