### ISSUE TITLE
LibClamAV Error: cli_loadldb: Failed to initialize target description block

### ISSUE THREAD

**Issue by FosterSM** [Cisco-Talos/clamav#792]
Starting clamd at boot gives the following error|:

Starting Clamd... LibClamAV Error: cli_loadldb: Failed to initialize target description block
LibClamAV Error: cli_loadldb: Failed to initialize target description block

How do I fix this please.

**Comment by ragusaa** [comment]
What version of clam are you running?  Are there corrupted files in your signature database?

**Comment by FosterSM** [comment]
clamav-0.105 is the version (built May  2  2022)
How do I know if there are corrupted files in my signature database ?

**Comment by ragusaa** [comment]
Could you try deleting your signature database directory (or change the location in your clamd.conf and freshclam.conf), redownload signatures with freshclam, see if this is still an issue?

**Comment by FosterSM** [comment]
freshclam returns the following:
--------------------------------------
freshclam daemon 0.105.0 (OS: Linux, ARCH: x86_64, CPU: x86_64)
ClamAV update process started at Fri Dec  9 00:26:30 2022
ERROR: Can't change dir to /opt/clamav/share/clamav/
ERROR: Can't create temporary directory /opt/clamav/share/clamav/tmp.d311bc0816
Hint: The database directory must be writable for UID 1001 or GID 1001
ERROR: Update failed.
--------------------------------------
 ls -tlr /opt/clamav/share/
total 12
drwxrwxrwx 5 clamav clamav 4096 May 19  2022 man
drwxrwxrwx 3 clamav clamav 4096 May 19  2022 doc
drw-rw-rw- 2 clamav clamav 4096 Dec  8 22:47 clamav

clamav UID is 1001, clamav GID is 1001

ls -tlr /opt/clamav/share/clamav/
total 4
-rw-rw-rw- 1 clamav clamav 69 Dec  8 22:47 freshclam.dat

root@Moira:/var/lib# ls -tlr clamav/
total 58944
-rw-r--r-- 1 clamav clamav 60352747 Dec  9 00:16 daily.cvd

**Comment by FosterSM** [comment]
This the last section from a strace run of freshclam:

....
openat(AT_FDCWD, "/usr/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
pread(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\1\0\1\300\4\0\0\0\33\0\0\0\0\0\0\0"..., 48, 2271848) = 48
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=20464304, ...}, 0x1000 /* AT_??? */) = 0
mmap(NULL, 2344896, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fd97c738000
mprotect(0x7fd97c7d9000, 1617920, PROT_NONE) = 0
mmap(0x7fd97c7d9000, 1167360, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xa1000) = 0x7fd97c7d9000
mmap(0x7fd97c8f6000, 446464, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1be000) = 0x7fd97c8f6000
mmap(0x7fd97c964000, 57344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22b000) = 0x7fd97c964000
mmap(0x7fd97c972000, 10176, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fd97c972000
close(3)                                = 0
mprotect(0x7fd97c964000, 45056, PROT_READ) = 0
mprotect(0x7fd97c9e3000, 4096, PROT_READ) = 0
mprotect(0x7fd97dc9c000, 4096, PROT_READ) = 0
munmap(0x7fd97c978000, 117095)          = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {0, 22258651}) = 0
futex(0x7fd97d88a0c8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, {0, 22434989}) = 0
futex(0x7fd97d567cf4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d567ce8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d567ce0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d567db8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d567cc8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(1, "", {st_mode=S_IFREG|0644, st_size=34047, ...}, 0x1000 /* AT_??? */) = 0
write(1, "Connecting via moira.delta\n", 27Connecting via moira.delta
) = 27
futex(0x7fd97d110258, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d11024c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d110244, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d110350, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d110230, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d110228, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d10fca4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d110284, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d10fc98, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(0x1146000)                          = 0x1146000
futex(0x7fd97d11023c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/etc/ssl/openssl.cnf", O_RDONLY) = 3
futex(0x7fd97d10fd68, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=9390, ...}, 0x1000 /* AT_??? */) = 0
read(3, "#\n# OpenSSL example configuratio"..., 4096) = 4096
read(3, "_name ]\ncountryName\t\t\t= Country "..., 4096) = 4096
read(3, "# This is OK for an SSL server.\n"..., 4096) = 1198
read(3, "", 4096)                       = 0
close(3)                                = 0
futex(0x7fd97d110220, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d1101fc, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d10fa9c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d1101f4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/opt/clamav/lib/libz.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=117095, ...}, 0x1000 /* AT_??? */) = 0
mmap(NULL, 117095, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fd97c718000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libz.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
pread(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\1\0\1\300\4\0\0\0\31\0\0\0\0\0\0\0"..., 48, 111880) = 48
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=125272, ...}, 0x1000 /* AT_??? */) = 0
close(3)                                = 0
munmap(0x7fd97c718000, 117095)          = 0
futex(0x7fd97d10f9ec, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fd97d1c37a0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
sysinfo({uptime=33987, loads=[21504, 19616, 14752] totalram=16506703872, freeram=13931470848, sharedram=23470080, bufferram=110542848} totalswap=25879920640, freeswap=25879920640, procs=362}) = 0
futex(0x7fd97d1c37c8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
newfstatat(AT_FDCWD, "/opt/clamav/share/clamav/", {st_mode=S_IFDIR|0666, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
chdir("/opt/clamav/share/clamav/")      = -1 EACCES (Permission denied)
write(2, "ERROR: Can't change dir to /opt/"..., 53ERROR: Can't change dir to /opt/clamav/share/clamav/
) = 53
futex(0x7fd97d567e28, FUTEX_WAKE_PRIVATE, 2147483647) = 0
getpid()                                = 14002
syscall_318(0x1134400, 0x20, 0, 0x7fd97db62d20, 0x1134420, 0x13e, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400, 0x1134400) = 0x20
getpid()                                = 14002
futex(0x7fd97d567df8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
getpid()                                = 14002
getpid()                                = 14002
getpid()                                = 14002
getpid()                                = 14002
openat(AT_FDCWD, "freshclam.dat", O_WRONLY|O_CREAT|O_TRUNC, 0644) = -1 EACCES (Permission denied)
getcwd("/root", 4096)                   = 6
write(2, "ERROR: Can't create freshclam.da"..., 43ERROR: Can't create freshclam.dat in /root
) = 43
getgid()                                = 1001
getuid()                                = 1001
write(1, "Hint: The database directory mus"..., 71Hint: The database directory must be writable for UID 1001 or GID 1001
) = 71
write(2, "ERROR: Failed to save freshclam."..., 37ERROR: Failed to save freshclam.dat!
) = 37
write(2, "WARNING: Failed to create a new "..., 47WARNING: Failed to create a new freshclam.dat!
) = 47
write(2, "ERROR: initialize: libfreshclam "..., 45ERROR: initialize: libfreshclam init failed.
) = 45
write(2, "ERROR: Initialization error!\n", 29ERROR: Initialization error!
) = 29
chmod("/opt/clamav/share/clamav/tmp.8e707fd81e", 0700) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/opt/clamav/share/clamav/tmp.8e707fd81e", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 EACCES (Permission denied)
futex(0x7fd97d567ba4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
exit_group(2)                           = ?

**Comment by ragusaa** [comment]
Could you please try setting the permissions on your database directory to 775 and run freshclam?

**Comment by FosterSM** [comment]
Ok:

root@Moira:/opt/clamav/share# freshclam 
Connecting via moira.delta
ClamAV update process started at Fri Dec  9 23:08:46 2022
daily database available for download (remote version: 26745)
Time:    1.1s, ETA:    0.0s [========================>]   57.56MiB/57.56MiB
Testing database: '/opt/clamav/share/clamav/tmp.dfdbd171ea/clamav-8687b64a92cb2f102c4fe657a02131d9.tmp-daily.cvd' ...
WARNING: Stderr output from database load : WARNING: [LibClamAV] cli_loadldb: Failed to initialize target description block [...] WARNING: [LibClamAV] cli_loadldb: Failed to initialize target description block
WARNING: Database successfully loaded, but there is stderr output
Database test passed.
daily.cvd updated (version: 26745, sigs: 2013617, f-level: 90, builder: raynman)
main database available for download (remote version: 62)
Time:    2.7s, ETA:    0.0s [========================>]  162.58MiB/162.58MiB
Testing database: '/opt/clamav/share/clamav/tmp.dfdbd171ea/clamav-5067398a967b60a3b70b9b3f32fad1c5.tmp-main.cvd' ...
Database test passed.
main.cvd updated (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode database available for download (remote version: 333)
Time:    0.1s, ETA:    0.0s [========================>]  286.79KiB/286.79KiB
Testing database: '/opt/clamav/share/clamav/tmp.dfdbd171ea/clamav-1c92f6d10b952792d057aca66fcb56ec.tmp-bytecode.cvd' ...
Database test passed.
bytecode.cvd updated (version: 333, sigs: 92, f-level: 63, builder: awillia2)

Still the original "cli_loadldb" problem.

**Comment by ragusaa** [comment]
Could you try with freshclam --debug ?

**Comment by FosterSM** [comment]
freshclam --debug :

[freshclame-debug.txt](https://github.com/Cisco-Talos/clamav/files/10200606/freshclame-debug.txt)

**Comment by ragusaa** [comment]
Could you post your freshclam.conf and your clamd.conf files please?  

I have looked through the code, and there are a couple ways you can get that error with the output you have.  Could you also run freshclam --debug --verbose ?

Thanks,
Andy

**Comment by FosterSM** [comment]
[freshclam.conf.txt](https://github.com/Cisco-Talos/clamav/files/10215920/freshclam.conf.txt)
[clamd.conf.txt](https://github.com/Cisco-Talos/clamav/files/10215922/clamd.conf.txt)
[freshclam-debugV.txt](https://github.com/Cisco-Talos/clamav/files/10215974/freshclam-debugV.txt)

As requested
Thanks
Stuart

**Comment by ragusaa** [comment]
Sorry for the delay in getting back to you.

LibClamAV debug: init_tdb: Signature for Doc.Dropper.Detected-9977031-0 not loaded (required f-level: 151)
WARNING: [LibClamAV] cli_loadldb: Failed to initialize target description block
LibClamAV debug: init_tdb: Signature for Doc.Downloader.Valyria-9978334-0 not loaded (required f-level: 151)
WARNING: [LibClamAV] cli_loadldb: Failed to initialize target description block

The warning is related to the f-level statement before it.  Running as-is, you will get all the signatures except Doc.Dropper.Detected-9977031-0 and Doc.Downloader.Valyria-9978334-0.  If you upgrade to 1.0, you will get those as well.  

Thanks,
Andy

**Comment by FosterSM** [comment]
Thank you, but sorry I don't know how to "upgrade to 1.0".

Stuart

**Comment by ragusaa** [comment]
1.0 is our latest release.  You can download it here https://www.clamav.net/downloads.

Thanks,
Andy

**Comment by FosterSM** [comment]
Understood thank you.

**Comment by ragusaa** [comment]
If you have any further issues with this, please re-open.

Thanks,
Andy
