### ISSUE TITLE
Newer Docker Images are eight times larger and perform way worse

### ISSUE THREAD

**Issue by hebelal** [Cisco-Talos/clamav#802]
Hi,

We use the clamav docker image in version [0.105.1_base](https://hub.docker.com/layers/clamav/clamav/0.105.1_base/images/sha256-eb010c5c4e50e86c25b80c9a82655a0ccdebfa163e55076ff1cba05183258f7a?context=explore).
Recently we noticed that the performance of our scans got way worse (takes twice as long) with one of the latest updates.
We also noticed that the docker image size increased from 11,76MB to 72,92MB with 0.105.1-3_base to 0.105.1-4_base.
Could it be that the slow performance and big image size are connected to each other (maybe the debug build mistakenly got shipped) ?
I already posted an issue in the [clamav-docker repo](https://github.com/Cisco-Talos/clamav-docker/issues/7), but it does not seem to get picked up.

Best regards,
Alex

**Comment by teoberi** [comment]
https://github.com/Cisco-Talos/clamav/issues/590

**Comment by JonBendtsen** [comment]
Could it perhaps be because the debian/Jenkinsfile copied the alpine/Dockerfile and not the debian/Dockerfile ?

Perhaps see this pull-request  https://github.com/Cisco-Talos/clamav-docker/pull/11

**Comment by micahsnyder** [comment]
Just merged the PR that should restore the performance back to the was it was in the 0.105.1-1 image. We will push updated images for 0.105.1, 1.0.0, and unstable shortly.
