### ISSUE TITLE
Raise artificial 4GB limit for MaxScanSize to allow scanning larger archives

### ISSUE THREAD

**Issue by scddev** [Cisco-Talos/clamav#809]
As comment in clamd.conf suggests:

```
# Value of 0 disables the limit
```

The result is a limit of 4GB:
```
Thu Jan 12 07:12:28 2023 -> Limits: Global size limit set to 4294967295 bytes.
Thu Jan 12 07:12:28 2023 -> Limits: File size limit set to 4294967295 bytes.
```

This is caused by a change dating back to 2011: https://github.com/Cisco-Talos/clamav/commit/6f4847aacfd153f0a88612789cac0deb233ee669

When reverting this change, also limits can be disabled again:
```
WARNING: Thu Jan 12 07:09:58 2023 -> Limits: Global size limit protection disabled.
WARNING: Thu Jan 12 07:09:58 2023 -> Limits: File size limit protection disabled.
```

**Comment by micahsnyder** [comment]
@scddev You cannot disable the file size or scan size limit. That is expected behavior.  But by settings to `0` which maxes out the limit. That's as close as we can get to disabling it. 

Further, the real internal limit for MaxFileSize, specifically, is 2GB and not the 4GB configuration limit.
See: https://github.com/Cisco-Talos/clamav/issues/344
And: https://github.com/Cisco-Talos/clamav/blob/main/etc/clamd.conf.sample#L536

But perhaps we should modify the conf wording to say something like this instead:
```
# This option sets the maximum amount of data to be scanned for each input
# file. Archives and other containers are recursively extracted and scanned
# up to this value.
# Value of 0 will set the limit to 4GB which is the maximum option.
# Note: disabling this limit or setting it too high may result in severe damage
# to the system.
# Default: 400M
#MaxScanSize 1000M

# Files larger than this limit won't be scanned. Affects the input file itself
# as well as files contained inside it (when the input file is an archive, a
# document or some other kind of container).
# Value of 0 will set the limit to 2GB which is the maximum option.
# Note: disabling this limit or setting it too high may result in severe damage
# to the system.
# Technical design limitations prevent ClamAV from scanning files greater than
# 2 GB at this time.
# Default: 100M
#MaxFileSize 400M
```

**Comment by scddev** [comment]
@micahsnyder I am fine with the technical limit for MaxFileSize and adapting the documentation, my main concern is in regards of the MaxScanSize which does not relate to any technical issue and just prevents a scan of larger files (archives).

E.g. in my case an exe installer containing a msi containing some files:

```
clamscan --alert-exceeds-max=yes --max-scantime=3600000 --max-filesize=0 --max-scansize=0 --max-files=20000 --max-embeddedpe=1000M <redacted>.exe
...
<redacted>.exe: Heuristics.Limits.Exceeded.MaxScanSize FOUND
...
Data scanned: 4292.86 MB
Data read: 111.95 MB (ratio 38.35:1)
```

Removing the default to 4GB shows the real size and fully scans the file:

```
Data scanned: 5431.70 MB
Data read: 111.95 MB (ratio 48.52:1)
```

**Comment by micahsnyder** [comment]
@scddev That's fair. Honestly I have idly wondered why there is a 4GB limit on scansize as well, but never got around to investigating.  I'll rename this issue to describe that problem.

**Comment by matthias-fratz-bsz** [comment]
We're afffected by this too, because we need to occasionally scan multi-GB files (and don't care if doing so takes hours). I noticed that on 64-bit (Debian Linux), either limit can be set way larger than 4G by specifying the limit in bytes:

```
$ clamscan --max-filesize 15000000000 --max-scansize 15000000000 --max-files 99999999 --alert-exceeds-max=yes --max-scantime=1800000 ~/huge-files/ -r
```

Not sure whether MaxFileSize works, but MaxScanSize sure does seem to be accepted:

```
----------- SCAN SUMMARY -----------
Known viruses: 8666225
Engine version: 0.103.8
Scanned directories: 13
Scanned files: 10
Infected files: 0
Data scanned: 15026.16 MB
Data read: 8877.37 MB (ratio 1.69:1)
Time: 1329.525 sec (22 m 9 s)
```

Is that expected to just work properly once the limit is set, or are there pitfalls elsewhere in the code? Should I try making a pull request to raise the configurable limit to 2^63? The option parser's `numarg` variable is `long long`, so should be 64-bit even on 32-bit platforms, ie. this looks like a reasonably easy thing to fix.

**Comment by micahsnyder** [comment]
> Should I try making a pull request to raise the configurable limit to 2^63? The option parser's numarg variable is long long, so should be 64-bit even on 32-bit platforms, ie. this looks like a reasonably easy thing to fix.

I investigated this and could only find once concern regarding add the ability to configure MaxScanSize limit higher than 4GB.  

There is a related feature for the number of bytes that were "scanned" that is actually the number of bytes that we've pattern matched on.  This is conceptually related but technically different from the "ScanSize" which is sum of the sizes of each of the files processed.  

This "scanned" number is the number that is reported in the scan summary, and is the `scanned` output parameter for `cl_scanmap_callback`, `cl_scandesc_callback`, and `cl_scanfile_callback`:
- https://github.com/Cisco-Talos/clamav/blob/main/libclamav/clamav.h#L1336
- https://github.com/Cisco-Talos/clamav/blob/main/libclamav/clamav.h#L1040
- https://github.com/Cisco-Talos/clamav/blob/main/libclamav/clamav.h#L1067

It is unfortunately an `unsigned long int` which means it may be a `uint32_t` or uint64_t`, depending on the platform.   What that means is that if you exceed 4GB in total bytes that clam pattern matches that variable may overflow internally and return the wrong value.  

We have some unrelated improvements we'd like to make to those API's as well which means we may eventually deprecate them and add like an `_ex` version which the new features and better types.  

Anyways, long story short that was the only concern I could come up with.  I don't think it's a blocker.  If you're up for making a PR to increase the size that can be configured for MaxScanSize, it would be appreciated.
