### ISSUE TITLE
Feature request: Extraction of attachments inside OneNote documents

### ISSUE THREAD

**Issue by LSchuepbach** [Cisco-Talos/clamav#819]
Describe the bug
----------------

I'd wish that attached files inside OneNote `.one` documents would be correctly recognized and extracted when using the `--leave-temps` option.

As mentioned in [Bleeping Computer](https://www.bleepingcomputer.com/news/security/hackers-now-use-microsoft-onenote-attachments-to-spread-malware/), OneNote is becoming a new way of spreading malwares.

How to reproduce the problem
----------------------------

Using 1.0.0 in docker, the .one file is considered as binary, --leave-temps leaves nothing.

[https://blog.didierstevens.com/2023/01/22/analyzing-malicious-onenote-documents/](https://blog.didierstevens.com/2023/01/22/analyzing-malicious-onenote-documents/) gives a sample, link to the document by Microsoft explaining the structure and a python script that recognizes the boundary and extracts the attachments.

I have access to a couple more samples if someone is interested.

**Comment by SecT0uch** [comment]
@LSchuepbach Small world :wave:
