### ISSUE TITLE
Can't open/parse the config file /opt/homebrew/etc/clamav/freshclam.conf

### ISSUE THREAD

**Issue by hoochanlon** [Cisco-Talos/clamav#826]
<img width="766" alt="catch2023-02-05 17 13 45" src="https://user-images.githubusercontent.com/35732922/216810904-b4d2633a-34ff-48aa-83b2-2b023ac123c5.png">

<img width="682" alt="catch2023-02-05 20 49 34" src="https://user-images.githubusercontent.com/35732922/216819621-30412c9d-e9dd-40a8-8611-ec946a8a1ad3.png">

**Comment by micahsnyder** [comment]
Hi @hoochanlon,

Some distributions provide default configuration files but in most cases you may need to create your own. 

There should be a some sample config files in `/opt/homebrew/etc/clamav/` to help you get started.

For more information, see: https://docs.clamav.net/manual/Usage/Configuration.html

This github issue queue is intended for reporting bugs in ClamAV and is not for user support.  If you have additional questions and can't find the solutions in the sample configs, the manpages, or on docs.clamav.net, you may ask the community for help in the clamav-users mailing list, or on our Discord server: https://docs.clamav.net/#mailing-lists-and-chat
