### ISSUE TITLE
Clamav Performance issue during Full scan

### ISSUE THREAD

**Issue by srikanth6066** [Cisco-Talos/clamav#833]
If a system is having 17 million files or more, Full scan with clamav is taking more than 24hrs using clamdscan command.
Can anyone please look into this issue

**Comment by teoberi** [comment]
https://github.com/Cisco-Talos/clamav/issues/590

**Comment by micahsnyder** [comment]
Your complaint is non-specific and doesn't give us anything actionable beyond "why is clam slow?"

We're aware that people want scan speed to be faster, and is a pretty common complaint when scanning a whole Windows C-drive. 

What would be helpful is identifying relatively small files that take a surprisingly long time to scan, and sharing those for investigation.  

As @teoberi noted, we already have github issues with complaints about scan speed in general, and in that ticket PDF scan performance has been highlighted and some samples shared for further investigation.  If you have any additional specific files or file types that are particularly concerning, feel free to share them in that issue.
