### ISSUE TITLE
(since running freshclam) scanning simple files is slow

### ISSUE THREAD

**Issue by leapfog** [Cisco-Talos/clamav#849]
Describe the bug
----------------
A workmate complained, that using 'clamscan' is quite slow today on his machine.

How to reproduce the problem
----------------------------
I tested on my own system and it took 12s to scan /etc/fstab. Then I run 'freshclam', now scanning the same file needs more than 90 seconds. Every time.

Config file: clamd.conf
-----------------------
LogFile = "/var/log/clamav/clamd.log"
LogTime = "yes"
PidFile = "/run/clamd.pid"
LocalSocket = "/run/clamav/clamd.ctl"
User = "clamav"

Config file: freshclam.conf
---------------------------
PidFile = "/run/freshclam.pid"
UpdateLogFile = "/var/log/clamav/freshclam.log"
DatabaseMirror = "database.clamav.net"

clamav-milter.conf not found

Software settings
-----------------
Version: 0.103.8
Optional features supported: MEMPOOL IPv6 AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV RAR 

Database information
--------------------
Database directory: /var/lib/clamav
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 14:32:42 2021
bytecode.cvd: version 334, sigs: 91, built on Wed Feb 22 22:33:21 2023
daily.cld: version 26827, sigs: 2022011, built on Wed Mar  1 09:28:49 2023
Total number of signatures: 8669529

Platform information
--------------------
uname: Linux 6.2.1-gentoo #1 SMP PREEMPT_DYNAMIC Sun Feb 26 08:15:20 CET 2023 x86_64
OS: linux-gnu, ARCH: x86_64, CPU: x86_64
Full OS version: "Gentoo Linux"
zlib version: 1.2.13 (1.2.13), compile flags: a9

Build information
-----------------
GNU C: 12.2.1 20230121 (12.2.1)
CPPFLAGS: 
CFLAGS: -march=native -O2 -pipe  -fomit-frame-pointer  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
CXXFLAGS: -march=native -O2 -pipe  -fomit-frame-pointer
LDFLAGS: -Wl,-O1 -Wl,--as-needed
Configure: '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--datarootdir=/usr/share' '--disable-dependency-tracking' '--disable-silent-rules' '--docdir=/usr/share/doc/clamav-0.103.8' '--htmldir=/usr/share/doc/clamav-0.103.8/html' '--with-sysroot=/' '--libdir=/usr/lib64' '--enable-bzip2' '--disable-clamonacc' '--disable-clamdtop' '--enable-ipv6' '--disable-milter' '--disable-check' '--with-xml' '--with-iconv' '--without-libjson' '--disable-libclamav-only' '--with-libcurl' '--with-system-libmspack' '--cache-file=/var/tmp/portage/app-antivirus/clamav-0.103.8/work/clamav-0.103.8/config.cache' '--disable-experimental' '--disable-static' '--disable-zlib-vcheck' '--enable-id-check' '--with-dbdir=/var/lib/clamav' '--with-zlib' '--disable-llvm' '--enable-openrc' '--runstatedir=/run' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CXXFLAGS=-march=native -O2 -pipe  -fomit-frame-pointer' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'CFLAGS=-march=native -O2 -pipe  -fomit-frame-pointer'
sizeof(void*) = 8
Engine flevel: 129, dconf: 129

**Comment by lunika** [comment]
We have the exact same behavior.
After a freshclam call this morning, the same file took 17 seconds to scan yesterday and today it takes 112 seconds.

**Comment by micahsnyder** [comment]
We are looking into it and found the issue with the latest `daily` database update.  We'll push out a fix as soon as we're able.

**Comment by lunika** [comment]
Great, thank you !

**Comment by yopink** [comment]
We have the exact same behavior.
thank you for fix.

**Comment by teoberi** [comment]
> We are looking into it and found the issue with the latest `daily` database update. We'll push out a fix as soon as we're able.

Will this solve the problem [here](https://github.com/Cisco-Talos/clamav/issues/590)?

**Comment by leapfog** [comment]
As far as I can see, after running 'freshclam' today, the issue is gone. Thanks!

**Comment by dougal** [comment]
Have also seen that this issue is fixed after `freshclam` run today.

**Comment by yopink** [comment]
is fixed . Thanks!

**Comment by micahsnyder** [comment]
Great!

**Comment by omelnyk1** [comment]
Hello @micahsnyder ,
We noticed the same behaviour for 0.105.2. Shall we run `freshclam` as well?

**Comment by micahsnyder** [comment]
Hi @omelnyk1 yes please use freshclam regularly/daily update to the latest to the latest virus definitions. The slow database load issue should have only affected one specific day's database.  The current databases should load in a reasonable amount of time.

**Comment by omelnyk1** [comment]
Thank you @micahsnyder 
However it did not help. I even rolled back from version 0.105.2 to 0.105.1.
```
# time clamscan --no-summary --stdout --remove=no --scan-archive=yes -r /tmp/emptyfile
/tmp/emptyfile: Empty file

real    0m18.652s
user    0m18.090s
sys     0m0.560s
# clamscan --version
ClamAV 0.105.1/26845/Thu Mar 16 18:16:15 2023
```
Could you please check from your side?

Thank you.

**Comment by micahsnyder** [comment]
@omelnyk1 18 seconds is a normal amount of time for clamscan to load the databases.
