### ISSUE TITLE
clamav-1.0.1 is in which distribution ?

### ISSUE THREAD

**Issue by kumarbava** [Cisco-Talos/clamav#853]
We have been using clamav-0.103.6 and would like to upgrade to the new LTS release(1.0.x).
However, I can not find clamav-1.0.1 in epel distribution.

So far , we have been able to install  clamav-0.103.x from EPEL repo and would like to do the same for the new LTS track(1.0.x) if its possible.
I could not find any specific package instructions for 1.0.x .

**Comment by micahsnyder** [comment]
This ticket queue is for issues with clamav or the clamav packages that we provide.  You may wish to ask in the clamav-users mailing list or even on our Discord server.  https://docs.clamav.net/Introduction.html#mailing-lists-and-chat
Perhaps someone will know the answer to your question.  (Sorry I do not know the answer)
