### ISSUE TITLE
ClamAV couldn't detect virus/malware in EICAR_test_file

### ISSUE THREAD

**Issue by rsharmavon** [Cisco-Talos/clamav#854]
Hey Team,

We are using clamav version i.e 
ClamAV 0.103.3
and clamav java client version is : version: '2.1.2'

Current architecture/Setup :
Our web application deployed in kubernetes (front end - angular 9/backend - java 17)  and talks to clamav daemon which is deployed in another pod.

Issue summary :
a) As part of our application automation ( i.e cypress) in order to test virus in a file we upload a file to our application and which then further passed to clamav to scan it, and after scan we upload the file to jira.

We tried to download this file on our laptop after it gets uploaded to Jira, and antivirus agent running on our laptop detects that this file has virus and removes it.
Hence file seems to be correct (i.e virus infected) but clamav couldn't detect any virus(es)/malware into this file.

-> Attaching the respective cypress code snippet (cypress_code_snippet.txt) which is used to generate the file with TEST_EICAR string and upload to our application.
-> Also attaching the respective clamav java client (ClamAVClient.txt)/controller (ClamAVController.txt -> /upload end point) which is triggered when file is uploaded.Saved as .txt file to allow upload to ticket in github.

Note : within /testEicar api (this is just a test api to detect virus in EICAR_test string) where we pass the input stream (after getting bytes from TEST_EICAR string) to clamav we get the correct response i.e
  [vgcn-api] 2023-03-07 20:58:41.237  WARN 1 --- [nio-8080-exec-3] c.v.gcn.controller.ClamAVController      : -------- Virus(es) found in file! - TEST_EICARstream:[Win.Test.EICAR_HDB-1]
  
Hence not sure why clamav not able to detect the virus in the file being uploaded ?
Please suggest as this is blocking our release to production at this point.
[ClamAVClient.txt](https://github.com/Cisco-Talos/clamav/files/10923225/ClamAVClient.txt)
[ClamAVController.txt](https://github.com/Cisco-Talos/clamav/files/10923226/ClamAVController.txt)
[cypress_code_snippet.txt](https://github.com/Cisco-Talos/clamav/files/10923227/cypress_code_snippet.txt)

**Comment by ragusaa** [comment]
Hi,

Is it possible that you have additional characters (newlines, or other characters before the beginning of the eicar string) in your test file?  This will cause clam not to signature the file.

Thanks,
Andy

**Comment by rsharmavon** [comment]
yes seems like that's was we found,
when file was generated with test EICAR string the following was passed in file 
X5O!P%@AP[**4\**\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*


so an additional back slash after 4 in above string caused clamav to not detect this file as malware/virus infected.
so when we passed correct EICAR string the file and then clamav detected the virus/malware in it.

**Comment by ragusaa** [comment]
Glad to hear it!
