### ISSUE TITLE
LibClamAV Error: cli_realloc(): Attempt to allocate 190840848 bytes.

### ISSUE THREAD

**Issue by waianaeboy702** [Cisco-Talos/clamav#883]
LibClamAV Error: cli_realloc(): Attempt to allocate 190840848 bytes. Please report to https://github.com/Cisco-Talos/clamav/issues

**Comment by m-sola** [comment]
Could you describe what happened in more detail?

**Comment by micahsnyder** [comment]
Closing issue due to lack of additional context. Feel free to re-open if you can provide:
1. the output from `clamconf -n`
2. the file which causes the error when scanned.
