### ISSUE TITLE
Unable to set for updates at interval with Alpine clamav/clamav docker image

### ISSUE THREAD

**Issue by makschr** [Cisco-Talos/clamav#929]
I deployed the official ClamAV 1.1.0 docker image (clamav/clamav:1.1.0 which uses Alpine in Azure, I put Checks 24 (for tests) in freshclam.conf, but still it doesnt check for updates every one hour?? I only get clamd.log updating every 10 mins saying "Database status is OK"... In the log file freshclam.log I see check new virus definitions every 24 hours. 
I ran command _ps aux_ to see all running processes. I got this output:
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
  122 root      0:01 tail -f /dev/null
  126 root      0:01 {init} /sbin/tini /bin/sh /init
  130 root      0:01 tail -f /dev/null
  **135 clamav    0:00 freshclam --checks=1 --daemon --foreground --stdout --user=clamav**
  136 clamav    0:34 clamd --foreground
14614 root      0:00 /bin/sh
15145 root      0:00 /bin/sh
15149 root      0:00 ps aux

PID 135 tells me that freshclam run as background daemon with check updates of virus definitions once a day. This process overrides settings in the file frshclam.conf.

Output of clamconf command:
/ # clamconf
Checking configuration files in /etc/clamav

Config file: clamd.conf
-----------------------
AlertExceedsMax disabled
PreludeEnable disabled
PreludeAnalyzerName disabled
LogFile = "/var/log/clamav/clamd.log"
LogFileUnlock disabled
LogFileMaxSize = "1048576"
LogTime = "yes"
LogClean disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate disabled
ExtendedDetectionInfo disabled
PidFile = "/tmp/clamd.pid"
TemporaryDirectory disabled
DatabaseDirectory = "/var/lib/clamav"
OfficialDatabaseOnly disabled
FailIfCvdOlderThan disabled
LocalSocket = "/tmp/clamd.sock"
LocalSocketGroup disabled
LocalSocketMode disabled
FixStaleSocket = "yes"
TCPSocket = "3310"
TCPAddr disabled
MaxConnectionQueueLength = "200"
StreamMaxLength = "139460608"
StreamMinPort = "1024"
StreamMaxPort = "2048"
MaxThreads = "10"
ReadTimeout = "120"
CommandReadTimeout = "30"
SendBufTimeout = "500"
MaxQueue = "100"
IdleTimeout = "30"
ExcludePath disabled
MaxDirectoryRecursion = "15"
FollowDirectorySymlinks disabled
FollowFileSymlinks disabled
CrossFilesystems = "yes"
SelfCheck = "600"
ConcurrentDatabaseReload = "yes"
DisableCache disabled
VirusEvent disabled
ExitOnOOM disabled
AllowAllMatchScan = "yes"
Foreground disabled
Debug disabled
LeaveTemporaryFiles disabled
GenerateMetadataJson disabled
User = "clamav"
Bytecode = "yes"
BytecodeSecurity = "TrustSigned"
BytecodeTimeout = "10000"
BytecodeUnsigned disabled
BytecodeMode = "Auto"
DetectPUA disabled
ExcludePUA disabled
IncludePUA disabled
ScanPE = "yes"
ScanELF = "yes"
ScanMail = "yes"
ScanPartialMessages disabled
PhishingSignatures = "yes"
PhishingScanURLs = "yes"
HeuristicAlerts = "yes"
HeuristicScanPrecedence disabled
StructuredDataDetection disabled
StructuredMinCreditCardCount = "3"
StructuredMinSSNCount = "3"
StructuredSSNFormatNormal = "yes"
StructuredSSNFormatStripped disabled
ScanHTML = "yes"
ScanOLE2 = "yes"
AlertBrokenExecutables disabled
AlertBrokenMedia disabled
AlertEncrypted disabled
StructuredCCOnly disabled
AlertEncryptedArchive disabled
AlertEncryptedDoc disabled
AlertOLE2Macros disabled
AlertPhishingSSLMismatch disabled
AlertPhishingCloak disabled
AlertPartitionIntersection disabled
ScanPDF = "yes"
ScanSWF = "yes"
ScanXMLDOCS = "yes"
ScanHWP3 = "yes"
ScanArchive = "yes"
ForceToDisk disabled
MaxScanTime disabled
MaxScanSize = "419430400"
MaxFileSize = "104857600"
MaxRecursion = "17"
MaxFiles = "10000"
MaxEmbeddedPE = "41943040"
MaxHTMLNormalize = "41943040"
MaxHTMLNoTags = "8388608"
MaxScriptNormalize = "20971520"
MaxZipTypeRcg = "1048576"
MaxPartitions = "50"
MaxIconsPE = "100"
MaxRecHWP3 = "16"
PCREMatchLimit = "100000"
PCRERecMatchLimit = "2000"
PCREMaxFileSize = "104857600"
OnAccessMountPath disabled
OnAccessIncludePath disabled
OnAccessExcludePath disabled
OnAccessExcludeRootUID disabled
OnAccessExcludeUID disabled
OnAccessExcludeUname disabled
OnAccessMaxFileSize = "5242880"
OnAccessDisableDDD disabled
OnAccessPrevention disabled
OnAccessExtraScanning disabled
OnAccessCurlTimeout = "5000"
OnAccessMaxThreads = "5"
OnAccessRetryAttempts disabled
OnAccessDenyOnError disabled
DevACOnly disabled
DevACDepth disabled
DevPerformance disabled
DevLiblog disabled
DisableCertCheck disabled
AlgorithmicDetection = "yes"
BlockMax disabled
PhishingAlwaysBlockSSLMismatch disabled
PhishingAlwaysBlockCloak disabled
PartitionIntersection disabled
OLE2BlockMacros disabled
ArchiveBlockEncrypted disabled

Config file: freshclam.conf
---------------------------
LogFileMaxSize = "1048576"
LogTime disabled
LogSyslog disabled
LogFacility = "LOG_LOCAL6"
LogVerbose disabled
LogRotate disabled
PidFile = "/tmp/freshclam.pid"
DatabaseDirectory = "/var/lib/clamav"
Foreground disabled
Debug disabled
UpdateLogFile = "/var/log/clamav/freshclam.log"
DatabaseOwner = "clamav"
Checks = "24"
DNSDatabaseInfo = "current.cvd.clamav.net"
DatabaseMirror = "database.clamav.net"
PrivateMirror disabled
MaxAttempts = "3"
ScriptedUpdates = "yes"
TestDatabases = "yes"
CompressLocalDatabase disabled
ExtraDatabase disabled
ExcludeDatabase disabled
DatabaseCustomURL disabled
HTTPProxyServer disabled
HTTPProxyPort disabled
HTTPProxyUsername disabled
HTTPProxyPassword disabled
HTTPUserAgent disabled
NotifyClamd = "/etc/clamav/clamd.conf"
OnUpdateExecute disabled
OnErrorExecute disabled
OnOutdatedExecute disabled
LocalIPAddress disabled
ConnectTimeout = "30"
ReceiveTimeout disabled
Bytecode = "yes"

clamav-milter.conf not found

Software settings
-----------------
Version: 1.1.0
Optional features supported: MEMPOOL AUTOIT_EA06 BZIP2 LIBXML2 PCRE2 ICONV JSON RAR 

Database information
--------------------
Database directory: /var/lib/clamav
bytecode.cvd: version 334, sigs: 91, built on Wed Feb 22 21:33:21 2023
daily.cvd: version 26918, sigs: 2035229, built on Thu May 25 07:25:14 2023
main.cvd: version 62, sigs: 6647427, built on Thu Sep 16 12:32:42 2021
Total number of signatures: 8682747

Platform information
--------------------
uname: Linux 5.10.102.2-microsoft-standard #1 SMP Mon Mar 7 17:36:34 UTC 2022 x86_64
OS: Linux, ARCH: x86_64, CPU: x86_64
zlib version: 1.2.13 (1.2.13), compile flags: a9
platform id: 0x0a21b4b408000000000c0201

Build information
-----------------
GNU C: 12.2.1 20220924 (12.2.1)
sizeof(void*) = 8
Engine flevel: 180, dconf: 180.

Is this the correct functioning of the docker image?

**Comment by micahsnyder** [comment]
Hi @makschr sorry no one replied earlier.  I was just reviewing some older tickets and came across this.

I am a little confused.  You wrote:

> I put Checks 24 (for tests) in freshclam.conf, but still it doesnt check for updates every one hour?? I only get clamd.log updating every 10 mins saying "Database status is OK"... In the log file freshclam.log I see check new virus definitions every 24 hours.

But in your `ps` output it shows:
> **135 clamav 0:00 freshclam --checks=1 --daemon --foreground --stdout --user=clamav**

The `--checks=1` option is overriding the `freshclam.conf` setting.  If you want it to run the freshclam checks more frequently, you'll have to change the `freshclam` parameters. As you're using the docker image, you can do that with the `FRESHCLAM_CHECKS` environement variable option when you start the image.  See https://docs.clamav.net/manual/Installing/Docker.html#controlling-the-container for details.
