### ISSUE TITLE
Unnecessary warning message in libfreshclam_internal.c

### ISSUE THREAD

**Issue by 09001413** [Cisco-Talos/clamav#930]
Sorry Micah @micahsnyder , I don't know if this should be reported as a bug, but it does bother us.

I found the following line of code inside libfreshclam_internal.c. Although the download executes properly, a warning message still appears. This message is picked up by our log monitoring system and alerted.

`logg(LOGG_WARNING, " ******* RESULT %ld, SIZE: %zu ******* \n", http_code, receivedFile.size).`

If this is an info message, can you lower its level to info level, or can you judge it based on the http code and not let it give a warning message if the code is 200? (Sorry, I am not a C player, so I raised this issue instead of raising a PR)

Thank you in advance.

**Comment by micahsnyder** [comment]
@09001413 It bothers me too. I'm sorry about any confusion it may have caused. We'll have it fixed in 1.1.1.

**Comment by 09001413** [comment]
@micahsnyder Thank you very much! we will wait for version 1.1.1.
