### ISSUE TITLE
clamAV Error for windows

### ISSUE THREAD

**Issue by TwoDogs2** [Cisco-Talos/clamav#943]
Using the calmdscan command to run a prompt error for Windows
```
C:\Program Files\ClamAV>clamdscan.exe --reload
ERROR: Could not connect to clamd on localhost: Connection refused
ERROR: Could not connect to clamd on localhost: Connection refused

C:\Program Files\ClamAV>clamdscan.exe -p 3
ERROR: Could not connect to clamd on localhost: Connection refused
ERROR: Could not connect to clamd on localhost: Connection refused
Could not connect, will PING again in 1 second
ERROR: Could not connect to clamd on localhost: Connection refused
ERROR: Could not connect to clamd on localhost: Connection refused
Could not connect, will PING again in 1 second
ERROR: Could not connect to clamd on localhost: Connection refused
ERROR: Could not connect to clamd on localhost: Connection refused
PING timeout exceeded; No response from clamd

C:\Program Files\ClamAV>clamdscan.exe C:\123
ERROR: Could not connect to clamd on localhost: Connection refused
ERROR: Could not connect to clamd on localhost: Connection refused

----------- SCAN SUMMARY -----------
Infected files: 0
Total errors: 1
Time: 2.068 sec (0 m 2 s)
Start Date: 2023:06:06 15:19:35
End Date:   2023:06:06 15:19:37

C:\Program Files\ClamAV>clamdscan.exe --reload
ERROR: Could not connect to clamd on localhost: Connection refused
ERROR: Could not connect to clamd on localhost: Connection refused
```

**Comment by TwoDogs2** [comment]
After a few hours of use, the clamscan command is not available, only the clamdscan command

**Comment by micahsnyder** [comment]
`clamd.exe` must be running for `clamdscan.exe` to work.  If you have not already created a `clamd.conf` config file, you'll have to do that before you can start `clamd.exe`.  

Basic instructions are here: https://docs.clamav.net/manual/Usage/Configuration.html#windows

After you create the `clamd.conf` file from the example file, and remove the "Example" line from the top, then just start `clamd.exe` and then try the `clamdscan.exe` program again. 

> After a few hours of use, the clamscan command is not available, only the clamdscan command

This makes no sense to me.  `clamscan` is not a command.  `clamscan.exe` is a program that sits in your `C:\Program Files\ClamAV` directory.

**Comment by TwoDogs2** [comment]
> `clamd.exe` must be running for `clamdscan.exe` to work. If you have not already created a `clamd.conf` config file, you'll have to do that before you can start `clamd.exe`.
> 
> Basic instructions are here: https://docs.clamav.net/manual/Usage/Configuration.html#windows
> 
> After you create the `clamd.conf` file from the example file, and remove the "Example" line from the top, then just start `clamd.exe` and then try the `clamdscan.exe` program again.
> 
> > After a few hours of use, the clamscan command is not available, only the clamdscan command
> 
> This makes no sense to me. `clamscan` is not a command. `clamscan.exe` is a program that sits in your `C:\Program Files\ClamAV` directory.

Prompt for issues when registering for the service 
```
C:\Program Files\ClamAV>clamd.exe --install-service
Service clamd successfully created.
Use 'net start clamd' and 'net stop clamd' to start/stop the service.

C:\Program Files\ClamAV>net start clamd
ClamAV ClamD Service is starting .
ClamAV ClamD Service cannot start。

system error。

System error occurred 1067。

Process terminated unexpectedly。


C:\Program Files\ClamAV>
```
OS is Windows Server 2016
Programs run as administrators

**Comment by TwoDogs2** [comment]
> > `clamd.exe` must be running for `clamdscan.exe` to work. If you have not already created a `clamd.conf` config file, you'll have to do that before you can start `clamd.exe`.
> > Basic instructions are here: https://docs.clamav.net/manual/Usage/Configuration.html#windows
> > After you create the `clamd.conf` file from the example file, and remove the "Example" line from the top, then just start `clamd.exe` and then try the `clamdscan.exe` program again.
> > > After a few hours of use, the clamscan command is not available, only the clamdscan command
> > 
> > 
> > This makes no sense to me. `clamscan` is not a command. `clamscan.exe` is a program that sits in your `C:\Program Files\ClamAV` directory.
> 
> Prompt for issues when registering for the service
> 
> ```
> C:\Program Files\ClamAV>clamd.exe --install-service
> Service clamd successfully created.
> Use 'net start clamd' and 'net stop clamd' to start/stop the service.
> 
> C:\Program Files\ClamAV>net start clamd
> ClamAV ClamD Service is starting .
> ClamAV ClamD Service cannot start。
> 
> system error。
> 
> System error occurred 1067。
> 
> Process terminated unexpectedly。
> 
> 
> C:\Program Files\ClamAV>
> ```
> 
> OS is Windows Server 2016 Programs run as administrators

I called the clamscan.exe service in the installation directory, and the previous second I was using it, and the next second I was prompted without this command

**Comment by kotenok2000** [comment]
> `clamd.exe` must be running for `clamdscan.exe` to work. If you have not already created a `clamd.conf` config file, you'll have to do that before you can start `clamd.exe`.
> 
> Basic instructions are here: https://docs.clamav.net/manual/Usage/Configuration.html#windows
> 
> After you create the `clamd.conf` file from the example file, and remove the "Example" line from the top, then just start `clamd.exe` and then try the `clamdscan.exe` program again.
> 
> > After a few hours of use, the clamscan command is not available, only the clamdscan command
> 
> This makes no sense to me. `clamscan` is not a command. `clamscan.exe` is a program that sits in your `C:\Program Files\ClamAV` directory.

If it is inputted in command line then it is command
Windows expands command clamscan to clamscan.exe

**Comment by HydraDragonAntivirus** [comment]
Also if net start clamd not found then do clamd.exe --install

**Comment by HydraDragonAntivirus** [comment]
Please close topic if there no answer because I faced same problem then fixed

**Comment by micahsnyder** [comment]
Closing stale ticket.

**Comment by HydraDragonAntivirus** [comment]
Did you forget "" this? so OnAccessMountPath C:\ should be OnAccessMountPath "C:\"

**Comment by micahsnyder** [comment]
@HydraDragonAntivirus please stop giving bad advice. OnAccess does not exist for Windows.

**Comment by HydraDragonAntivirus** [comment]
> @HydraDragonAntivirus please stop giving bad advice. OnAccess does not exist for Windows.

Yeah I now realized that OnAccessMounthPath causes this error.

**Comment by HydraDragonAntivirus** [comment]
I also realized any broken database also cause that.
