### ISSUE TITLE
Kaiji false positives on Live ubuntu image

### ISSUE THREAD

**Issue by mindtheegab** [Cisco-Talos/clamav#944]
Describe the bug
----------------

multiple false positives on fresh ubuntu 23.04 live

How to reproduce the problem
----------------------------
launc hthis command from the live environment

ubuntu@ubuntu:~$ clamscan -r --bell -i /usr/lib/snapd/

Attachments
-----------

 /usr/lib/snapd/snap-bootstrap: Unix.Malware.Kaiji-10003916-0 FOUND
 /usr/lib/snapd/snap-preseed: Unix.Malware.Kaiji-10003916-0 FOUND
 /usr/lib/snapd/snap-recovery-chooser: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/lib/snapd/snap-repair: Unix.Malware.Kaiji-10003916-0 FOUND
 /usr/lib/snapd/snapctl: Unix.Malware.Kaiji-10003916-0 FOUND
 /usr/lib/snapd/snapd: Unix.Malware.Kaiji-10003916-0 FOUND

**Comment by epcim** [comment]
we do face same problem, match regular binaries of multiple types (custom, public builds golang build builds) and tar.gz.. 

Problem comes with the latest db version: 26931
```
clamav-z54mz clamav daily database available for update (local version: 26868, remote version: 26931)
clamav-z54mz clamav-exporter {"level":"info","msg":"Server is starting...","time":"2023-06-07T09:05:10Z"}
clamav-z54mz clamav-exporter {"level":"info","msg":"Server is ready to handle requests at :9810","time":"2023-06-07T09:05:10Z"}
```
Some examples:
```
Clamav found virus files at node fluentbit-4vq22 in past 30 minutes. 2023-06-07T11:05:41.126654932Z stdout F /host-fs/home/kubernetes/gcfsd.tar.gz: Unix.Malware.Kaiji-10003916-0 FOUND

Clamav found virus files at node fluentbit-2jndb in past 30 minutes. /host-fs/usr/bin/kubectl: Unix.Malware.Kaiji-10003916-0 FOUND
```



```

```

**Comment by mindtheegab** [comment]
thanks a lot for the quick reply, is there a way to use an older "stable"  DB?

**Comment by awalende** [comment]
Can confirm with the newest release.
These are false positives, checked a few of them with virustotal.com

/snap/lxd/22923/bin/lxc: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/22923/bin/lxc-to-lxd: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/22923/bin/lxd-agent: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/22923/bin/lxd-benchmark: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/22923/bin/lxd-migrate: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/22923/bin/lxd-user: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/22923/bin/snap-query: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/24322/bin/lxc: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/24322/bin/lxd-agent: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/24322/bin/lxd-benchmark: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/24322/bin/lxd-migrate: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/24322/bin/lxd-user: Unix.Malware.Kaiji-10003916-0 FOUND
/snap/lxd/24322/bin/snap-query: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/sbin/zabbix_agent2: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/sbin/zabbix-agent2-plugin/zabbix-agent2-plugin-postgresql: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/sbin/zabbix-agent2-plugin/zabbix-agent2-plugin-mongodb: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/lib/snapd/snapctl: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/lib/snapd/snap-bootstrap: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/lib/snapd/snap-preseed: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/lib/snapd/snap-recovery-chooser: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/lib/snapd/snapd: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/lib/snapd/snap-repair: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/bin/snap: Unix.Malware.Kaiji-10003916-0 FOUND
LibClamAV Warning: cli_scanxz: decompress file size exceeds limits - only scanning 27262976 bytes

----------- SCAN SUMMARY -----------
Known viruses: 8668539
Engine version: 0.103.8
Scanned directories: 23653
Scanned files: 133936
Infected files: 23
Data scanned: 9738.14 MB
Data read: 10930.95 MB (ratio 0.89:1)
Time: 1461.665 sec (24 m 21 s)
Start Date: 2023:06:07 12:16:11
End Date:   2023:06:07 12:40:33

**Comment by nmaludy** [comment]
Looks like Unix.Malware.Kaiji-10003916-0  was added to the signature database last night / this morning.

https://lists.clamav.net/pipermail/clamav-virusdb/2023-June/008314.html

**Comment by doverholt** [comment]
Yes, it looks like the SSM agent in Amazon Linux 2 is also getting detected has containing this malware in our nightly scans:

/usr/bin/amazon-ssm-agent: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/bin/ssm-agent-worker: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/bin/ssm-cli: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/bin/ssm-document-worker: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/bin/ssm-session-logger: Unix.Malware.Kaiji-10003916-0 FOUND
/usr/bin/ssm-session-worker: Unix.Malware.Kaiji-10003916-0 FOUND

The signatures on these files match what AWS is providing in their yum repos. Submitted samples to VirusTotal and only vendor reporting malware is ClamAV.

**Comment by mclaborn** [comment]
Also a problem with Digital Ocean's do-agent

**Comment by tat777** [comment]
Hello. I'm absolutely green in this topic, but I found the same malware in some of my files. Checking it on virustotal.com, only the Clam AV flagged it as malicious. What do I do? Is it necessary to eliminate it? I tried to do this through the Clam TK, but it doesn't work. Some suggestions please. Thanks 💞

**Comment by candrews** [comment]
There's another discussion on this topic at https://serverfault.com/questions/1132808/clamav-detected-kaiji-malware-on-ubuntu-instance/1132817

I also reported this issue to ClamAV in their discord at https://discord.com/channels/636023333074370595/636023333074370597/1116030656548454480

**Comment by jesperG-dk** [comment]
**tat777:** A "false positive" is when the virus detector is wrong, i.e. there is no virus even though one appears to have been detected. The fact that this detection shows up in so many places at once - and that other AV packages don't make the same detection - is a strong indicator that it is a false positive: It is _very likely_ that the clamav detector is in error here - that the current clamav signature for the Kaiji thing will flag a lot of innocent stuff along with the real culprit.

Of course, some of us could still have that virus on our systems. Right now, based on this clamav detection, it is just very unlikely that this is the case, and particularly so if other AV packages do not make the same detection.

So I'd sit this one out until the next clamav database update comes along. With any luck the detection will then be gone. In the meantime, and if you can, you might want to avoid using the files/packages that your clamav flagged as malware.

**Comment by nmaludy** [comment]
Latest signatures came out about an hour and a half ago. They dropped the signature

**Comment by tat777** [comment]
> **tat777:** A "false positive" is when the virus detector is wrong, i.e. there is no virus even though one appears to have been detected. The fact that this detection shows up in so many places at once - and that other AV packages don't make the same detection - is a strong indicator that it is a false positive: It is _very likely_ that the clamav detector is in error here - that the current clamav signature for the Kaiji thing will flag a lot of innocent stuff along with the real culprit.
> 
> Of course, some of us could still have that virus on our systems. Right now, based on this clamav detection, it is just very unlikely that this is the case, and particularly so if other AV packages do not make the same detection.
> 
> So I'd sit this one out until the next clamav database update comes along. With any luck the detection will then be gone. In the meantime, and if you can, you might want to avoid using the files/packages that your clamav flagged as malware.

Thank you very much for detailed explication!!!

**Comment by tat777** [comment]
Thank you much for yours replies. I installed ClamTK for detect viruses on my Ubuntu. But I saw that there is no way to prevent the entrance of some virus , but only doing detection screening, moreover, it need to screen folder by folder and no all computer in a one touch.
Does exist some program for Linux which function as alert for entering malware file? Could you recommend some? 🙏🏼
