### ISSUE TITLE
Issues running Clamav with clamav-1.1.0.win.x64.msi version

### ISSUE THREAD

**Issue by Thorny-Twig** [Cisco-Talos/clamav#947]
Issue
----------------------------
Issues running Clamav with clamav-1.1.0.win.x64.msi version on Windows 8.1

Description
----------------------------
First off newbie alert and Github slacker, I'm come with the user mindset that I was just to download and install latest stable .msi file and run clamav from the command line by entering "clamscan -r c:\\" to scan the c: drive through the command prompt, I was wrong, or was I? I'm having issues running clamav after installing clamav-1.1.0.win.x64.msi out of the box. I cannot run clamav as normal, I'm getting error messages that the "database" directory/folder isn't available, which is true, it never got installed (see image attached). Have I to install the directory? Please note I've tried deleting and reinstalling also and I'm getting same result. I also tried running "freshclam" from the Command Prompt and I also get issues saying no freshclam.conf is available, which is also true, it never got put in, so do I need to add (see image attached)?

**How to reproduce the problem:**
----------------------------
- Download and install clamav-1.1.0.win.x64.msi
- Open a Command Prompt and "cd" into c:\Program Files\clamav 
- Try running a scan using command "clamscan -r c:\"
- See image attached on error messages returned
- Try running a scan using command "freshclam"
- See image attached on error messages returned

![clamav_win_64bit_msi_install_and_first_run](https://github.com/Cisco-Talos/clamav/assets/19927246/7fa21235-8c5a-4985-bec8-467973a75290)

**Comment by micahsnyder** [comment]
@Thorny-Twig You will need to set up the `freshclam.conf` file as described here https://docs.clamav.net/manual/Usage/Configuration.html#windows

After that, then you can run `freshclam` (or `freshclam.exe`) from your `Administrator` command prompt. 

After Freshclam updates the database, then `clamscan` will work.

**Comment by Thorny-Twig** [comment]
Thanks a million, that link you supplied, helped me do some further steps to configure ClamAV and get `clamscan` and `freshclam`  working for me. I wonder if someone should add this type of information and that link you specified to the main downloads webpage to inform and help more Windows/ClamAV users to getting `clamscan` and `freshclam` installed and up and running.
