### ISSUE TITLE
Rate limited after failure on Freshclam with bytecode.cvd file

### ISSUE THREAD

**Issue by briansu-zillow** [Cisco-Talos/clamav#967]
I was running a docker build and the build was able to run freshclam to get the main and daily files.  It failed to get the bytecode file and is now rate limiting me for 24 hours.  Is the limit 5 downloads?  We did a prod deploy earlier in the day that did freshclam run which I assume did 3 downloads of the 5.  This was a new MR that got merged in after the deploy for some testing.  It downloaded daily and main then stopped at bytecode which was rate limited.  I am just trying to make sure I understand the rate limiting properly.

**Comment by micahsnyder** [comment]
I believe the limit is 10 downloads per file, per hour.  But I may be mistaken.

**Comment by briansu-zillow** [comment]
I just ran this fresh this morning after my rate limiting cooldown and it was able to get main and daily but it cannot seem to get bytecode.  Is there any issue on the rate limiting for bytecode?

**Comment by briansu-zillow** [comment]
Issue is still on going

**Comment by micahsnyder** [comment]
Hi @briansu-zillow I met with our cloudflare account admins this morning along with my management and their management to discuss rate limit behaviors. We are investigating because we're also seeing issues.

**Comment by briansu-zillow** [comment]
@micahsnyder  any updates?

**Comment by micahsnyder** [comment]
We reverted a change that caused more frequent rate limiting, particularly with bytecode.cvd (it was an accident, we'd intended to make it rate limit *less* often).

I've done a bunch of testing today and provided my notes to our web team.  They're going to be meeting with Cloudflare representatives later this month and will present our concerns to them to try to get help tuning it so it works as desired.
