### ISSUE TITLE
91.107.204.153 is rate limited?

### ISSUE THREAD

**Issue by Semisol** [Cisco-Talos/clamav#971]
The IP 91.107.204.153/2a01:4f8:c010:a359::1 seems to be rate limited. Updating always gives me a cooldown 1 day in the future, even if I stop updating attempts for 2 days.

**Comment by micahsnyder** [comment]
@Semisol Can you please run freshclam with `--verbose` and gather the `cf-ray` ID from the HTTP response?  It should look something like this:
> < cf-ray: 7e4aaef45c4d2523-SJC

I can ask the cloudflare admin to investigate by looking up your public IP, but the `cf-ray` ID will help identify the exact issue more precisely and I know they'll ask me for it.

**Comment by micahsnyder** [comment]
Okay great I've passed it along and will let you know what I hear.

**Comment by micahsnyder** [comment]
@Semisol please give it another try.  For some reason Cloudflare's bot analysis was blocking you.  It should be bypassed for you now.
