### ISSUE TITLE
freshclam..your clamav installation is OUTDATED!!

### ISSUE THREAD

**Issue by kimsung444** [Cisco-Talos/clamav#978]
Describe the bug
![1234](https://github.com/Cisco-Talos/clamav/assets/140060056/daa517dc-6516-46e7-ad33-8bb9111e13ab)

How can I update to freshclam??
----------------

Replace this text with a clear and concise description of the bug or feature request.

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by micahsnyder** [comment]
@kimsung444 As the warning message indicates, your clamav installation is running an older version and you should upgrade. There have been a number of important security fixes since 0.103.5. https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html

**Comment by kimsung444** [comment]
I want to upgrade clamav...but I can't..What should I do??

----------------
root@release:/home/sjhee0109# sudo apt install clamav
Reading package lists... Done
Building dependency tree       
Reading state information... Done
clamav is already the newest version (0.103.5+dfsg-1~20.04.1).
0 upgraded, 0 newly installed, 0 to remove and 88 not upgraded.
root@release:/home/sjhee0109# apt-get remove clamav clamtk freshclam     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package freshclam
root@release:/home/sjhee0109#

**Comment by micahsnyder** [comment]
@kimsung444 sorry didn't see your reply. 

It looks like you're using Ubuntu 20.04 which absolutely should have a newer version available.  Maybe you need to run `sudo apt update` first.

I just checked on my machine and I see:
```
clamav/focal-updates,focal-security 0.103.8+dfsg-0ubuntu0.20.04.1 amd64
  anti-virus utility for Unix - command-line interface
```
