### ISSUE TITLE
ClamAV for Windows

### ISSUE THREAD

**Issue by TwoDogs2** [Cisco-Talos/clamav#979]
hello Does the Windows version have the Dynamic Directory Determination feature

**Comment by micahsnyder** [comment]
Hi @TwoDogs2

The Dynamic Directory Determination feature is a part of ClamAV's on-access scanning (clamonacc) component.  
At this time, the on-access scanning / clamonacc only exists for glibc-based Linux distributions. That is, musl-based distributions like Alpine are also not supported.
