### ISSUE TITLE
Php.Backdoor.Generic false positives on Centos 7 with Magento 2

### ISSUE THREAD

**Issue by serhiiakimov** [Cisco-Talos/clamav#980]
Describe the bug
----------------
False positives on fresh Centos 7 with Magento2
How to reproduce the problem
----------------------------

Prepare a Magento 2 build via Composer on fresh node, and run the scan onto this particular test file:

[root@ip-10-0-2-15 vagrant]# clamscan magento2/vendor/magento/magento-coding-standard/Magento2/Tests/Functions/DiscouragedFunctionUnitTest.inc

Attachments
-----------

/home/vagrant/magento2/vendor/magento/magento-coding-standard/Magento2/Tests/Functions/DiscouragedFunctionUnitTest.inc: Php.Backdoor.Generic-10006641-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8671248
Engine version: 0.103.8
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 0.02 MB
Data read: 0.01 MB (ratio 2.00:1)
Time: 1132.036 sec (18 m 52 s)
Start Date: 2023:07:27 14:18:10
End Date:   2023:07:27 14:37:02

**Comment by micahsnyder** [comment]
Please submit your false positive reports using this report form: https://www.clamav.net/reports/fp
The report will be submitted to a system maintained by our threat research team and will automatically processed.  You should expect it to take at least 48 hours before a change is seen in the signature database.
