### ISSUE TITLE
Unresolved external symbol(s) when trying to link clamav applications

### ISSUE THREAD

**Issue by aktiwari22** [Cisco-Talos/clamav#991]
environment:
host: x64-win11
compiler: msvc(vs2019)
clamav: v1.1.0

Used vcpkg cmake to compile clamav on windows according to the clamav documentation, but finally reported an error when linking each application clamav application like this:

INK : warning LNK4217: symbol 'inflate64Init2' defined in 'inflate64.obj' is imported by 'unzip.obj' in function '
unz' [C:\Users\cce\Documents\clamav-1.1.0\build\libclamav\clamav.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol
 __imp_NtCreateFile referenced in function _ZN3std3sys7windows2fs20open_link_no_reparse17h8e579f91ed4cd982E [C:\Use
rs\cce\Documents\clamav-1.1.0\build\libclamav\clamav.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol
 __imp_RtlNtStatusToDosError referenced in function _ZN3std3sys7windows2fs20open_link_no_reparse17h8e579f91ed4cd982
E [C:\Users\cce\Documents\clamav-1.1.0\build\libclamav\clamav.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol
 __imp_NtReadFile referenced in function _ZN3std3sys7windows6handle6Handle16synchronous_read17hfa39d6a5f17db40dE [C
:\Users\cce\Documents\clamav-1.1.0\build\libclamav\clamav.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol
 __imp_NtWriteFile referenced in function _ZN3std3sys7windows6handle6Handle17synchronous_write17h017470e7d9d95434E
[C:\Users\cce\Documents\clamav-1.1.0\build\libclamav\clamav.vcxproj]
C:\Users\cce\Documents\clamav-1.1.0\build\libclamav\Debug\libclamav.dll : fatal error LNK1120: 4 unresolved externa
ls [C:\Users\cce\Documents\clamav-1.1.0\build\libclamav\clamav.vcxproj]

**Comment by aktiwari22** [comment]
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.29.30151.0
-- The CXX compiler identification is MSVC 19.29.30151.0

**Comment by micahsnyder** [comment]
This looks like the same report as https://github.com/Cisco-Talos/clamav/issues/990

**Comment by aktiwari22** [comment]
Seems yes only difference is MSVC  2022 vs 2019..

LINK : warning LNK4217: symbol 'inflate64' defined in 'inflate64.obj' is import
ed by 'unzip.obj' in function 'unz' [C:\Users\clamav\build\libclamav\clamav.vcx
proj]
LINK : warning LNK4217: symbol 'inflate64End' defined in 'inflate64.obj' is imp
orted by 'unzip.obj' in function 'unz' [C:\Users\clamav\build\libclamav\clamav.
vcxproj]
LINK : warning LNK4217: symbol 'inflate64Init2' defined in 'inflate64.obj' is i
mported by 'unzip.obj' in function 'unz' [C:\Users\clamav\build\libclamav\clama
v.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error
 LNK2019: unresolved external symbol __imp_NtCreateFile referenced in function
_ZN3std3sys7windows2fs20open_link_no_reparse17h8e579f91ed4cd982E [C:\Users\clam
av\build\libclamav\clamav.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error
 LNK2019: unresolved external symbol __imp_RtlNtStatusToDosError referenced in
function _ZN3std3sys7windows2fs20open_link_no_reparse17h8e579f91ed4cd982E [C:\U
sers\clamav\build\libclamav\clamav.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error
 LNK2019: unresolved external symbol __imp_NtReadFile referenced in function _Z
N3std3sys7windows6handle6Handle16synchronous_read17hfa39d6a5f17db40dE [C:\Users
\clamav\build\libclamav\clamav.vcxproj]
clamav_rust.lib(std-4e8f46f7d0c95848.std.8cc7dfd4267f2efd-cgu.0.rcgu.o) : error
 LNK2019: unresolved external symbol __imp_NtWriteFile referenced in function _
ZN3std3sys7windows6handle6Handle17synchronous_write17h017470e7d9d95434E [C:\Use
rs\clamav\build\libclamav\clamav.vcxproj]
C:\Users\clamav\build\libclamav\RelWithDebInfo\libclamav.dll : fatal error LNK1
120: 4 unresolved externals [C:\Users\clamav\build\libclamav\clamav.vcxproj]

however - -DENABLE_APP=OFF is not working in this case. Hope this helps. Thanks

**Comment by micahsnyder** [comment]
Is this a coincidence?  Did we just break something in the `main` branch?   Or are you two working together?

**Comment by aktiwari22** [comment]
No idea. But I don't know that other person. 
I started building from yesterday from main branch so I am sure something is wrong with vcpkg cmake

**Comment by micahsnyder** [comment]
> No idea. But I don't know that other person. I started building from yesterday from main branch so I am sure something is wrong with vcpkg cmake

Hm very strange coincidence in both timing and the issue title. Because they just opened it 14 hours ago.  Will continue this in the other ticket since it was opened first.

**Comment by aktiwari22** [comment]
No issue, please keep updating in that group so I can follow on that. Thanks
