### ISSUE TITLE
Clamav 1.1.0r134 on Asustor AS6102T cannot update the virus definition database

### ISSUE THREAD

**Issue by pawol** [Cisco-Talos/clamav#995]
Completly fresh installation of Clamav 1.1.0r134 on Asustor AS6102T cannot update the virus definition database plus fault 429.

Thu Aug 10 12:59:00 2023 ->     See https://docs.clamav.net/faq/faq-eol.html for details.
Thu Aug 10 12:59:00 2023 ->  2. Run FreshClam no more than once an hour to check for updates.
Thu Aug 10 12:59:00 2023 ->     FreshClam should check DNS first to see if an update is needed.
Thu Aug 10 12:59:00 2023 ->  3. If you have more than 10 hosts on your network attempting to download,
Thu Aug 10 12:59:00 2023 ->     it is recommended that you set up a private mirror on your network using
Thu Aug 10 12:59:00 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Thu Aug 10 12:59:00 2023 ->     CDN and your own network.
Thu Aug 10 12:59:00 2023 ->  4. Please do not open a ticket asking for an exemption from the rate limit,
Thu Aug 10 12:59:00 2023 ->     it will not be granted.
Thu Aug 10 12:59:00 2023 -> WARNING: You are still on cool-down until after: 2023-08-10 14:14:13
Thu Aug 10 12:59:22 2023 -> --------------------------------------
Thu Aug 10 12:59:22 2023 -> ClamAV update process started at Thu Aug 10 12:59:22 2023
**Thu Aug 10 12:59:22 2023 -> daily database available for update (local version: 26828, remote version: 26996)
Thu Aug 10 12:59:25 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:25 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff**
Thu Aug 10 12:59:25 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:25 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:26 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:26 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:26 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:26 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:26 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:26 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 12:59:26 2023 -> WARNING: Incremental update failed, trying to download daily.cvd
Thu Aug 10 12:59:27 2023 -> WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
**Thu Aug 10 12:59:27 2023 -> WARNING: FreshClam received error code 429 from the ClamAV Content Delivery Network (CDN).**
Thu Aug 10 12:59:27 2023 -> This means that you have been rate limited by the CDN.
Thu Aug 10 12:59:27 2023 ->  1. Run FreshClam no more than once an hour to check for updates.
Thu Aug 10 12:59:27 2023 ->     FreshClam should check DNS first to see if an update is needed.
Thu Aug 10 12:59:27 2023 ->  2. If you have more than 10 hosts on your network attempting to download,
Thu Aug 10 12:59:27 2023 ->     it is recommended that you set up a private mirror on your network using
Thu Aug 10 12:59:27 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Thu Aug 10 12:59:27 2023 ->     CDN and your own network.
Thu Aug 10 12:59:27 2023 ->  3. Please do not open a ticket asking for an exemption from the rate limit,
Thu Aug 10 12:59:27 2023 ->     it will not be granted.
Thu Aug 10 12:59:27 2023 -> WARNING: You are on cool-down until after: 2023-08-10 14:14:12
Thu Aug 10 12:59:27 2023 -> main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Thu Aug 10 12:59:27 2023 -> bytecode.cvd database is up-to-date (version: 334, sigs: 91, f-level: 90, builder: anvilleg)
Thu Aug 10 13:00:00 2023 -> --------------------------------------
Thu Aug 10 13:00:00 2023 -> ClamAV update process started at Thu Aug 10 13:00:00 2023
Thu Aug 10 13:00:00 2023 -> WARNING: FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).
Thu Aug 10 13:00:00 2023 -> This means that you have been rate limited or blocked by the CDN.
Thu Aug 10 13:00:00 2023 ->  1. Verify that you're running a supported ClamAV version.
Thu Aug 10 13:00:00 2023 ->     See https://docs.clamav.net/faq/faq-eol.html for details.
Thu Aug 10 13:00:00 2023 ->  2. Run FreshClam no more than once an hour to check for updates.
Thu Aug 10 13:00:00 2023 ->     FreshClam should check DNS first to see if an update is needed.
Thu Aug 10 13:00:00 2023 ->  3. If you have more than 10 hosts on your network attempting to download,
Thu Aug 10 13:00:00 2023 ->     it is recommended that you set up a private mirror on your network using
Thu Aug 10 13:00:00 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Thu Aug 10 13:00:00 2023 ->     CDN and your own network.
Thu Aug 10 13:00:00 2023 ->  4. Please do not open a ticket asking for an exemption from the rate limit,
Thu Aug 10 13:00:00 2023 ->     it will not be granted.
Thu Aug 10 13:00:00 2023 -> WARNING: You are still on cool-down until after: 2023-08-10 14:14:12

**Comment by pawol** [comment]
After complete reinstallation I got:
Thu Aug 10 14:07:33 2023 -> --------------------------------------
Thu Aug 10 14:07:33 2023 -> ClamAV update process started at Thu Aug 10 14:07:33 2023
Thu Aug 10 14:07:33 2023 -> daily database available for update (local version: 26828, remote version: 26996)
Thu Aug 10 14:07:35 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:35 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:36 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:36 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:36 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:36 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:37 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:37 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:37 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:37 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:07:37 2023 -> WARNING: Incremental update failed, trying to download daily.cvd
Thu Aug 10 14:08:07 2023 -> WARNING: Download failed (28) Thu Aug 10 14:08:07 2023 -> WARNING:  Message: Timeout was reached
Thu Aug 10 14:08:07 2023 -> WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Thu Aug 10 14:08:07 2023 -> Trying again in 5 secs...
Thu Aug 10 14:08:12 2023 -> daily database available for update (local version: 26828, remote version: 26996)
Thu Aug 10 14:08:15 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:15 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:15 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:15 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:15 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:15 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:16 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:16 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:16 2023 -> WARNING: downloadFile: file not found: https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:16 2023 -> WARNING: downloadPatch: Can't download daily-26829.cdiff from https://database.clamav.net/daily-26829.cdiff
Thu Aug 10 14:08:16 2023 -> WARNING: Incremental update failed, trying to download daily.cvd

**Comment by micahsnyder** [comment]
@pawol I'm not sure freshclam is attempting to download the `.cdiff` patch files so many times before it attempts to download the `daily.cvd` file instead.  Unfortunately we only host the last 90 `.cdiff` patches and your database is older than that.  So when it tries to update, it seems to be getting rate limited limited before it falls back to download the whole file. 

As an aside, our CDN is presently rate limiting more than we would like and I am trying to get it fixed. Ref: https://github.com/Cisco-Talos/clamav/issues/983#issuecomment-1658789835

Please try clearing the old signature databases from your machine.  They're probably in `/usr/local/share/clamav` or else `/var/lib/clamav`. Then in 12 or maybe 24 hours, please try again with freshclam.  I think that will resolve your issue.

**Comment by pawol** [comment]
In the AS6102T there is completly different files structure then you suggest. Do you mean I should clean the content of /volume1/.@plugins/AppCentral/clamav/etc/virusdb/  ?

**Comment by pawol** [comment]
I cleaned up virusdb folder and I got:
Fri Aug 11 15:20:00 2023 -> --------------------------------------
Fri Aug 11 15:20:00 2023 -> ClamAV update process started at Fri Aug 11 15:20:00 2023
Fri Aug 11 15:20:00 2023 -> WARNING: Cool-down expired, ok to try again.
Fri Aug 11 15:20:00 2023 -> daily database available for download (remote version: 26997)
Fri Aug 11 15:20:30 2023 -> WARNING: Download failed (28) Fri Aug 11 15:20:30 2023 -> WARNING:  Message: Timeout was reached
Fri Aug 11 15:20:30 2023 -> WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Fri Aug 11 15:20:30 2023 -> Trying again in 5 secs...
Fri Aug 11 15:20:35 2023 -> daily database available for download (remote version: 26997)
Fri Aug 11 15:21:05 2023 -> WARNING: Download failed (28) Fri Aug 11 15:21:05 2023 -> WARNING:  Message: Timeout was reached
Fri Aug 11 15:21:05 2023 -> WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Fri Aug 11 15:21:05 2023 -> Trying again in 5 secs...
Fri Aug 11 15:21:10 2023 -> daily database available for download (remote version: 26997)
Fri Aug 11 15:21:40 2023 -> WARNING: Download failed (28) Fri Aug 11 15:21:40 2023 -> WARNING:  Message: Timeout was reached
Fri Aug 11 15:21:40 2023 -> WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Fri Aug 11 15:21:40 2023 -> Trying again in 5 secs...
Fri Aug 11 15:21:45 2023 -> daily database available for download (remote version: 26997)
Fri Aug 11 15:22:15 2023 -> WARNING: Download failed (28) Fri Aug 11 15:22:15 2023 -> WARNING:  Message: Timeout was reached
Fri Aug 11 15:22:15 2023 -> WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Fri Aug 11 15:22:15 2023 -> Trying again in 5 secs...
Fri Aug 11 15:22:20 2023 -> daily database available for download (remote version: 26997)
Fri Aug 11 15:22:50 2023 -> ERROR: Download failed (28) Fri Aug 11 15:22:50 2023 -> ERROR:  Message: Timeout was reached
Fri Aug 11 15:22:50 2023 -> ERROR: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Fri Aug 11 15:22:50 2023 -> Giving up on https://database.clamav.net...
Fri Aug 11 15:22:50 2023 -> daily database available for download (remote version: 26997)
Fri Aug 11 15:22:50 2023 -> WARNING: Can't download daily.cvd from https://database.clamav.net/daily.cvd
Fri Aug 11 15:22:50 2023 -> WARNING: FreshClam received error code 429 from the ClamAV Content Delivery Network (CDN).
Fri Aug 11 15:22:50 2023 -> This means that you have been rate limited by the CDN.
Fri Aug 11 15:22:50 2023 ->  1. Run FreshClam no more than once an hour to check for updates.
Fri Aug 11 15:22:50 2023 ->     FreshClam should check DNS first to see if an update is needed.
Fri Aug 11 15:22:50 2023 ->  2. If you have more than 10 hosts on your network attempting to download,
Fri Aug 11 15:22:50 2023 ->     it is recommended that you set up a private mirror on your network using
Fri Aug 11 15:22:50 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Fri Aug 11 15:22:50 2023 ->     CDN and your own network.
Fri Aug 11 15:22:50 2023 ->  3. Please do not open a ticket asking for an exemption from the rate limit,
Fri Aug 11 15:22:50 2023 ->     it will not be granted.
Fri Aug 11 15:22:50 2023 -> WARNING: You are on cool-down until after: 2023-08-12 15:22:50
Fri Aug 11 15:22:50 2023 -> main database available for download (remote version: 62)
Fri Aug 11 15:22:50 2023 -> WARNING: Can't download main.cvd from https://database.clamav.net/main.cvd
Fri Aug 11 15:22:50 2023 -> WARNING: FreshClam received error code 429 from the ClamAV Content Delivery Network (CDN).
Fri Aug 11 15:22:50 2023 -> This means that you have been rate limited by the CDN.
Fri Aug 11 15:22:50 2023 ->  1. Run FreshClam no more than once an hour to check for updates.
Fri Aug 11 15:22:50 2023 ->     FreshClam should check DNS first to see if an update is needed.
Fri Aug 11 15:22:50 2023 ->  2. If you have more than 10 hosts on your network attempting to download,
Fri Aug 11 15:22:50 2023 ->     it is recommended that you set up a private mirror on your network using
Fri Aug 11 15:22:50 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Fri Aug 11 15:22:50 2023 ->     CDN and your own network.
Fri Aug 11 15:22:50 2023 ->  3. Please do not open a ticket asking for an exemption from the rate limit,
Fri Aug 11 15:22:50 2023 ->     it will not be granted.
Fri Aug 11 15:22:50 2023 -> WARNING: You are on cool-down until after: 2023-08-12 15:22:50
Fri Aug 11 15:22:50 2023 -> bytecode database available for download (remote version: 334)
Fri Aug 11 15:22:51 2023 -> Testing database: '/usr/local/AppCentral/clamav/etc/virusdb/tmp.b83a3cb3c1/clamav-73673f79e330474c7725fbd171e4125f.tmp-bytecode.cvd' ...
Fri Aug 11 15:22:51 2023 -> Database test passed.
Fri Aug 11 15:22:51 2023 -> bytecode.cvd updated (version: 334, sigs: 91, f-level: 90, builder: anvilleg)
Fri Aug 11 15:23:00 2023 -> --------------------------------------
Fri Aug 11 15:23:00 2023 -> ClamAV update process started at Fri Aug 11 15:23:00 2023
Fri Aug 11 15:23:00 2023 -> WARNING: FreshClam previously received error code 429 or 403 from the ClamAV Content Delivery Network (CDN).
Fri Aug 11 15:23:00 2023 -> This means that you have been rate limited or blocked by the CDN.
Fri Aug 11 15:23:00 2023 ->  1. Verify that you're running a supported ClamAV version.
Fri Aug 11 15:23:00 2023 ->     See https://docs.clamav.net/faq/faq-eol.html for details.
Fri Aug 11 15:23:00 2023 ->  2. Run FreshClam no more than once an hour to check for updates.
Fri Aug 11 15:23:00 2023 ->     FreshClam should check DNS first to see if an update is needed.
Fri Aug 11 15:23:00 2023 ->  3. If you have more than 10 hosts on your network attempting to download,
Fri Aug 11 15:23:00 2023 ->     it is recommended that you set up a private mirror on your network using
Fri Aug 11 15:23:00 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Fri Aug 11 15:23:00 2023 ->     CDN and your own network.
Fri Aug 11 15:23:00 2023 ->  4. Please do not open a ticket asking for an exemption from the rate limit,
Fri Aug 11 15:23:00 2023 ->     it will not be granted.
Fri Aug 11 15:23:00 2023 -> WARNING: You are still on cool-down until after: 2023-08-12 15:22:50

**Comment by micahsnyder** [comment]
> In the AS6102T there is completly different files structure then you suggest. Do you mean I should clean the content of /volume1/.@plugins/AppCentral/clamav/etc/virusdb/ ?

This is correct.  I'm glad you found it.  It's not surprising to me that they customize where the clamav files are stored.

> Fri Aug 11 15:20:30 2023 -> WARNING: Download failed (28) Fri Aug 11 15:20:30 2023 -> WARNING: Message: Timeout was reached

This message means your `freshclam.conf` file has the `ReceiveTimeout` set and that the download time took too long so `freshclam` gave up before it was complete.  I would suggest commenting out the config line that has `ReceiveTimeout` and then try again after your rate-limit cooldown expires (again).  

I'm not sure where your `freshclam.conf` file is found.  You probably already know.  You may also find it by running the `clamconf` program which will tell you where it finds the config files, and what options are set.

**Comment by pawol** [comment]
OK, I shall try it. I have found config as below and I changed timeout onto 300 (probably in seconds)

# Automatically created by the clamav-freshclam postinst
# Comments will get lost when you reconfigure the clamav-freshclam package

DatabaseOwner root
UpdateLogFile /usr/local/AppCentral/clamav/log/freshclam.log
LogVerbose false
LogSyslog false
LogFacility LOG_LOCAL6
LogFileMaxSize 0
LogRotate true
LogTime true
Foreground false
Debug false
MaxAttempts 5
DatabaseDirectory /usr/local/AppCentral/clamav/etc/virusdb
DNSDatabaseInfo current.cvd.clamav.net
AllowSupplementaryGroups false
ConnectTimeout 30
ReceiveTimeout 300
TestDatabases yes
ScriptedUpdates yes
CompressLocalDatabase no
Bytecode true
# Check for new database 24 times a day
Checks 24
DatabaseMirror db.local.clamav.net
DatabaseMirror database.clamav.net

**Comment by pawol** [comment]
I tried to make local mirror by means of cvdupdate project from github. I got that full database download took 7 minutes.
So, inceasing of ReceveTimeout is mandatory

2023-08-11 08:33:48 PM - INFO:  Using nameservers: ['208.67.222.222', '208.67.220.220']
2023-08-11 08:33:50 PM - INFO:  Downloaded main-62.cdiff
2023-08-11 08:36:03 PM - INFO:  Downloaded main.cvd. Version: 62
2023-08-11 08:36:03 PM - INFO:  Downloaded daily-26997.cdiff
2023-08-11 08:36:54 PM - INFO:  Downloaded daily.cvd. Version: 26997
2023-08-11 08:36:55 PM - INFO:  Downloaded bytecode-334.cdiff
2023-08-11 08:36:57 PM - INFO:  Downloaded bytecode.cvd. Version: 334
2023-08-11 08:40:01 PM - ERROR:  No such database: DB

**Comment by pawol** [comment]
Done. I added in the config file DatabaseMirror https://clamav.jinr.ru and works okay. 
The deafult CDN servers are terrible

**Comment by micahsnyder** [comment]
> Can I place retrieved files manually into database folder in my NAS?

Yes, that would work.

Glad you got it working.

Please let me know if it's okay to close this issue.

**Comment by v-vovk-edvantis** [comment]
antivirus database isn't available

```
# freshclam
Creating missing database directory: /var/lib/clamav
Assigned ownership of database directory to user "clamav".
Thu Nov  9 16:19:43 2023 -> ClamAV update process started at Thu Nov  9 16:19:43 2023
Thu Nov  9 16:19:43 2023 -> ^Your ClamAV installation is OUTDATED!
Thu Nov  9 16:19:43 2023 -> ^Local version: 0.103.9 Recommended version: 0.103.11
Thu Nov  9 16:19:43 2023 -> DON'T PANIC! Read https://docs.clamav.net/manual/Installing.html
Thu Nov  9 16:19:43 2023 -> daily database available for download (remote version: 27088)
Time:    0.3s, ETA:    0.0s [========================>]        16B/16B
Thu Nov  9 16:19:43 2023 -> ^Can't download daily.cvd from https://database.clamav.net/daily.cvd
Thu Nov  9 16:19:43 2023 -> ^FreshClam received error code 429 from the ClamAV Content Delivery Network (CDN).
Thu Nov  9 16:19:43 2023 -> This means that you have been rate limited by the CDN.
Thu Nov  9 16:19:43 2023 ->  1. Run FreshClam no more than once an hour to check for updates.
Thu Nov  9 16:19:43 2023 ->     FreshClam should check DNS first to see if an update is needed.
Thu Nov  9 16:19:43 2023 ->  2. If you have more than 10 hosts on your network attempting to download,
Thu Nov  9 16:19:43 2023 ->     it is recommended that you set up a private mirror on your network using
Thu Nov  9 16:19:43 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Thu Nov  9 16:19:43 2023 ->     CDN and your own network.
Thu Nov  9 16:19:43 2023 ->  3. Please do not open a ticket asking for an exemption from the rate limit,
Thu Nov  9 16:19:43 2023 ->     it will not be granted.
Thu Nov  9 16:19:43 2023 -> ^You are on cool-down until after: 2023-11-10 10:56:12
Thu Nov  9 16:19:43 2023 -> main database available for download (remote version: 62)
Time:    0.1s, ETA:    0.0s [========================>]        16B/16B
Thu Nov  9 16:19:43 2023 -> ^Can't download main.cvd from https://database.clamav.net/main.cvd
Thu Nov  9 16:19:43 2023 -> ^FreshClam received error code 429 from the ClamAV Content Delivery Network (CDN).
Thu Nov  9 16:19:43 2023 -> This means that you have been rate limited by the CDN.
Thu Nov  9 16:19:43 2023 ->  1. Run FreshClam no more than once an hour to check for updates.
Thu Nov  9 16:19:43 2023 ->     FreshClam should check DNS first to see if an update is needed.
Thu Nov  9 16:19:43 2023 ->  2. If you have more than 10 hosts on your network attempting to download,
Thu Nov  9 16:19:43 2023 ->     it is recommended that you set up a private mirror on your network using
Thu Nov  9 16:19:43 2023 ->     cvdupdate (https://pypi.org/project/cvdupdate/) to save bandwidth on the
Thu Nov  9 16:19:43 2023 ->     CDN and your own network.
Thu Nov  9 16:19:43 2023 ->  3. Please do not open a ticket asking for an exemption from the rate limit,
Thu Nov  9 16:19:43 2023 ->     it will not be granted.
Thu Nov  9 16:19:43 2023 -> ^You are on cool-down until after: 2023-11-10 10:56:12
Thu Nov  9 16:19:43 2023 -> bytecode database available for download (remote version: 334)
Time:    0.2s, ETA:    0.0s [========================>]  285.12KiB/285.12KiB
Thu Nov  9 16:19:43 2023 -> Testing database: '/var/lib/clamav/tmp.0194c8be93/clamav-555f5cec58deef7dd629bd4eba0ba0d6.tmp-bytecode.cvd' ...
Thu Nov  9 16:19:43 2023 -> Database test passed.
Thu Nov  9 16:19:43 2023 -> bytecode.cvd updated (version: 334, sigs: 91, f-level: 90, builder: anvilleg)
Thu Nov  9 16:19:43 2023 -> Clamd successfully notified about the update.
```

**Comment by micahsnyder** [comment]
Hi @v-vovk-edvantis. It looks like you're being rate-limited much like the OP. Our database mirror continues to rate limit by IP and more aggressively than I would like.  I've escalated the issue with our web team but I do not know how long it will take to fix. 

You can find documentation on [running your own mirror here](https://docs.clamav.net/appendix/CvdPrivateMirror.html), if you want to go that route.  If not, you may have it try again later. 

I didn't get a response from the OP to my Aug 11th message.  Their issue was exacerbated by a shorter ReceiveTimeout setting and slower internet connection causing the update to fail repeatedly which triggered the rate-limiting.  I suspect that is fixed (or they gave up).  Either way, closing this issue sine no response.
